### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Deth2442** [fantasycalendar/FoundryVTT-Sequencer#101]
**Describe the bug**
An error is logged in cosole every time I launch Foundry with Sequencer active. I use the PF2E game system

**To Reproduce**
Logged in console upon launching Foundry

I have an error from Foundry V10
![image](https://user-images.githubusercontent.com/112991742/188761242-d0e8a0bf-98b1-42b5-acd2-be3dac8710d6.png)

Here is the error when using Foundry V9
![image](https://user-images.githubusercontent.com/112991742/188761299-93d3f863-6963-49e0-8864-f4ea7b55702a.png)

**Comment by Haxxer** [comment]
The first error doesn't make any sense, that would imply that the scene you're on doesn't support templates at all.

That last error seems to be Automated Animations erroring on the fact that Sequencer isn't enabled, or has errored further up in the console. Could you look for a Sequencer specific error?

**Comment by Haxxer** [comment]
Fixed in 2.3.3 (hopefully)
