### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Deth2442** [fantasycalendar/FoundryVTT-Sequencer#102]
**Describe the bug**
Still getting an error in console. Fresh world, PF2E, only Sequencer and dependencies installed

**To Reproduce**
1. Launch world
2. Press F12 to see console
3. Sequencer shows error

**Screenshots**
![image](https://user-images.githubusercontent.com/112991742/190023121-86fa1950-f8fe-4700-8f6b-a905ec3a25bb.png)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Chrome

**Comment by Haxxer** [comment]
Please include the version of the modules and systems installed.

**Comment by Deth2442** [comment]
The latest for all of the above.
PF2E is 4.0.4
Sequencer is 2.3.5
socketlib is 1.0.10

**Comment by Haxxer** [comment]
Fixed in 2.3.8
