### ISSUE TITLE
[BUG] - Effects are not deleted

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#107]
**Describe the bug**
A resurgence of a previous bug that was described on Discord. Animations stay after the document that they were attached to no longer exist.

**To Reproduce**
1. Create a Persistent Sequence that is attached to a document
2. Delete the document
3. Refresh

**Expected behavior**
The animations would be gone.

**Screenshots**
![image](https://user-images.githubusercontent.com/32039708/196967399-a99a5b19-d97e-41b1-a91e-a89cb835c150.png)

**Setup:**
 - **Foundry Version:** 10.288
 - **System Version**: Pathfinder 4.2.6
 - **Sequencer Version**: 2.3.11
 - **Browser & version** Chrome 106.0.5249.119

**Active modules:**
 - Sequencer
 - socketlib
 - PF2e Animation Macros

**Additional context**
[Discord](https://discord.com/channels/772596237605011466/881983209909391400/1029437607215628328)

**Comment by Haxxer** [comment]
Fixed in 2.3.12
