### ISSUE TITLE
[REQUEST] - Replace settings' `onChange` with v10's `requiresReload`.

### ISSUE THREAD

**Issue by krbz999** [fantasycalendar/FoundryVTT-Sequencer#108]
**Is your feature request related to a problem? Please describe.**
Not knowing which settings require a reload can be annoying. The option added in v10 fixes that by turning it into a prompt before Foundry is reloaded.

**Describe the solution you'd like**
It would be as simple as replacing all instances of `onChange: debouncedReload` in `settings.js` with `requiresReload: true`.

**Describe alternatives you've considered**
Sucking it up and doing it myself with each Sequencer update...? 🤔 

**Additional context**
This doesn't work for `Object` type settings, e.g., menus, but `onChange: () => SettingsConfig.reloadConfirm({ world: true })` is the direct method there to call the built-in Foundry prompt.

**Comment by Haxxer** [comment]
Done ages ago, hah
