### ISSUE TITLE
Request: make possible a random placement with the "Offset" method

### ISSUE THREAD

**Issue by randyrosales** [fantasycalendar/FoundryVTT-Sequencer#11]
Hi, just like the "Missed" method place the effect on a random location outside the token, is possible to add a random placement functionality to the "Offset" method but inside the token area? Thanks.

**Comment by Haxxer** [comment]
Hi! Thanks for the request - so you would imagine that calling something like `.randomOffset()` would pick a random spot within the bounds of the object given to the effect? If no token was passed, but a specific location was passed (like `.atLocation({ x: 100, y: 500 })`, should it revert to picking a random spot on that location, but within the size of the grid on the canvas?

**Comment by randyrosales** [comment]
Hi, yes to the first, the random spot would be inside the bounds of the token, and in the second case, if no token is used, i think a random spot inside the grid square (or exagon) could possibly be to small? (I´m not sure if that is what you mean when you say "within the size of the grid on the canvas"?) maybe the randomOffset should just appy to a token and not to a x,y location.
