### ISSUE TITLE
[BUG] - tieToDocuments doesn't remove across scenes

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#113]
**Describe the bug**
When removing an item that has an effect tied to it through `.tieToDocuments()`, the effect is not removed across scenes.

**To Reproduce**
1. Create a token linked to the same actor on two scenes 
2. Put an effect tied to a document on the token in one scene
3. Go to another scene to load the effect
4. Delete the document from either token
5. Go back to the other scene to see the animation still remaining

**Expected behavior**
Both animations are removed across scenes.

**Screenshots**

https://user-images.githubusercontent.com/32039708/199719649-57619f15-77b0-4b46-a1ae-e02511fee9c4.mp4

**Setup:**
 - Foundry Version: 10.288
 - System Version: Pathfinder 2e v4.3.3
 - Sequencer Version: 2.3.15
 - Browser & version Google Chrome 107.0.5304.88

**Active modules:**
Advanced Macros
PF2e Animation Macros
Compendium Folders
Item Piles
JB2A - Patreon Complete Collection
lib - Color Settings
libWrapper
socketlib
Module Management+
Monaco Macro Editor
Perfect Vision
PF2e Companion Compendia
PF2e Damage Target
pf2E Extempore Effects
PF2e Flat Check
pf2e Persistent Damage
PF2e Ranged Combat
PF2e Workbench
Quick Insert - Search Widget
Sequencer
Automated Animations
SoundFx Library
Tagger
Token Ease
PF2e Dorako UI
Warp Gate

**Comment by uniwars** [comment]
Step 3 can be not done and I still get the problem.

I get the same problem with only AA, Sequencer, PF2e Animation macro and their dependencies.

For me it seems to not work only for some effect (quickened status effect, rage effect) Edit, effects that use a macro.

Il also noticed for quickened that removing multiple status effect seems to fix the error with quickened like that :
1) Add Quickened via the token status effect HUD + add another status effect that has an animation the same way
2) Remove both with the same HUD right clicking the 2 status effect.
3) No bug.

**Comment by Haxxer** [comment]
Fixed in 2.1.16/17
