### ISSUE TITLE
[BUG] - PF2e NPCs do not work with `.tieToDocuments()`

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#114]
**Describe the bug**
When applying a persistent Sequence tied to a document on an NPC, the sequence does not get removed upon removing the document.

**To Reproduce**
1. Create an NPC-type sheet and token
2. Put on the scene and give them an effect that created a tied to itself sequence
3. Remove it
4. See error (no console logs)

**Expected behavior**
Removal of the effect.

**Screenshots**

https://user-images.githubusercontent.com/32039708/200071836-e2a15c2c-23cd-439e-9b82-51fb2cf0e4d8.mp4

**Setup:**
 - Foundry Version: 10.288
 - System Version: Pathfinder 2e v4.3.3
 - Sequencer Version: 2.3.15
 - Browser & version Google Chrome 107.0.5304.88

**Active modules:**
Advanced Macros
PF2e Animation Macros
Compendium Folders
Item Piles
JB2A - Patreon Complete Collection
lib - Color Settings
libWrapper
socketlib
Module Management+
Monaco Macro Editor
Perfect Vision
PF2e Companion Compendia
PF2e Damage Target
pf2E Extempore Effects
PF2e Flat Check
pf2e Persistent Damage
PF2e Ranged Combat
PF2e Workbench
Quick Insert - Search Widget
Sequencer
Automated Animations
SoundFx Library
Tagger
Token Ease
PF2e Dorako UI
Warp Gate

**Comment by Haxxer** [comment]
Fixed in 2.3.17
