### ISSUE TITLE
[REQUEST] - Error-less Sound Effects

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#115]
**Is your feature request related to a problem? Please describe.**
When creating an `.effect()` and picking a `.file()`, you can add a boolean to ignore the effect if the file does not exist.
`.sound()`'s `.file()` allegedly does not have that, Would be nice.

**Describe the solution you'd like**
As above.

**Additional context**
The information about this seems to be absent from the wiki, and is purely gained [through Otigon on Discord](https://discord.com/channels/772596237605011466/829025285792858202/1031194463667753000) (discord message link).

**Comment by MrVauxs** [comment]
**Additional Additional Context**
(About the information about soft failing `.file()` not being described on the wiki)
![image](https://user-images.githubusercontent.com/32039708/200677751-8f49e553-75ff-4121-9948-0c3166852e39.png)

**Comment by Haxxer** [comment]
I believe this was added a few releases ago, at least looking from my code
