### ISSUE TITLE
[BUG] - Advanced Macros Version Incompatibility

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#116]
**Describe the bug**
`.macro()` and the optional parameters from Advanced Macros no longer work, causing the macro to never be ran.

**To Reproduce**
Create two Sequencer macros, one with `.macro("Macro", args)` and one with `.macro("Macro")`
Notice how only the latter works.

**Setup:**
 - Foundry Version: 10.290
 - System Version: Pathfinder 2e 4.3.4
 - Sequencer Version: 2.3.17

**Active modules:**
 - Sequencer
 - socketlib
 - Advanced Macros 1.91.1

**Comment by Haxxer** [comment]
Fixed in 2.3.18
