### ISSUE TITLE
won't play animations from s3 bucket

### ISSUE THREAD

**Issue by modzy2** [fantasycalendar/FoundryVTT-Sequencer#117]
**Describe the bug**
WHen I am using an s3 bucket for an autoanimations &  jb2a_patreon animation location, either via the overall bucket setting of autoanimations or by an explicit aws s3 URL override for a given weapon attack, the video is not playing.  I can track it down as far as _loadtexture call in canvas-effects.js - if a URL is coming in as the value of "file", _loadtexture ends up with this.video as null when it's returning to _initialize().  I can see the URL getting loaded in the console network tab, with 200 status.  My s3 url is like
https://XXXXXXX.s3.ap-southeast-2.amazonaws.com/jb2a_patreon/Library/Generic/Weapon_Attacks/Melee/Rapier01_01_Regular_White_800x600.webm

Happens in foundry 10 with latest sequencer version.
 - Foundry Version: [e.g. 9.238]
 - System Version: [e.g. DND5e 1.5.7]
 - Sequencer Version: [e.g. 1.0.0]
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Sequencer
 - socketlib
 - autoanimations
 - jbra_patreon

**Comment by modzy2** [comment]
I see where the problem is manifested- in loadVideo in sequencer-file-cache it checks the type of blob
     if (blob?.type !== "video/webm") return false;
     
   But when mine is loaded from s3 it is "application/octet-stream"

**Comment by Haxxer** [comment]
Interesting, thank you for the info, if you're able to change that locally, does it work if you replace the `video/webm` with `application/octet-stream`?

**Comment by modzy2** [comment]
Yes well I just updated the metadata on aws s3 for the testing file and it works now.
So I can go and change all the webm metadata content-type to video/webm
I'll close this

**Comment by Haxxer** [comment]
Alright, thank you for the info! I'll add a warning to Sequencer that'll tell any further users of this exact issue.

**Comment by modzy2** [comment]
To answer your question correctly: If if comment out the test for "video/webm" it works on a file I have not corrected the metadata for (ie; if the metadata still is application/octet-stream the video still plays correctly after bypassing the check

**Comment by Haxxer** [comment]
Ah, then I will add it as an accepted type
