### ISSUE TITLE
Error in 0.5.5 with offset method

### ISSUE THREAD

**Issue by randyrosales** [fantasycalendar/FoundryVTT-Sequencer#12]
Just updated to 0.5.5 (from 0.5.1 i think) and get this error when calling the "offset" method

effect.js:216 Uncaught (in promise) ReferenceError: mergeFunc is not defined
    at EffectSection.offset (effect.js:216)

the line code of the error is:

**inOffset = mergeFunc(inOffset, options);**

And checking older versions of the module I saw that you define that **mergeFunc** a couple of lines earlier in the code but now in the 0.5.5 that function is not declared.

**Comment by Haxxer** [comment]
Thanks for the highlight, I'll fix that tonight in 0.5.6!

**Comment by randyrosales** [comment]
Thanks, btw, i think you remove the "repeats" method too, i get and error that It does not exist and looking in the code i can't find it, i think all this bugs come from the changes that you to remove the 0.7.x support. But apart from this 2 bugs, my sequences seem to work.

**Comment by Haxxer** [comment]
Fixed in 0.5.6
