### ISSUE TITLE
[REQUEST] - Include audio in effects manager

### ISSUE THREAD

**Issue by friendlylambda** [fantasycalendar/FoundryVTT-Sequencer#120]
**Is your feature request related to a problem? Please describe.**
When I'm building sequences with audio and video, I can easily stop the video via the effects manager, but not the audio.

**Describe the solution you'd like**
It would be awesome if currently playing audio was listed in the effects manager and stoppable just like video

**Describe alternatives you've considered**
Right now I'm just waiting for the audio to finish before playing the sequence again, which works but is very time consuming when I'm working on synchronizing many audio and video events

**Comment by Haxxer** [comment]
Added in 3.0.0
