### ISSUE TITLE
[REQUEST] - Warning when Photosensitive setting is blocking animations

### ISSUE THREAD

**Issue by MotoMoto1234** [fantasycalendar/FoundryVTT-Sequencer#121]
**Is your feature request related to a problem? Please describe.**
A user reported no animations working in their game.  It took us a very very long time to realize it was the new photosensitivity setting in core settings blocking it.  

**Describe the solution you'd like**
A warning that fires in console when an animation is blocked in this way by that feature.  

**Describe alternatives you've considered**

**Additional context**
It took us well over an hour to diagnose this problem in module troubleshooting as there is no hint at all that the animations are being blocked by the core setting, and everything behaves as if everything is fine.

**Comment by Haxxer** [comment]
I can add a warning, but keep in mind that _every single effect_ would have this error, which would potentially bloat the console with warnings, that for all intents and purposes, is working as intended.

**Comment by Haxxer** [comment]
Added in 2.4.2
