### ISSUE TITLE
Issue with Multilevel Tokens

### ISSUE THREAD

**Issue by ttocs240** [fantasycalendar/FoundryVTT-Sequencer#123]
When tokens are being cloned via Multilevel Tokens, animation effects are added to both the real token and the cloned token, but when removed, only one animation effect is ended automatically. 

Example using PF2e Animations - When applying the Effect: Shield item to a token that is being cloned, the animation for the Shield will activate on both tokens. But when removing the Effect; Shield item from the real token, only the animation on the clone will be ended.

**Comment by Haxxer** [comment]
I cannot do anything about this;

https://github.com/grandseiken/foundryvtt-multilevel-tokens/blob/master/multilevel.js#L1528-L1544

This portion of the code redirects any updates to the fake token to the main token, even extra data like flags and such. As such, Multilevel tokens is subverting what I expect foundry to do, and I cannot do anything about this.

**Comment by Haxxer** [comment]
I lied, it is possible. Will fix in next update.

**Comment by Haxxer** [comment]
Fixed in 2.4.2
