### ISSUE TITLE
[BUG] - `.attachTo()` uses token scale

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#124]
**Describe the bug**
When using `.attachTo()`'s `align` and `edge` properties, they are calculated based on the tokens scale, which causes them to often be way farther than they should be.

**To Reproduce**
1. Make a token with scale higher than 1
2. Make a Sequencer effect with `.attachTo(token, { align: "bottom", edge: "inner"})`

**Expected behavior**
The token scale not being included in the attached effects position.

**Screenshots**
This is "top inner" on a x1.6-x2 token.
![image](https://user-images.githubusercontent.com/32039708/209249766-620ef9e8-8b9c-41b0-89b0-fc814c991bd9.png)

**Comment by Haxxer** [comment]
Fixed in 2.4.3
