### ISSUE TITLE
[BUG] - .zeroSpriteRotation() doesn't work?

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#125]
**Describe the bug**
Just, doesn't seem to be doing anything anymore.

**To Reproduce**
Just attempt using `.zeroSpriteRotation()`...? Really don't know what I can say.

**Expected behavior**
It working.

**Screenshots**
![image](https://user-images.githubusercontent.com/32039708/209250312-45d91bdc-6f37-4c9d-95e8-a3c83f950577.png)

**Comment by Haxxer** [comment]
`.zeroSpriteRotation()` only _cancels out_ rotation applied to the `spriteContainer`. If you do not want the sprite to follow the rotation of the attached token, please use `.attachTo()`'s `followRotation: false`:

https://fantasycomputer.works/FoundryVTT-Sequencer/#/api/effect?id=attach-to
