### ISSUE TITLE
[BUG] - massive lag after teleport

### ISSUE THREAD

**Issue by Terrox** [fantasycalendar/FoundryVTT-Sequencer#126]
[foundry.anisms.com-1672437714054.log](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/10326406/foundry.anisms.com-1672437714054.log)
**Describe the bug**
Player used Blessing of the Raven Queen to misty step, everyone got massive lag, FPS tanked to 0.4.
Was not easy to diagnose.

**To Reproduce**
Unknown, teleported before but never happened like this, I have a copy of my lagging world but is 2.5GB, I'd have to clean it up a bit.
Maybe I could export the active persistent sequencer?

**Expected behavior**
If FPS is low for 20 seconds, maybe disable or popup a dialogue to disable all persistent sequences?

**Screenshots**

**Setup:**
 - Foundry Version: [e.g. 9.238]
 - System Version: [e.g. DND5e 1.5.7]
 - Sequencer Version: [e.g. 1.0.0]
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Sequencer 2.2.4
 - socketlib 1.0.10
 - all others disabled.

**Additional context**
console log attached with debug mode on.

-- a request frame error shows every 500ms

**Comment by Haxxer** [comment]
Do you have a macro you used for this? Sequencer does not implement any system specific teleportation logic, so information would be useful here.

**Comment by Terrox** [comment]
These are the likely culprits.
Blessing fires, then Resistance is applied.
Twilight Sanctuary was running but not sure if it's the one.
[fvtt-Item-blessing-of-the-raven-queen-(resistance).json.txt](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/10326410/fvtt-Item-blessing-of-the-raven-queen-.resistance.json.txt)
[fvtt-Item-blessing-of-the-raven-queen.json.txt](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/10326411/fvtt-Item-blessing-of-the-raven-queen.json.txt)
[fvtt-Item-channel-divinity_-twilight-sanctuary (1).json.txt](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/10326412/fvtt-Item-channel-divinity_-twilight-sanctuary.1.json.txt)

**Comment by Haxxer** [comment]
These are the items, though - what about the macros?

**Comment by Terrox** [comment]
the macros are in embedded ItemMacros. I had 100+ modules in use, but even with all disabled except Sequencer &
socketlib,  the slowdown was still happening.
I might set up a test world to show, though not sure you can get much out of that.
could it possibly be that the avatar image is a webp with a query string in the path? it has a path like .Token.webp?1657510015161

**Comment by Terrox** [comment]
I'll paste macro and set up a login tomorrow

**Comment by Terrox** [comment]
`// Requires the JB2A module - if you're using their free version, change the path to point to the right location
// Then add this macro's name to the bottom of the Misty Step spell in the "On Use Macro" field

let error = false;
if(!(game.modules.get("jb2a_patreon") || game.modules.get("JB2A_DnD5e"))){
    error = `You need to have JB2A installed to run this macro!`;
}

if(!game.modules.get("warpgate")?.active){
    let installed = game.modules.get("warpgate") && !game.modules.get("warpgate").active ? "enabled" : "installed";
    error = `You need to have WarpGate ${installed} to run this macro!`;
}

const tokenD = typeof args !== "undefined" && args.length !== 0 ? canvas.tokens.get(args?.[0]?.tokenId) : token;

if(!tokenD){
    error = `Could not find the token to teleport!`;
}

if(error){
    ui.notifications.error(error);
    return;
}

let range = await canvas.scene.createEmbeddedDocuments('MeasuredTemplate', [{
    t: "circle",
    user: game.user.id,
    x: tokenD.x + canvas.grid.size / 2,
    y: tokenD.y + canvas.grid.size / 2,
    direction: 0,
    distance: 30,
    borderColor: "#FF0000"
}]);

let position = await warpgate.crosshairs.show({
    size: 1,
    tag: randomID(),
    label: "Teleport to",
    drawOutline: false,
    drawIcon: false
}, { show: async (crosshair) => {

    new Sequence()
        .effect()
            .from(tokenD)
            .attachTo(crosshair)
            .persist()
            .opacity(0.5)
        .play();

}})

await range[0].delete();

new Sequence()
    .effect()
        .file("jb2a.misty_step.01.blue")
        .atLocation(tokenD)
        .randomRotation()
        .scaleToObject(2)
    .wait(750)
    .animation()
        .on(tokenD)
        .opacity(0.0)
        .waitUntilFinished()
    .animation()
        .on(tokenD)
        .teleportTo(position)
        .snapToGrid()
        .waitUntilFinished()
    .effect()
        .file("jb2a.misty_step.02.blue")
        .atLocation(tokenD)
        .randomRotation()
        .scaleToObject(2)
    .wait(1500)
    .animation()
        .on(tokenD)
        .opacity(1.0)
    .play();

// resistance power.
const skillName = 'Blessing of the Raven Queen (Resistance)';
const skillFeature = tokenD.actor.data.items.find((item) => (item.name === skillName));
  if (skillFeature) {
console.log('rolling '+skillName);
skillFeature.roll();
  }`

**Comment by Haxxer** [comment]
\`\`\`js
code here
\`\`\`
This is the proper way to put code in comments :)

**Comment by Terrox** [comment]
temporary login
http://foundry.anisms.com:30000/join
foundry
foundrytest

**Comment by Haxxer** [comment]
Thanks, I'll give it a try. What browser does your players use?

**Comment by Haxxer** [comment]
Ah, you are on version 9 of Foundry, are you not? I cannot help you to fix anything on version 9 as I do not support that version anymore.

**Comment by Terrox** [comment]
all sorts, chrome, firefox, safari, edge.
ok no probs
