### ISSUE TITLE
[REQUEST] - Optional Macros

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#127]
**Is your feature request related to a problem? Please describe.**
If a macro does not exist in your world, Sequencer will pop up an error. It would be nice to have it optionally not happen.

**Describe the solution you'd like**
Some sort of argument would be nice, but I don't know how you can fit this in with the current `.macro()` structure.

**Describe alternatives you've considered**
Having to make a macro that checks it for Sequencer is an option, but I'd rather first see if this would be possible.

**Additional context**
PF2e Animations would benefit from being able to use other modules macros, if one has them.

**Comment by Haxxer** [comment]
This should be okay in the latest with `softFail`, AFAIK
