### ISSUE TITLE
[REQUEST] - Respect Token Rotation Lock

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#128]
**Is your feature request related to a problem? Please describe.**
When you have an attached animation to a token, it follows the tokens rotation even when its locked.

**Describe the solution you'd like**
I think a default behavior where the token rotation lock is respected would be great.

**Describe alternatives you've considered**
The macro maker can look at the tokens data and do it on case by case basis, I suppose.

**Additional context**
https://github.com/MrVauxs/pf2e-jb2a-macros/issues/88

**Comment by Haxxer** [comment]
Fixed in 2.4.8
