### ISSUE TITLE
[BUG] - Effects attached to template are incorrectly rotated

### ISSUE THREAD

**Issue by Vauryx** [fantasycalendar/FoundryVTT-Sequencer#129]
**Describe the bug**
When trying to attach effects to a template, there needs to be a rotation of direction*-1 applied for the effect to attach correctly oriented.

**To Reproduce**
Create a Rectangle template with Direction 45.
Example script to visualize bug 
`let template = canvas.scene.templates.get("1ZotaZlknHSvAClC");
new Sequence()
  .effect("jb2a.wall_of_force.horizontal.blue")
  .attachTo(template)
  .fadeIn(250)
  .fadeOut(250)
  .tilingTexture({x: 1, y: 1})
  .belowTokens()
  .zIndex(-1000)
  .persist()
  .play()
`

**Screenshots**
![image](https://user-images.githubusercontent.com/32877348/213935474-a371a3e7-225d-453c-aaaf-93aa18a8b7b6.png)
![image](https://user-images.githubusercontent.com/32877348/213935476-5f55b268-f040-4f46-b584-ca7bfbd66058.png)

**Setup:**
 - Foundry Version: 10.291
 - System Version: 2.1.2
 - Sequencer Version: 2.4.3

**Active modules:**
 - Sequencer
 - socketlib
 - ASE
 - Warpgate
 -MIDI-QOL
 - DAE
 - libWrapper
 - Tagger

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.4.8
