### ISSUE TITLE
Debugger on the loose

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#13]
A debugger snuck by on effect.js 487

**Comment by Haxxer** [comment]
I... I can't find it?

**Comment by otigon** [comment]
hmm, I'll make sure I'm on the latest version and report back, I updated yesterday afternoon

**Comment by otigon** [comment]
I updated to 0.5.7 and whatever was there is gone now. Of course it's possible I was seeing things too
