### ISSUE TITLE
[BUG] - TYPE BRIEF DESCRIPTION HERE

### ISSUE THREAD

**Issue by pesky-wobbit** [fantasycalendar/FoundryVTT-Sequencer#131]
How do I fix this? Thanks!
![image](https://user-images.githubusercontent.com/477446/213943836-d816a9ce-7fef-4982-a0bb-157db9ec63a7.png)

**Comment by Haxxer** [comment]
Please do not create issues for non-bugs. This is for feature requests and bugs. If you need help with macros, ask in macro-polo or in the JB2A discord's macro channel.
