### ISSUE TITLE
[BUG] - randomOffset Warnings

### ISSUE THREAD

**Issue by pesky-wobbit** [fantasycalendar/FoundryVTT-Sequencer#132]
**Describe the bug**
Warnings in foundry after setting up your trap tutorial. 

**To Reproduce**
Follow your arrow trap tutorial: https://fantasycomputer.works/FoundryVTT-Sequencer/#/tutorials/advanced-trap

**Expected behavior**
randomoffset() warnings, see below 

**Screenshots**
![image](https://user-images.githubusercontent.com/477446/213943836-d816a9ce-7fef-4982-a0bb-157db9ec63a7.png)
![image](https://user-images.githubusercontent.com/477446/213944318-ee73b039-8ab3-4172-a534-265b3429eaec.png)
Top: Foundry warnings. Bottom: macro from your arrow trap tutorial

**Setup:**
 - Foundry Version: 10.291
 - System Version: DnD5e 2.1.2
 - Sequencer Version: 2.4.4
 - Google Chrome 109.0.5414.75

**Active modules:**
 - Sequencer
 - socketlib
 - midiQOL

**Additional context**
Seems an easy fix. I get that I'm to delete the randomOffset() lines, but I'm having trouble with the second parameter in the atLocation and stretchTo functions.

**Comment by Haxxer** [comment]
Have you checked the wiki?

https://fantasycomputer.works/FoundryVTT-Sequencer/#/api/effect?id=at-location

It even has examples:)

**Comment by pesky-wobbit** [comment]
Thank you!

**Comment by Haxxer** [comment]
Updated docs
