### ISSUE TITLE
[BUG] - new Arguments passed in Sequence can break the .shape() method

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#133]
**Describe the bug**
When passing the new Object data inside ``new Sequence(moduleName, softFail)``, if ``softFail`` is set to true, it breaks a Sequence with the ``shape()`` method. No errors thrown, just doesn't run it

**To Reproduce**
You can use this macro to replicate. Switching ``softFail`` to ``false`` will play the animation/shape on selected token. No errors are thrown when set to ``false`` or ``true``

```js
let tactor = canvas.tokens.controlled[0]

const borderData = {
 lineSize: 4,
 lineColor: game.user.color,
 radius:5,
 width: 10,
 height: 10,
 gridUnits: true,
 name: "teleBorder"
}

new Sequence({moduleName: "Test", softFail: true})
.effect()
 .persist()
 .atLocation(tactor)
 .shape("circle", borderData)
 .play()
```

**Expected behavior**
I wouldn't expect this parameter to affect ``.shape()``

**Screenshots**

**Setup:**
 - Foundry Version: 10.291
 - System Version:  DND5e 2.0.3
 - Sequencer Version: 2.4.4
 - Browser & version: Google Chrome v 109.0.5414.75

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by Haxxer** [comment]
Fixed in 2.4.6
