### ISSUE TITLE
[REQUEST] - Remove Annoying Warning

### ISSUE THREAD

**Issue by brunocalado** [fantasycalendar/FoundryVTT-Sequencer#135]
Using Automated Animations and Token Magic I trigger an animation without the need to args, but sequencer keep warning about the need to advanced macros.

Can you turn off this warning?

https://user-images.githubusercontent.com/4999783/215296779-3d1d0b2f-742a-4dff-be22-91d9543f960b.mp4

tks

**Comment by Haxxer** [comment]
If you are using automated animations that connect to macros, you will need advanced macros. I cannot control what automated animations do.

**Comment by brunocalado** [comment]
> If you are using automated animations that connect to macros, you will need advanced macros. I cannot control what automated animations do.

They also can't... :https://github.com/otigon/automated-jb2a-animations/issues/584#issuecomment-1407665456

Is it possible to add a checkbox to supress any warning?
