### ISSUE TITLE
[BUG] - .tint() method issues with .stretchTo()

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#136]
**Describe the bug**
The ``.tint()`` method appears to not work when using ``.stretchTo()`` on the effect at the same time.

**To Reproduce**
Macro to replicate:
```js
new Sequence()
 .effect()
  .atLocation(tactor)
  .file("jb2a.ray_of_frost.blue")
  .stretchTo(target)
  .tint("#FC0000")
.play()
```

**Expected behavior**
``.tint()`` would work with ``.stretchTo()``?

**Screenshots**

https://user-images.githubusercontent.com/73318661/215343649-648ea105-972d-44f9-8635-86015b68d1c4.mp4

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.4
 - Sequencer Version: 2.47

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by Haxxer** [comment]
Fixed in 2.4.8
