### ISSUE TITLE
[BUG] - "Sequencer Database Viewer" Window Layout broken on WFRP4e

### ISSUE THREAD

**Issue by Berytak** [fantasycalendar/FoundryVTT-Sequencer#137]
**Describe the bug**
Database Link and Path copy buttons cannot be clicked due to a broken layout. 

**Expected behavior**
Buttons should be readable and clickable

**Screenshots**
![Formating_Sequencer](https://user-images.githubusercontent.com/85394657/215976989-4022561f-35a0-4243-8ad8-b06039891cc4.jpg)

**Setup:**
 - Foundry Version: 10.291
 - System Version: Warhammer Fantasy Roleplay 4th Edition 6.3.1
 - Sequencer Version: 2.49
 - Browser & version: every browser and version

**Comment by Haxxer** [comment]
Looks like the system is applying styles to EVERYTHING. I'm not sure what I can do about this, except for specifically design everything to accommodate for the system.

**Comment by Berytak** [comment]
I mean the buttons are somehow clickable, but it's very frustrating to get the right point because the clickable area seems a bit off, too.
Is it even possible to have different layouts per system? If so, I think a more generous line height would help enormously.

**Comment by Haxxer** [comment]
I will look into it, but surely you must see the frustration of systems that completely override all styles of all UIs with no regard 😅

**Comment by Berytak** [comment]
> I will look into it, but surely you must see the frustration of systems that completely override all styles of all UIs with no regard 😅

I do, I definitely do. Rest assured that this is not the only module with layout problems in WFRP4e. The GUI looks great, but at what cost? 😬

**Comment by Haxxer** [comment]
Fixed in 2.410
