### ISSUE TITLE
[REQUEST] - `.waitUntilFinished(false)`

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#138]
**Is your feature request related to a problem? Please describe.**
Wanting to create a synchronized loop of `effect()` Sequences, I need the ability to add `waitUntilFinished` at the end. Adding it separately seems to have bugs, and the easiest solution would be to have `waitUntilFinished` accept `false` as an argument, ignoring the function entirely.

**Describe the solution you'd like**
`.waitUntilFinished(false)` which turns off the functionality.

**Describe alternatives you've considered**
Attempting to add the function "separately" seems to create a strange delay bug where nothing happens for a while. Example below of how that works out:
```js
sequence.effect(...)
sequence.waitUntilFinished(-200)
```

https://user-images.githubusercontent.com/32039708/216794057-2f2bc14e-0f07-4455-891b-6924df277457.mp4

**Comment by Haxxer** [comment]
Added in 2.410
