### ISSUE TITLE
[BUG] Embedded WEBM Audio Not Playing 

### ISSUE THREAD

**Issue by Cholston-LUV** [fantasycalendar/FoundryVTT-Sequencer#139]
When attempting to play a WEBM file with embedded audio as an effect, no audio is emitted.

Troubleshooting steps:

- Added volume(1) to sequence.
- Verified interface volume was max
- Verified WEBM file played with audio when natively attached to tile

**Comment by Haxxer** [comment]
@Cholston-LUV Do you have an example of a webm with audio, so I can test my fixes?

**Comment by Cholston-LUV** [comment]
[IBI Intro.webm](https://user-images.githubusercontent.com/112558541/220466049-a03bf3df-1feb-4001-a48b-b58622f09f8f.webm)

@Haxxer - Here's the exact one I couldn't get audio out of but works as a tile.

**Comment by Haxxer** [comment]
Fixed in 2.412
