### ISSUE TITLE
Problem with addOverride

### ISSUE THREAD

**Issue by randyrosales** [fantasycalendar/FoundryVTT-Sequencer#14]
I think that the method that overrides the effect data is not working correctly, and it seems to me that the problem is that the code override treatment is being executed before the generation of some data (I think), for example the "scale" which is what I'm trying to override...

for example in the effects.js file the override treatment is in this part of the code:
(line 539)
```
for(let override of this._overrides) {
    data = await override(this, data);
}
```
But then later in the code you do this (among other things)
(line 562)
```
data = await this._calculateHitVector(data);
```
and inside that _calculateHitVector_ method you calculate the "scale" and set it to data object, so my override function that try to overrride the "scale" is also being overwritten.

I´m not sure if the solution is to move the overriden part of the code to the end of the method _sanitizeEffectData_ that will fix my problem, but I´m not sure if doing that can break something else.

And yes, I know is weird that I want to overwrite something that is calculated, but I have a special case when I want to overwrite only the "Y" in the scale and let the "X" calculated.

Thanks.

**Comment by Haxxer** [comment]
I have added `addPostOverride()` as a function that will get evaluated after all of the data sanitation, hope this solves your issue!
