### ISSUE TITLE
[BUG] - moveTowards towards the same location ends with a bloodbath

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#141]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32039708/218890917-466789c6-349e-46f0-a91b-34eca4cbf891.png)

**To Reproduce**
```js
new Sequence()
    .animation()
        .moveTowards(token)
        .on(token)
    .play()
```

**Expected behavior**
Not that.

**Comment by Haxxer** [comment]
Fixed in 2.412
