### ISSUE TITLE
[REQUEST] - Toggle setting for Sequencer buttons visibility in Tokens Controls

### ISSUE THREAD

**Issue by archeresky** [fantasycalendar/FoundryVTT-Sequencer#142]
**Is your feature request related to a problem? Please describe.**
With many modules installed, the button inflation in Tokens Control can get pretty bad, I'd like to request addition of a setting to toggle Sequencer buttons visibility in Canvas Controls, all the more that those buttons double the functionality of the buttons already present under Sequencer Layer controls.

**Describe the solution you'd like**
A simple toggle option in module settings will do.

**Comment by Haxxer** [comment]
![image](https://user-images.githubusercontent.com/12858387/220465775-261077bf-89d0-4df2-9a95-9c1ae48717bc.png)

**Comment by Haxxer** [comment]
Already exists

**Comment by Haxxer** [comment]
Fair

**Comment by Haxxer** [comment]
Added in 2.412
