### ISSUE TITLE
[BUG] - screenSpaceScale({fitY: true, fitX: true}) with no input location

### ISSUE THREAD

**Issue by Gazkhan** [fantasycalendar/FoundryVTT-Sequencer#144]
**Describe the bug**
If using ``.screenSpace()`` and ``.screenSpaceScale({fitY: true, fitX: true})`` but no ``.atLocation()`` is specified, a couple of errors pop up in the console. (see image below)

**To Reproduce**
Use this macro to reproduce the error (I commented out the suggested fix): 
```js
new Sequence()
    .effect()
          .file("modules/jb2a_patreon/Library/Generic/Traps/Falling_Rocks/FallingRocks01Side_02_Regular_Grey_05x05ft_Endframe.webp")
        //.atLocation({x:0,y:0})
        .screenSpace()
        .screenSpaceScale({fitX: true, fitY: true})
        .name("Hazard")
    .play()
```

**Expected behavior**
To still display the image or animation, even if the location is not provided.
Since the location doesn't matter here (it will always be displayed centered in the middle of the page I believe), would it be possible to add a default location of ``{x: 0, y:0}``, it would make more sense here? 
Or perhaps make the center of the page the default location, if not provided? 
Note: Maybe add a soft fail when the very specific case of ``screenSpaceScale({fitX: true, fitY: true})`` is not used but the location is not provided... 

**Screenshots**
![image](https://user-images.githubusercontent.com/34525758/221323511-a8a774cb-4edb-4ee4-b4f5-94e89c877f1b.png)

**Setup:**
 - Foundry Version: [10.291]
 - System Version: [DND5e 2.1.5]
 - Sequencer Version: [2.412]
 - Browser & version [Google Chrome 110.0.5481.104]

**Active modules:**
 - Sequencer
 - socketlib

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 2.413
