### ISSUE TITLE
[BUG] - softFail fails to fail softly on wildcard sounds

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#145]
**Describe the bug**
When attempting to play a wildcard sound that doesn't exist, Sequencer throws an error despite having `softFail: true` in the class.

**To Reproduce**
Use the following macro to see the error:
```js
new Sequence({softFail: true})
    .sound()
        .file("modules/invalid-folder/arrow-fly-by-*.wav")
        .fadeInAudio(500)
        .fadeOutAudio(500)
    .play()
```

**Expected behavior**
Nothing happens in the case of the macro above. No sound is played, and no errors are made.

**Screenshots**
![image](https://user-images.githubusercontent.com/32039708/221367440-d02c17cb-77ec-4775-9ccf-f772f358b688.png)

**Setup:**
 - Foundry Version: **10.291**
 - System Version: **PF2e 4.8.1**
 - Sequencer Version: **2.412**
 - Browser & version: **Google Chrome 110.0.5481.177** 

**Additional context**
[PF2e Animations issue](https://github.com/MrVauxs/pf2e-jb2a-macros/issues/119#issuecomment-1444968526).

**Comment by Haxxer** [comment]
Fixed in 2.413
