### ISSUE TITLE
[BUG] - CSS missing in latest release, cannot be reinstalled anymore. 

### ISSUE THREAD

**Issue by apoapostolov** [fantasycalendar/FoundryVTT-Sequencer#147]
Latest version 2.415 released moments ago. 

setup.js:141 [sequencer] Metadata validation failed for module "sequencer": The file "style.css" included by module sequencer does not exist

**Comment by Haxxer** [comment]
I think you meant 2.413, but try updating again to 2.414

**Comment by apoapostolov** [comment]
Fixed. Thank you.
