### ISSUE TITLE
Error updating to latest version

### ISSUE THREAD

**Issue by rgwynnjr** [fantasycalendar/FoundryVTT-Sequencer#148]
Updating to latest version:

![image](https://user-images.githubusercontent.com/94638193/224562421-3222d4bd-ad19-4ee8-a269-d9e0c92d5f2d.png)

**Comment by Haxxer** [comment]
Please update again to 2.414:

https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues/147

Leaving this issue open for others to find

**Comment by rgwynnjr** [comment]
Thanks. All good now.
