### ISSUE TITLE
[BUG] - fadeOut doesn't seem to work properly with duration() only.

### ISSUE THREAD

**Issue by Gazkhan** [fantasycalendar/FoundryVTT-Sequencer#150]
**Describe the bug**
``fadeOut()`` works well with ``persist()`` but not with ``.duration()`` only

**To Reproduce**
using this macro, the animation disappears suddenly instead of fading out over 500 milliseconds: 
```js
new Sequence()
    .effect()
        .file("jb2a.screen_overlay.01.bad_omen.dark_black")
        .screenSpace()
        .screenSpaceScale({ fitX: true, fitY: true })
        .fadeIn(500, {ease: "easeInOutSine"})
        .duration(1000)
        .fadeOut(500, {ease: "easeInOutSine"})
        .filter("Blur")
        //.persist()
        //.name("Bad Omen")
    .play()
```

**Screenshots**
See video attached

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.5
 - Sequencer Version: 2.!417 and 2.414
 - Browser & version Google Chrome 111.0.5563.65

**Active modules:**
 - Sequencer
 - JB2A

[SequencerFadeOutBug.webm](https://user-images.githubusercontent.com/34525758/225381426-aac09954-1efd-4fa3-84f7-5bd5ae550989.webm)

**Comment by Haxxer** [comment]
Fixed in 3.0.0
