### ISSUE TITLE
[BUG] - The "Below token" option does not work.

### ISSUE THREAD

**Issue by Darronus** [fantasycalendar/FoundryVTT-Sequencer#153]
**Describe the bug**
The "below token" option does not work. Animations are played above the token regardless of the state of the "below token" option.

**To Reproduce**
When using sequencer player: select animation, select "below token" option and apply animation on token. The animation will play above the token, not below it.

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.5
 - Sequencer Version: 2.414
 - Browser & version: Latest Chrome

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A - Patreon Complete Collection

https://user-images.githubusercontent.com/47969818/229998538-7921bf47-6c04-4b21-aa97-be5e07170d2c.mp4

**Comment by Haxxer** [comment]
Fixed in 3.0.0
