### ISSUE TITLE
[BUG] - About Face & Sequencer

### ISSUE THREAD

**Issue by FreshnessDND** [fantasycalendar/FoundryVTT-Sequencer#157]
Effects triggered into animations leading to thrown hook spam. For me, it was spirit guardians animation from spell.

https://github.com/mclemente/about-face/issues/71

**Setup:**
Foundry v10.291
DnD5e 2.1.5
About Face 3.23
Sequencer 2.414

**Active modules:**
Sequencer
About Face
Midi QoL
AA
...

**Comment by Haxxer** [comment]
Based on what I can see in the error, the token has lost its actor. This is not something that Sequencer touches.
