### ISSUE TITLE
[BUG] - Sample for Lightning Teleport doesn't work on hex maps

### ISSUE THREAD

**Issue by Falkvinge** [fantasycalendar/FoundryVTT-Sequencer#162]
**Describe the bug**
The documentation-supplied sample Lightning Teleport (which is awesome) works brilliantly on square maps, but not on hex maps: the resulting teleported token ends up in a seemingly random position, while the effects play out correctly to the intended location.

**To Reproduce**
In Foundry, activate a scene with map grid "Hexagonal Rows - Odd". Select a token and activate the "Lightning Teleport" macro exactly as copied from the website. The animation will play out with the correct origin and target locations, but the token will be teleported to somewhere else entirely.

**Expected behavior**
There should be no difference in behavior between square and hex (indoor and outdoor) maps.

**Setup:**
 - Foundry Version: 10.latest
 - System Version: DND5e.current
 - Browser & version: Google Chrome

**Comment by Falkvinge** [comment]
There is no difference between 1920×1080 and 3840×2160 maps in this.

A clue could be that the teleport target snapping isn't snapping to the map's hexes, but seemingly to a grid unrelated to the map grid.

**Comment by Haxxer** [comment]
Fixed in 3.0.2
