### ISSUE TITLE
[BUG] - xray makes effects invisible

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#164]
**Describe the bug**
`.xray()` makes effects invisible

**To Reproduce**
Create a Sequencer effect with an `.xray()` in it.

**Expected behavior**
The effect appears.

**Screenshots**
https://cdn.discordapp.com/attachments/881983179920142356/1101267904898543666/chrome_KBAes4Q9rO.mp4

**Setup:**
 - Foundry Version: 10.291
 - System Version: PF2E 4.11.0
 - Sequencer Version: 3.0.1
 - Google Chrome 112.0.5615.138

**Active modules:**
 - Sequencer
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 3.0.2
