### ISSUE TITLE
[BUG] - in v3.0.3 .animation() .on(token) .opacity(0) does not work as in v3.0.1

### ISSUE THREAD

**Issue by quantiq** [fantasycalendar/FoundryVTT-Sequencer#165]
new Sequence()
.animation()
.on(token)
.opacity(0)
.play();

new Sequence()
.effect()
.from(token)
.attachTo(token)
.loopProperty("spriteContainer", "position.x", { values: [0, 25, -25, 0], duration: 10000, pingPong: true })
.loopProperty("spriteContainer", "position.y", { values: [0, -5, 5, -10, 10], duration: 1500, pingPong: true, ease: "easeInOutSine" })
.persist()
.play()

**Expected behavior**
In the macro above the token it suppose to turn its opacity to 0 then the effect to copy the image of the token and give it a looping position like a hover above the ground.

**Comment by Haxxer** [comment]
Have you tried to disable `bindAlpha` on the `.attachTo()`?

**Comment by quantiq** [comment]
That was it. I have to re-read the wiki again it seams.
