### ISSUE TITLE
[BUG] - `.opacity()` on new sequence stops existing sequence until a token is moved

### ISSUE THREAD

**Issue by InnilToo** [fantasycalendar/FoundryVTT-Sequencer#167]
**Describe the bug**
When there is an existing sequence like:
```js
await new Sequence()
  .effect()
  .attachTo(token)
  .file(file)
  .persist()
  .play({ remote: true });
```
And new sequence is played, for example a Misty Step to teleport a token:
```js
await new Sequence()
  .effect()
  .file(vanish)
  .atLocation(token)
  .randomRotation()
  .scaleToObject(2)
  .wait(750)
  .animation()
  .on(token)
  .opacity(0.0)
  .waitUntilFinished()
  .play({ remote: false });

await token.document.update(
  { x: x - canvas.grid.size / 2, y: y - canvas.grid.size / 2 },
  { animate: false }
);

await new Sequence()
  .effect()
  .file(appear)
  .atLocation(token)
  .randomRotation()
  .scaleToObject(2)
  .wait(1500)
  .animation()
  .on(token)
  .opacity(1.0)
  .play({ remote: false });
```
The `.opacity(0.0)` makes the existing animation disappear. It will reappear if the token is moved. If I go to the Sequencer Layer I can see a white box on hover where the effect should be.

**To Reproduce**
1. Run any animation on a token that persists.
2. Run a script that teleports the token with a sequence that contains `.opacity()`.
3. Animation disappears.
4. Move a token to see the original animation.

**Expected behavior**
It's okay for the original animation that was attached to the token to disappear during the transition but it should pop back once the other sequence is either over or the opacity is back to normal.

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.5
 - Sequencer Version: 3.0.5
 - Browser & version: Local and Edge Version 113.0.1774.35

**Active modules:**
 - Item Macro v1.8.0
 - JB2A v0.4.9
 - Sequencer v3.0.5
 - socketlib v1.0.12
 - Warp Gate v1.16.2

**Additional context**
Tried on a completely fresh world with the modules' default settings (except Item Macro hook).

**Comment by Haxxer** [comment]
Fixed in 3.0.6
