### ISSUE TITLE
[BUG] - filter('Glow') seems broken under v11

### ISSUE THREAD

**Issue by n0q** [fantasycalendar/FoundryVTT-Sequencer#168]
**Describe the bug**
Glow seems to generate a type error under Foundry v11. I've got the below script (and numerous iterations thereof) working fine under v10. Under v11, they only work if I comment out the `filter()` call.

**To Reproduce**
Create the following script macro, select a token, and then execute the macro. Note that any art asset will do, here.
```js
const assetName = 'jb2a.energy_wall.01.circle';

const glowData = {
    distance:                              5,
    outerStrength:                         2,
    innerStrength:                         1,
    color:            Color.from('0xff00ff'),
    quality:                             0.5,
    knockout:                          false,
}

new Sequence()
    .effect()
        .file(assetName)
        .attachTo(token)
        .filter('Glow', glowData)
    .play();
```

**Expected behavior**
Art asset should appear, attached to selected token with a purple glow. Instead, the macro generates an error in the console, and terminates.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/7948363/6dbc5e32-0d52-4368-900e-d84630a5030b)

**Setup:**
 - Foundry Version: 11.299
 - System Version:
   - Hackmaster 0.3.26
   - DnD5 - Fifth Edition System 2.2.1
 - Sequencer Version: 3.0.8
 - Browser & version: Chromium 114.0.5735.45 (Official Build) Arch Linux (64-bit)

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A - Jules and Ben's Animated Assets - Free Content

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 3.0.9
