### ISSUE TITLE
[REQUEST] - belowTokens but above tiles for effects

### ISSUE THREAD

**Issue by Krigsmaskine** [fantasycalendar/FoundryVTT-Sequencer#169]
**Is your feature request related to a problem? Please describe.**
After I became a user of Forgotten Adventures' battlemap module, which employs toggleable tiles to change the layout of their maps, I noticed that `belowTokens()` effect would get cut off, which is unfortunate. I use such effects for impact (like when being struck by something powerful) or when being tossed around.

**Describe the solution you'd like**
I'm unsure if it's feasible to accomplish the above currently, but would love if I could adjust the effect to play below tokens but still above tiles.

**Additional context**
We had the briefest of chats of this in Discord, but figured I'd throw an official issue here.

**Comment by Haxxer** [comment]
Fixed in 3.0.9
