### ISSUE TITLE
'Could not find " " in database' errors.

### ISSUE THREAD

**Issue by gravagehulk** [fantasycalendar/FoundryVTT-Sequencer#17]
I have been using Automated Animations for a while now in conjunction with JB2A. Recently, they were updated to use this module by default. Since then, I've been getting a 'Could not find " " in database' error on a regular basis. This happened when a player used a javelin, but it also happened when a skeleton from the monster manual fired an arrow. These are attacks that previously worked with no issue.

I'm on the latest 0.8.8 build of Foundry, 1.4.1 DnD5e, and the most recent versions of all three modules.

![image](https://user-images.githubusercontent.com/69117052/127651749-7a2df9f6-a83d-4b94-9730-020e69acb2ea.png)

**Comment by Haxxer** [comment]
I believe this bug is with Automated Animations, please consult Otigon on the discord server.
