### ISSUE TITLE
[BUG] - using filter in database viewer dropdown removes all entries in list

### ISSUE THREAD

**Issue by Tupsi** [fantasycalendar/FoundryVTT-Sequencer#172]
**Describe the bug**
When I open the sequencer db viewer I see automatedanimations listed in a nested tree view. Using the upper left dropdown and selecting anything offered (not matter if you do automatedanimations or "All packs") deletes al entries in the tree and only a reload of foundry brings it back.

**To Reproduce**
1. Open Sequencer DB Viewer
2. See your entries in the left pane
3. Select the upper left dropdown and select something from it (for instance autoanimations)
4. The entries in the list disappear
5. Selecting "All packs" again does not bring the list entries back, only a forced reload does that.

**Expected behavior**
The dropdown should filter what it is suppose to filter and show everything when selecting "All packs".

**Screenshots**
<img width="206" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/3730499/47297c89-e076-4920-a92d-5e2a8218b1aa">

<img width="157" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/3730499/0fdec446-7341-4b0e-8a46-e61e057a3eea">
<img width="164" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/3730499/d7805f65-36a5-4f4b-8d4b-2f0d22bb2964">

<img width="178" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/3730499/ec75bfa4-2336-45e8-bab5-7b41eb75a28e">

**Setup:**
 - Foundry Version: 11.299
 - System Version: DND5e 2.2.1
 - Sequencer Version: 3.0.9
 - Browser & version Chrome 113.0.5672.127, Edge 113.0.1774.57, Firefox 113.0.2

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by Haxxer** [comment]
Fixed in 3.0.10
