### ISSUE TITLE
[BUG] - Unable to play effect using Click and Click Hold + Drag

### ISSUE THREAD

**Issue by onekinddonut** [fantasycalendar/FoundryVTT-Sequencer#173]
**Describe the bug**
Just got Foundry V11 and was trying out Sequencer. When I try to click on the canvas while in sequence manager with an effect from the database, it would not play the effect. I was checking the logs, I keep getting this error:

canvas-lib.js:312 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 1 package: sequencer]
    at get_mouse_position (canvas-lib.js:312:61)
    at Object._evaluatePosition (sequencer-interaction-manager.js:194:20)
    at Object._evaluateCursorPosition (sequencer-interaction-manager.js:216:29)
    at Object.mouseMove (sequencer-interaction-manager.js:175:10)
    at Object._propagateEvent (sequencer-interaction-manager.js:100 :29)
    at sequencer-interaction-manager.js:76:12

So I was unsure if I am missing something or doing something wrong

**To Reproduce**
1. Go to Sequence Manager
2. Go to Player Tab
3. Input an effect from the Sequence Database Viewer
4. Click on All Users for "Play for Users:"
5. Switch to Layer and click on the canvas

**Expected behavior**
Effect plays where I click on the canvas

**Setup:**
 - Foundry Version: 11
 - System Version: DND 5e
 - Sequencer Version: 3.0.9
 - Browser & version: Google Chrome 113.0.5672.129

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A - Jules&Ben's Animated Assets

**Comment by Haxxer** [comment]
Fixed in 3.0.10
