### ISSUE TITLE
[BUG] - Effect reappearing after a reload

### ISSUE THREAD

**Issue by uniwars** [fantasycalendar/FoundryVTT-Sequencer#174]
**Describe the bug**
After a reload (f5) an animation will be still active even if the condition giving it was removed.

**To Reproduce**
On Foundry V10, Pathfinder 2 system last version, with the module PF2e Animation
Add Wounded condition to a PC token
An animation from the wounded condition will play on the token
Remove Wounded condition (by rick clicking it on the top right)
The animation will be removed with the condition
F5
The visual effect of the wounded conditoon will be visible even without the condition on the token
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/65986545/9e7b12ce-aa9c-4dd5-af13-bc874d6ee043)
To delete it we need to go in the sequencer manager to remove wounded effect.

**Expected behavior**
The effect should not come back.

**Setup:**
 - Foundry Version: 10
 - System Version: Pathfinder 2 4.12.9
 - Sequencer Version: 3.0.9
 - Browser & version Chrome last version

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A Premium
 - automated animation
 - pf2e animation

**Comment by Haxxer** [comment]
Fixed in 3.0.11
