### ISSUE TITLE
[BUG] - playbackRate() with persist() can break the loop

### ISSUE THREAD

**Issue by BenIsWassily** [fantasycalendar/FoundryVTT-Sequencer#175]
**Describe the bug**
Using `.persist()` for an asset with Intro/Loop/Outro and using `.playbackRate()` to speed up the animated asset make it not loop anymore.

**To Reproduce**
Simply use this macro
```js
let target = Array.from(game.user.targets)[0];  
    new Sequence()
    .effect()
        .file("jb2a.moonbeam.01.complete.blue")
        .atLocation(target)
        .persist()
        .name("test")
        .playbackRate(3)
        .scale(.5)
.play()
```

**Expected behavior**
It should behave like without using `.playbackRate()`, meaning it should go on a loop after playing the intro (and play the outro when the effect is ended) but at a different playback speed.

[moonbeam.webm](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34525955/2275b6df-c342-4f9e-8700-c4c569f4bcc2)

**Setup:**
 - Foundry Version: 10.291
 - System Version: DnD5e 2.2.1
 - Sequencer Version: 3.0.10
 - Browser & version Version : Chrome 114.0.5735.110

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A - Patreon Complete Collection

**Comment by Haxxer** [comment]
Fixed in 3.0.11, though playbackRate is going to make tight timings of transitions relatively unstable
