### ISSUE TITLE
[BUG] - .mask() it doesn't work as it should in Foundry v11

### ISSUE THREAD

**Issue by quantiq** [fantasycalendar/FoundryVTT-Sequencer#177]
The effect that is masked on a token is left behind when the token is moved.

Macro: 
 new Sequence()
.effect()
.file("jb2a.smoke.plumes.01.grey.1")
.mask(token)
.timeRange(1000, 7000)
.attachTo(token)
.scale(1.5)
.persist()
.play();

Video: https://streamable.com/ts3i7d

**Comment by Haxxer** [comment]
Fixed in 3.0.14
