### ISSUE TITLE
[BUG] - Unexpected behavior between repeats() and waitUntilFinished()

### ISSUE THREAD

**Issue by BenIsWassily** [fantasycalendar/FoundryVTT-Sequencer#178]
**Describe the bug**
Using this macro :
```js
let inRepetitions = 3;
let inRepeatDelayMin = 500;

let target = Array.from(game.user.targets)[0];  
    new Sequence()
    .effect()
    .file("jb2a.side_impact.part.slow.music_note.greenyellow")
    .atLocation(token)
    .rotateTowards(target)
    .scaleToObject(1.5)
    .randomizeMirrorY()
    .repeats(inRepetitions, inRepeatDelayMin)
    .waitUntilFinished(-100000)

.effect()
    .file("jb2a.side_impact.part.shockwave.yellow")
    .atLocation(token)
    .rotateTowards(target)
    .scaleToObject(1.5)
    .repeats(inRepetitions, inRepeatDelayMin)
.play()
```
I'm trying to play simultaneously two .effect() with the same number of repetitions and delay between repetitions.

Normally `.waitUntilFinished(-100000)` would not be needed, but I want to create a configurable macros with arguments to call it with automated animations. Setting a huge negative value should "disable" it when not needed (maybe there is a better way to do it?).
Unfortunately, it seems to have an undesired side effect with `.repeats()`. Both `.effect()` are not playing simultaneously.

Changing the value for `inRepeatDelayMin` to 0, seems to behave as intended (everything is fired at once), but when a positive value is set, a delay between the two `.effect()` occurs (it seems to be equal to two times the value set in this case).

[01.webm](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34525955/8617fe3e-8cd3-453c-9185-5af6672642e1)
Without `.waitUntilFinished(-100000)`

[02.webm](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34525955/79a56348-9968-4d2b-97c0-1a79690f381a)
With `.waitUntilFinished(-100000)` and any positive value set for `repeatsDelay`

[03.webm](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34525955/44d58024-484c-41ee-bc79-dbb76d18ab67)
With `.waitUntilFinished(-100000)` and  `repeatsDelay = 0`

**To Reproduce**
1. Copy the code and create a macro on FoundryVTT with it.
2. Select a token a source and target another token.
3. Execute the macro

**Expected behavior**
I would expect that setting a huge value to `.waitUntilFinished()` should not change the behavior of the effect `.repeats()`

**Setup:**
 - Foundry Version: 10.291
 - System Version: DnD5e 2.2.1
 - Sequencer Version: 3.0.10
 - Browser & version: Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A Patreon Collection
 - Tidy UI - Settings

**Comment by Haxxer** [comment]
As discussed, won't fix this due to the complex issues surrounding adjusting this in the core waiting code
