### ISSUE TITLE
[BUG] - duration() can't be used in a preset at the moment

### ISSUE THREAD

**Issue by BenIsWassily** [fantasycalendar/FoundryVTT-Sequencer#179]
**Describe the bug**
When using `.duration()` inside a preset, it throws an error.

**To Reproduce**
1. Create a preset with `.duration()` inside
```js
    Sequencer.Presets.add("drop01", (effect, { aDuration = 2500, fInDuration = 200, fOutDuration = 1000, sDuration = 400 }={}) => {
      return effect
        .duration(aDuration)
        .fadeIn(fInDuration, { ease: "easeInSine" })
        .animateProperty("spriteContainer", "scale.x", { from: 4, to: 1, duration: sDuration, ease: "easeOutBounce" })
        .animateProperty("spriteContainer", "scale.y", { from: 4, to: 1, duration: sDuration, ease: "easeOutBounce" })
        .fadeOut(fOutDuration, { ease: "easeOutCirc" })
    });
```
2. Use a macro to use the preset
```js
{
let target = Array.from(game.user.targets)[0];  
let scale = .5;

    new Sequence()
        .effect()
          .file("jb2a.icon.skull.dark_red")
          .atLocation(target)
          .scaleToObject(scale)
          .playbackRate(2)
          .preset("drop01")

.play()
}
```
3. It should trigger the same error as shown below.

**Expected behavior**
`.duration()` being taken into account when used inside a preset without triggering an error.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34525955/0c81852e-bfb8-4291-91c0-108acf4a2400)

**Setup:**
 - Foundry Version: 10.291
 - System Version: DnD5e 2.2.1
 - Sequencer Version: 3.0.10
 - Browser & version: Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A Patreon Collection
 - Tidy UI - Settings

**Comment by Haxxer** [comment]
Fixed in 3.0.11
