### ISSUE TITLE
[BUG] - Canvas pan shake not propagated to others

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-Sequencer#180]
**Describe the bug**
When using the shake function for canvas pan, that effect is not propagated to other clients. While your own canvas is shaking, it does nothing for others.

**To Reproduce**
1. Create macro or execute in web console
2. paste script provided below
3. Open another window of the instance, login with other user
4. execute macro on one machine

```js
new Sequence()
  .canvasPan()
  .shake({
    duration: 10000,
    strength: 5,
    frequency: 25,
    fadeInDuration: 1500,
    fadeOutDuration: 5500,
  })
  .play();
```

**Expected behavior**
Canvas shakes on all machines, on the current active scene

**Setup:**
 - Foundry Version: 10.297
 - System Version: Cyberpunk Red - CORE 0.86.1
 - Sequencer Version: 3.0.11
 - Browser & version Chrome

**Active modules:**
 - Sequencer
 - socketlib
no additional modules

**Additional context**
Desktop client version and NodeJS version of foundry used in tests

**Comment by Haxxer** [comment]
Fixed in 3.0.12
