### ISSUE TITLE
[REQUEST] - Add `elevation` to the `teleportTo`

### ISSUE THREAD

**Issue by theripper93** [fantasycalendar/FoundryVTT-Sequencer#182]
Add `elevation` to the `teleportTo` in order for teleportation to also take into consideration elevation for use with Core, Levels and 3D Canvas.

example:

```js
sequence.teleportTo({ x: gridPos[0], y: gridPos[1], elevation: pos.elevation })
```

**Comment by Haxxer** [comment]
Fixed in 3.0.12
