### ISSUE TITLE
[BUG] - Sequencer Database paths throwing errors

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#185]
**Describe the bug**
Depending on the database structure, the Sequencer database paths can sometimes throw errors

**To Reproduce**
1. Make sure Automated Animations is active to use the following macros
This macro works when using a database path that goes all the way to the Color.
```js
let tactor = canvas.tokens.controlled[0];
let targets = game.user.targets.first();
new Sequence()
 .effect()
 .file("autoanimations.range.weapon.lasershot.01.blue")
 .atLocation(tactor)
 .stretchTo(targets)
 .play()
```
Attempting to randomize the colors using the database path throws an error.
```js
let tactor = canvas.tokens.controlled[0];
let targets = game.user.targets.first();
new Sequence()
 .effect()
 .file("autoanimations.range.weapon.lasershot.01")
 .atLocation(tactor)
 .stretchTo(targets)
 .play()
```
throws this error:
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/73318661/336b5ee9-2f44-460c-8b3e-543ababacf97)

**Expected behavior**
The "error" type macro would choose a random color, then the correct range. This has worked in the past, so I'm not sure what version of Sequencer this started

**Setup:**
 - Foundry Version: [11.302]
 - System Version: [DND5e 2.2.1]
 - Sequencer Version: [3.0.12]
 - Automated Animations: [4.2.60]

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by Haxxer** [comment]
Fixed in 3.0.14
