### ISSUE TITLE
[BUG] - Condition Animations spawn in the upper left after swtiching scenes

### ISSUE THREAD

**Issue by aburley1234** [fantasycalendar/FoundryVTT-Sequencer#189]
**Describe the bug**
Seeing a bug I think with Sequencer. After loading into a scene with a creature with a an effect on it, loading into another scene, and then coming back to the original scene, the animations get sent to the upper lefthand corner. I don't see any errors in the log. I use PF2e Animations but I was also able to replicate this with just sequencer and JB2A Assets. 

**To Reproduce**
1. Create a world with JB2A Assets, Sequencer, and socketLib enabled
2. Drag a token onto a scene 
3. Add the Energy Strands from JB2A onto the token
4. Load into another scene
5. Load back into the original scene
6. See that the effects are now in the upper left hand corner

**Expected behavior**
Expected behavior is that the effects would remain on top of the token.

**Screenshots**
![wolf1](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/1166210/2188aa98-a0ff-40e5-840f-4c9e7441cec3)
![wolf2](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/1166210/ff67baa5-c4f7-41a6-ac13-dc807c5c23b3)

**Setup:**
Foundry Version: 11.305
PF2e System Version: 5.1.1
JB2A: 0.5.9
SocketLib: 1.0.13
Sequencer: 3.1.0
Automated Animations: 4.2.60
PF2e Animations: 2.15.5
Warp Gate: 1.17.2
Browser Version: Google Chrome Version 114.0.5735.199

**Active modules:**
JB2A
SocketLib
Sequencer
Automated Animations
PF2e Animations
Warp Gate

**Additional context**
Reported this on PF2e Animations already and they claimed it was a Sequencer bug 
https://github.com/MrVauxs/pf2e-jb2a-macros/issues/152

**Comment by Haxxer** [comment]
Fixed in 3.1.1
