### ISSUE TITLE
[BUG] - Not all persistent effects persist through scene changes

### ISSUE THREAD

**Issue by CrimsonPolar** [fantasycalendar/FoundryVTT-Sequencer#190]
**Describe the bug**
When a token has multiple persistent effects, only the most recently added effect will persist through a scene change. This is the case when the token exists on multiple scenes and they are switched between and when a token is copied and pasted into a new scene.

**To Reproduce**
1. Create 2 scenes and have an actor token in one or both.
2. Add multiple persistent effects on the token. This is most easily done with automated animations and the pf2e system's conditions. I've tested this by adding both the "drained 1" and "stupefied 1" conditions to my token.
3. Navigate to the scene with the copy of the same token, or paste the token in the new scene.
4. See that only the most recently added effect has persisted. Other effects are marked as finished in the Sequencer Manager.

**Expected behavior**
When changing scenes, all persistent effects on the token would be maintained and continue to play.

**Setup:**
 - Foundry Version: v11 build 305
 - System Version: PF2e 5.1.2
 - Sequencer Version: v3.1.1
 - Browser & version: Google Chrome v114.0.5735.199

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - JB2A
 - PF2e Animations
 - Warp Gate

**Comment by Haxxer** [comment]
Fixed in 3.1.2
