### ISSUE TITLE
[BUG] - Inconsistant Stretching

### ISSUE THREAD

**Issue by jacobwojoski** [fantasycalendar/FoundryVTT-Sequencer#191]
**Describe the bug**
Stretching different animations the same distance doesn't stretch each animation the same

(The following describes Lines Drawn in the screenshot)
- **The black** Line shows where I started and where I ended each animation. (Where I clicked on the grid) I Would expect the animation to stretch to that area
- **The Blue lines** Shows some of the animation boxes when hovering over them. (Stretched to fill that space as I would have expected)
- The Blue line animations don't always touch each of the tokens Like with the electric arc as the animation doesn't start and end touching the box. (Due to the animation having some borders on the end)
- **The Red line** Shows that some of the animations expanded past where I clicked(Black Line) to make sure it properly targeted the end square. 

- The Red distance is preferred as it means the animation actually hits the target 
- Why does this only happen with some of the animations
- Is there anyway to fix it on my end? 

![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/124112219/fd0d502a-ee20-401e-957e-493c6b1d0ea7)

**Setup:**
 - Foundry Version: [11.305]
 - System Version: [pf2e 5.1.2]
 - Sequencer Version: [3.1.1]
 - Browser & version [Foundry VTT App]

**Active modules:**
 - Sequencer
 - socketlib
 - jb2a Free Version

**Additional context**
- More of a discussion then a bug but kinda a bug and couldn't figure out how to start a discussion.

**Comment by Haxxer** [comment]
This is jb2a's configuration, if you are using database assets that they have registered.

**Comment by jacobwojoski** [comment]
@Haxxer Any chance you knows if the patreon version assets fix the issue?

**Comment by jacobwojoski** [comment]
It seems like there might be more to this issue.

Using 2 sets of points in a macro [{x:50,y:50}, {x:500,y:50}] the weird stretch happens but drawing an arrow between those 2 points using sequencer manager only having stretch selected it works fine

**Comment by Haxxer** [comment]
Each asset in the database is registered by JB2A may contain padding that is added to the right and left of the asset when played. Again, this is not an issue with sequencer, as it is decided by JB2A. Please contact their discord, further discussion here will be fruitless.
