### ISSUE TITLE
[BUG] - Dungeon draw and Sequencer conflct and cause errors

### ISSUE THREAD

**Issue by CrackJackFlood** [fantasycalendar/FoundryVTT-Sequencer#193]
**Describe the bug**
When Dungeon Draw and Sequencer is enabled sequencer doesn't work properly or at all

**To Reproduce**
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/49882452/66a9ce87-bf7a-4779-8316-c7420852a8ae)

**Comment by IHaveThatPower** [comment]
This is an issue with DungeonDraw, not Sequencer. DungeonDraw includes its own copy of the PIXI filters, which as far as I can tell is not necessary. I've submitted a pull request there to remove the offending library and its import call: https://github.com/mcglincy/dungeondraw-foundry-vtt/pull/120
