### ISSUE TITLE
[BUG] - Sequencer Manager - STOP ALL SOUNDS

### ISSUE THREAD

**Issue by Nexusprime22** [fantasycalendar/FoundryVTT-Sequencer#196]
I'm using v11 and when playing a sound with sequencer, there is a button to stop all sounds, but it does nothing and it gave this error on the console : 
Uncaught ReferenceError: undefined. SequencerAudioHelper is not defined
[Detected 1 package: sequencer]
    at HTMLButtonElement.endAllSounds

**Comment by Haxxer** [comment]
Fixed in 3.1.4
