### ISSUE TITLE
[BUG] - local offset makes the effect invisible

### ISSUE THREAD

**Issue by Nexusprime22** [fantasycalendar/FoundryVTT-Sequencer#197]
I'm using foundry v11 and I've got this sequence : 

new Sequence()
  .effect()
    .attachTo(token,{offset:{x:10,y:240},local:true,followRotation:true,bindVisibility:true})
    .file("jb2a.thunderwave.bottom_left.blue")
    .fadeIn(500)
    .fadeOut(200)
    .scaleToObject(1)
    .rotate(225)
    .tint(0x8B00FF)
    
  .effect()
  .attachTo(token,{offset:{x:10,y:240},local:true,followRotation:true,bindVisibility:true})
    .file("jb2a.side_impact.part.shockwave.blue")
    .fadeIn(500)
    .fadeOut(200)
    .scaleToObject(1)
    .rotate(270)
    .tint(0x8B00FF)

  .wait(300)
  .canvasPan()
    .shake({duration:500, strength:6})

.play()

But I've noticed that when using **local** (which worked on v10) the effect is not shown, and it is needed for the offset, so that the token can emit from his mouth the effect.

**Comment by Haxxer** [comment]
Fixed in 3.1.4
