### ISSUE TITLE
Suggestion: add an effect method to change the speed of a webm effect

### ISSUE THREAD

**Issue by DalvynPF** [fantasycalendar/FoundryVTT-Sequencer#2]
I have no idea whether it is easy/possible or not, but a method to change the speed at which a webm effect is played could be very useful, e.g. :

.file("...")
.speed(0.8)

to play the webm file at 80% of its normal speed (and .speed(1.5) to speed up the video).

Alternatively:

.file("...")
.duration(x)

to play the web file at such a speed that it lasts for x milliseconds.

(Thank you for your module!)

**Comment by Haxxer** [comment]
`.playbackRate()` kind of does what you're looking for, but `.duration()` is an interesting one. I'll add it to future potential features 👍

**Comment by Haxxer** [comment]
Reminder that all the documentation can be found [here](https://github.com/Haxxer/FoundryVTT-Sequencer/blob/master/DOCS.md) :)

**Comment by Haxxer** [comment]
Realized it wasn't documented, thank you for highlighting that! :)

**Comment by DalvynPF** [comment]
Wonderful! Thank you for updating the documentation. :)

**Comment by Haxxer** [comment]
Added `.duration()` to sounds and effects in 0.3.11
