### ISSUE TITLE
[BUG] - belowTiles seems to be broken

### ISSUE THREAD

**Issue by RHeynsZa** [fantasycalendar/FoundryVTT-Sequencer#200]
**Describe the bug**
Possibly in conjunction with other settings, but when I use `.belowTiles()`, my animation disappears.

Example script here:
```
// Get the id of the token calling his function
const source = arguments[0].tile;
const tokenId = Tagger.getTags(source)[0].split('-').pop();

const destId = args[0];
const [dest] = await Tagger.getByTag(`energy-wall-activate-${destId }`);

const laserStr = "jb2a.wall_of_force.vertical.purple";

new Sequence()
    .effect()
        .attachTo(source)
        .stretchTo(dest, { onlyX: true, attachTo: true })
        .file(laserStr)
        .fadeIn(500)
        .fadeOut(500)
        .belowTiles() // <--------- Issue here
        .name(`energy-wall-connect-animation-${tokenId}`)
        .persist()
    .play();
```
**To Reproduce**
1. Run script on top, fails to render
2. Remove belowTiles
3. Run again
4. Now it works

**Expected behavior**
I dont have any other tiles in the area, so there is no elevation or hiding behind. I just dont see the animation. It is there however

**Screenshots**
With belowTiles:
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/58415372/ba13f66e-58d4-490d-807d-37205151c2d2)

Without belowTiles
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/58415372/e5aeda7d-5ceb-4c23-9cdf-ca70a26b0fd0)

**Setup:**
 - Foundry Version: 11.307
 - System Version: 5e 2.3.1
 - Sequencer Version: 313
 - Browser & version Chrome Version 116.0.5845.112

**Active modules:**
 - Sequencer
 - socketlib
 - jb2a

**Additional context**

**Comment by Haxxer** [comment]
This should be fixed in v12 on 3.2.6
