### ISSUE TITLE
[BUG] - tint does not work with attachTo

### ISSUE THREAD

**Issue by Nexusprime22** [fantasycalendar/FoundryVTT-Sequencer#202]
When doing the sequence below, the tint does not apply on the effect, it is because of attachTo

new Sequence()
    .effect()
        .attachTo(targets[0])
        .stretchTo(token,{attachTo:true})
        .file("jb2a.energy_beam.normal.bluepink.02")
        .fadeIn(500)
        .fadeOut(500)
        .belowTokens()
        .tint(0xff0000)
.play()

**Comment by Haxxer** [comment]
Fixed with 3.2.0
