### ISSUE TITLE
[MINOR BUG] - js console reporting sequencer using deprecated call in PixiJS

### ISSUE THREAD

**Issue by galaara98** [fantasycalendar/FoundryVTT-Sequencer#206]
**Describe the bug**
not functional breaking, but should probably be addressed so that it doesnt get in the way later

**To Reproduce**
while using a browser connected to a foundry server that is showing dev tools (console tab)
while sequencer is a loaded module in a world
LOGIN to world in foundry
Look for orange warning is jsconsole related to PixiJS, expand warning to see if it is referencing sequencer 

In js console of browser: 
PixiJS Deprecation Warning: Setting interactive is deprecated, use eventMode = 'none'/'passive'/'auto'/'static'/'dynamic' instead.Deprecated since v7.2.0
index.mjs:2     at SequencerInterfaceLayer._setup (https://foundry.nodebased.server/modules/sequencer/module.js:19671:45)

**Expected behavior**
no warning from PixiJS that .../modules/sequencer/.... is using  deprecated functionality

NOTE: if it is useful, I reported the exact same issue to theripper93, for a module of theirs: light-switch (displayname lightswitch), the module code is patreon only, so I cant point you too it.  

I believe that the related configuration just need to be changed to new verbiage, or some other very slight tweaking (theripper93 mentioned in a discord chat, before they dug into it at all, that it most likely just needed to be updated to 'auto' instead of 'interactive'), but I don't want to lead you on path I have no expertise in, just trying to give you as much information as I can.

**Setup:**
 - Foundry Version: [e.g. 11.313]
 - System Version: [e.g. PF2e 5.6.2]
 - Sequencer Version: [e.g. 3.1.4]
 - Browser & version [e.g. OPERA GX 102.0.4880.90, but because it is a warning from a 3rd party .js i think this will not matter]

**Active modules:**
 - Sequencer
 - socketlib
 - No other (if other mods are loaded and one of them has the SAME issue, i don't think PixiJS will warn again, so first mod to trigger the warning is the one you can see in js console)

**Additional context**
Again, NOT FUNCTION BREAKING... just giving you a heads up that a 3rd party thing your code is using is popping off a deprecation warning.

**Comment by orangepeelbeef** [comment]
dupe of #199

**Comment by galaara98** [comment]
Closing in agreeance with [orangepeelbeef](https://github.com/orangepeelbeef)
