### ISSUE TITLE
.moveTowards() and .teleportTo() not ending at the same position given the same coordinates

### ISSUE THREAD

**Issue by Vauryx** [fantasycalendar/FoundryVTT-Sequencer#21]
Using .moveTowards() and .teleportTo() with the same coordinates does not result with the effect at the same location. 
This is the sequence in question: 
```javascript
let caster = canvas.tokens.controlled[0]
let casterImg = "Tokens/Custom/Zoris.png"
let jumpRange = caster.document._actor.data.data.abilities.str.value;
console.log(caster)
let range = MeasuredTemplate.create({
    t: "circle",
    user: game.user.id,
    x: caster.x + canvas.grid.size / 2,
    y: caster.y + canvas.grid.size / 2,
    direction: 0,
    distance: jumpRange,
    borderColor: "#FF0000",
    flags: {
        world: {
            Jump: {
                CasterId: caster.id
            }
        }
    }
});
let pos;
canvas.app.stage.addListener('pointerdown', event => {
    if (event.data.button !== 0) { return }
    pos = event.data.getLocalPosition(canvas.app.stage);
    let ray = new Ray(caster.center, pos)
    if (ray.distance > ((canvas.grid.size * (jumpRange / canvas.dimensions.distance)) + (canvas.grid.size / 2))) {
        ui.notifications.error(game.i18n.format("AUTOANIM.teleport"))
    } else {
        deleteTemplatesAndMove();
        canvas.app.stage.removeListener('pointerdown');
    }
});
async function deleteTemplatesAndMove() {

    let gridPos = canvas.grid.getTopLeft(pos.x, pos.y);

    let removeTemplates = canvas.templates.placeables.filter(i => i.data.flags.world?.Jump?.CasterId === caster.id);
    removeTemplates = removeTemplates.map(template => template.id);
    if (removeTemplates) await canvas.scene.deleteEmbeddedDocuments("MeasuredTemplate", removeTemplates);

    let jumpSeq = new Sequence()
        .animation()
        .on(caster)
        .opacity(0)
        .effect()
        .file(casterImg)
        .atLocation(caster)
        .moveTowards({ x: gridPos[0] + 50, y: gridPos[1]+ 50 }, { ease: "easeInOutElastic" })
        .scale(0.25)
        .moveSpeed(175)
        .rotate(90)
        .waitUntilFinished()
        .animation()
        .on(caster)
        .teleportTo({ x: gridPos[0]+ 50, y: gridPos[1]+ 50 })
        .waitUntilFinished()
        .animation()
        .on(caster)
        .opacity(1)
    jumpSeq.play()

}
```
Unsure if its intentional or not - its easy enough to get around by just subtracting 50 from the teleportTo x and y

https://user-images.githubusercontent.com/32877348/129249037-947f47fc-49a7-4086-98c3-880514db51e4.mp4

**Comment by Vauryx** [comment]
Adding .snapToSquare() into the .teleportTo() does make it so that it ends at the same point as the .moveTowards() given the same coords. Is that the expected behavior however? I assumed that generally speaking if given the same coords in terms of x and y then then .moveTowards() and .teleportTo() should end at the same point.

**Comment by Haxxer** [comment]
Effects on tokens are centered on the token through PIXI anchor points

**Comment by Haxxer** [comment]
In short, when you create an effect on a location and that location is a token, it's using the token center rather than the token location (which is at the top left), so when you then tell that effect to move to the left to the center of a square, it will do so, because its location is at its center.

When you tell a token to teleport, that token teleports to the location you gave it, so if you do not snap the location to the square, the top left of the token (which is the token's actual location) is put at that square's center

**Comment by Vauryx** [comment]
Ohh so .teleportTo() actually is putting it in the exact same place as .moveTowards(), but the point on the effect that it is placing on the given coord itself is different. Thanks!
