### ISSUE TITLE
When I use Spirit Gaurdian I get an error

### ISSUE THREAD

**Issue by TheMorningStarLucifer** [fantasycalendar/FoundryVTT-Sequencer#210]
**Describe the bug**

**To Reproduce**

**Expected behavior**
The animation file jb2a.spirit_gaurdian.blueyellow could not be found.
<img width="206" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/137843163/ec5dcacd-9c09-40b0-b43a-0a6197f550ab">

**Setup:**
 - Foundry Version: v11.315
 - System Version: DND5E v 2.4.0
 - Sequencer Version: v 3.1.4
 - Browser & version Google Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A
 - Chris's premade
 - Midi
 - DAE

**Additional context**

<img width="268" alt="image" src="https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/137843163/07769baa-821b-4da9-94d0-c3c9ff1f9460">

**Comment by Haxxer** [comment]
Sequencer does not control how other modules use it. As per your error, something has asked Sequencer to play `jb2a.spirit_guardians.blueyellow.undefined`, which does not exist. Log a bug with the module that uses Sequencer instead.
