### ISSUE TITLE
[REQUEST] - Add way to remove sounds effects

### ISSUE THREAD

**Issue by MJAjani** [fantasycalendar/FoundryVTT-Sequencer#215]
**Is your feature request related to a problem? Please describe.**
I have macros that use Sequencer to put music as Sound Effects, and I can't make sure that when I run the macro again, it automatically removes all sound effects at the very start of my script.

**Describe the solution you'd like**
I'd like to have a way to Remove All Sound Effects, just like in the manager, but with a function just like the "Sequencer.EffectManager.endAllEffects(inSceneId)" method.

**Describe alternatives you've considered**
If not able to have a "Sequencer.EffectManager.endAllSounds()" method, then have a "Sequencer.EffectManager.endSound(inFilters)" method that finds a sound played and stops it.

**Comment by Haxxer** [comment]
Fixed with 3.2.0
