### ISSUE TITLE
[REQUEST] - Being able to add Repeat Delay on a Persistent Aura or Effect!

### ISSUE THREAD

**Issue by Xaytal** [fantasycalendar/FoundryVTT-Sequencer#217]
**Is your feature request related to a problem? Please describe.**

I wanted to add a 15 second delay between each time the Detect Magic Effect goes off while keeping it persistent as through few modules and MIDI it allows me to "concentrate" on a spell to add and remove the effect as it feels that sometimes the detect magic repeats too much and it's too distracting as it loops currently.

**Describe the solution you'd like**

Being able to add delay between each time the animation loops/repeats while being persistent!

**Describe alternatives you've considered**

I've tried using non-persistent repeat which is possible through Automated Animations by setting for example the animation to repeat 4 times and then adding a repeat delay onto it of lets say 5 secs so that it repeats the animation 4 times with 5 sec in between each loop. But that of course doesn't work with persistent concentration where if the concentration is broken the effect is taken off since it will repeat the animation till it repeats it all the way.

**Comment by Haxxer** [comment]
Added in 3.2.6 as `.loopOptions()`
