### ISSUE TITLE
[BUG] - ScaleToObject incorrectly using token from RotateTowards instead of AtLocation

### ISSUE THREAD

**Issue by Frozedon** [fantasycalendar/FoundryVTT-Sequencer#218]
**Describe the bug**
When using the RotateTowards and the AtLocation functions on the same effect, the ScaleToObject scales based on the token given in RotateTowards instead of AtLocation.

**To Reproduce**
1. Make a primary token scaled at 1
2. Make a secondary token scaled at 2
3. Make an effect with AtLocation on the primary token, RotateTowards on the secondary token, and also use ScaleToObject.
6. See scale of effect is at 2 instead of 1.

**Expected behavior**
ScaleToObject should scale to the token given in AtLocation, not RotateTowards.

**Setup:**
 - Foundry Version: 11.315
 - Sequencer Version: 3.1.4

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A

**Comment by Haxxer** [comment]
Fixed with 3.2.0
