### ISSUE TITLE
Sound control features extesion

### ISSUE THREAD

**Issue by d1no1** [fantasycalendar/FoundryVTT-Sequencer#22]
Preface and context:
Sequencer is already the best way to tinker with animations, but what if we tinker with sounds further?!
this feature request is largely driven by a use case focused on getting visual and auditory feedback for "landing page, navigation menu buttons" but i foresee the full scope of the features to extend past it.

Objective:
Full control in macros over what sounds are played and how.

Description:
Ability to loop a sound forever with a simple flag.
Play sound just for the client triggering as opposed to all clients.
Ability to stop all sounds playing locally to a client. (optionally, being able to end all local looping sounds could possibly be better if otherwise would stop a non looping sound midway)

**Comment by Haxxer** [comment]
Great suggestions!

What should happen if someone refreshes their foundry when a looping sound is playing through Sequencer? Should it keep playing once they load again? If so, what differentiates these sounds from playlist tracks?

**Comment by Haxxer** [comment]
I have implemented `.locally()` and `.forUsers()` in the 0.6.6 branch, you can test it out here:
https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/0.6.6/release_candidate/sequencer_0.6.6_rc1.zip

`.forUsers()` expect a single user ID, or an array of user IDs for which to play

**Comment by Haxxer** [comment]
This was added in 0.6.7
