### ISSUE TITLE
[BUG] Foundry V12 - Macro Error - Foundry Summons

### ISSUE THREAD

**Issue by nlblunt** [fantasycalendar/FoundryVTT-Sequencer#222]
While using Foundry Summons in Pathfinder 2e, the summons no longer works. Looking at console, it is giving the following error.

TypeError: Cannot read properties of undefined (reading 'OWNER')
    at Proxy.<anonymous> (sequencer.js:183:72)
    at async Proxy.run (func.js:23:5)
    at async Proxy._execute (func.js:31:5)
    at async Proxy.play (sequencer.js:67:23)

Looking into it, it seems the following is the culprit perhaps?
macro.ownership.default = CONST.DOCUMENT_PERMISSION_LEVELS.OWNER;   *OWNER* undefined

DOCUMENT_PERMISSION_LEVELS was depreciated and removed in V12.

**Comment by Haxxer** [comment]
Fixed with 3.2.0
