### ISSUE TITLE
[BUG] - Issues with StretchTo Within codes

### ISSUE THREAD

**Issue by Illuxiem** [fantasycalendar/FoundryVTT-Sequencer#223]
**Describe the bug**
When trying to make macros for animations, using the "StretchTo" command doesnt seem to register?

**Expected behavior**
example for casting firebolt: start point of animation is selected token, stretchto point is the target, animation of firebolt should be played between the target and the caster.

**Setup:**
 - Foundry Version: V12
 - System Version: DND5e 3.2.1
 - Sequencer Version: 3.1.4

**Active modules:**
 - Sequencer
 - socketlib
 - D&D5e Animations
 - Automated Animations

**Comment by Haxxer** [comment]
A V12 update is in the works, and will be fixed by https://github.com/fantasycalendar/FoundryVTT-Sequencer/pull/221

**Comment by Haxxer** [comment]
Fixed with 3.2.0
