### ISSUE TITLE
[BUG] - Method timeRange prevent the animation from playing

### ISSUE THREAD

**Issue by boss-loot** [fantasycalendar/FoundryVTT-Sequencer#226]
**Describe the bug**
Method timeRange prevent the animation from playing.

**To Reproduce**
Execute this world script:
const target = Array.from(game.user.targets)[0];
  new Sequence()
    .effect()
    .file('jb2a.greatsword.melee.standard.white')
    .atLocation(token)
    .stretchTo(target)
    .timeRange(1400, 2400)
    .play();

**Expected behavior**
Expectation it's for the animation to play from 1400ms to 2400ms but it won't play. If I comment the timeRange the animation play.

**Screenshots**
No error, just the animation won't play.

**Setup:**
 - Foundry Version: [e.g. 12.327]
 - System Version: [e.g. DND5e 3.2.1]
 - Sequencer Version: [e.g. 3.2.0]
 - Tested in Foundry App

**Active modules:**
 - Sequencer
 - socketlib
 - Midi-QoL
 - DAE
 - Times-up

**Comment by Haxxer** [comment]
Could you try and see if this is fixed in the pre-release? I tested it myself, but I would like your confirmation as you are one of Sequencer's power users :)
https://github.com/fantasycalendar/FoundryVTT-Sequencer/releases/download/3.2.!9/module.json

**Comment by boss-loot** [comment]
Works perfect. Thanks.

**Comment by Haxxer** [comment]
Fixed in 3.2.1
