### ISSUE TITLE
[BUG] - Method moveTowards doesn't work

### ISSUE THREAD

**Issue by boss-loot** [fantasycalendar/FoundryVTT-Sequencer#227]
**Describe the bug**
Method moveTowards doesn't work.

**To Reproduce**
Execute this world script:
const myToken = canvas.tokens.controlled[0];
const targetToken = Array.from(game.user.targets)[0];
const elevation = targetToken.document.elevation;
const gridSize = canvas.scene.grid.size;

await new Sequence()

  .effect()
  .file('blfx.token.construct.stone3.shard.gem.obsidian.green.animated')
  .atLocation(myToken)
  .moveTowards(targetToken, { ease: 'easeOutSine' })
  .moveSpeed(2.5 * gridSize)
  .scale(0.1)
  .elevation(elevation)

  .play();

**Expected behavior**
Expectation it's for the animation move from myToken towards targetToken but instead the animation play only on myToken.

**Screenshots**
No error, just the animation won't play.

**Setup:**
 - Foundry Version: [e.g. 12.327]
 - System Version: [e.g. DND5e 3.2.1]
 - Sequencer Version: [e.g. 3.2.0]
 - Tested in Foundry App

**Active modules:**
 - Sequencer
 - socketlib
 - Midi-QoL
 - DAE
 - Times-up

**Comment by Haxxer** [comment]
Could you try and see if this is fixed in the pre-release? I tested it myself, but I would like your confirmation as you are one of Sequencer's power users :)
https://github.com/fantasycalendar/FoundryVTT-Sequencer/releases/download/3.2.!9/module.json

**Comment by boss-loot** [comment]
Works perfect. Thanks.

**Comment by Haxxer** [comment]
Fixed in 3.2.1
