### ISSUE TITLE
[BUG] - `game.settings.set` `welcome-shown` can happen before `game.ready`

### ISSUE THREAD

**Issue by rikmarais** [fantasycalendar/FoundryVTT-Sequencer#229]
**Describe the bug**
A race condition can cause `game.settings.set("sequencer", "welcome-shown", true)` to error and not update the setting, which causes the Sequencer welcome message to be displayed every time a GM logs in.

Relates to code around https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/master/src/module.js#L148

In Foundry, a world level setting cannot be set if the game is not ready.
It is possible for the `sequencer.ready` hook to be called before the `ready` hook (before `game.ready`), possibly due to it being hooked onto multiple triggers, possibly due to network conditions or other factors not commonly encountered in a self-hosting environment.

**To Reproduce**
Difficult to reproduce, due to race condition. Requires a large world and specific network conditions.

**Expected behavior**
`game.settings.set("sequencer", "welcome-shown", true)` should happen after `game.ready`. 

If `game.ready` is `false` at https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/master/src/module.js#L148, there could be a `Hooks.once('ready', ()=> ...)` to schedule the settings.set to happen only after the ready hook has fired, ensuring Foundry 

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34374883/f78b7cab-a610-4c47-82bc-67a8c1bcdb0d)

![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34374883/c68094c0-a05c-419a-abf2-8417eab22fff)

![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34374883/0df8b384-081d-440b-8a2c-04712f583ed2)

![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/34374883/7717c39e-8f5e-4049-b984-5fb55077728e)

**Setup:**
 - Foundry Version: 11.315
 - System Version: pf2e 5.16.1
 - Sequencer Version: 3.2.0
 - Browser: Firefox, latest version

**Active modules:**
 - Sequencer
 - socketlib
 - The Forge

**Additional context**
This issue was reported to Forge support. 
On Forge on small worlds, `game.ready` is true when `game.settings.set` is called, and there is no issue.
On Forge on a specific user's pf2e world which has a fair amount of data, the race condition was observed.

I believe https://github.com/fantasycalendar/FoundryVTT-Sequencer/commit/604256820c2b3f933489d402e531b6ebfb139684 was implemented as a fix, but I suspect that async/await is not the issue, and I wanted to bring the `game.ready` behaviour I saw while investigating to your attention.

That said, the user who was encountering this before said that their issue was resolved in 3.2.1, so it might be possible that I am mistaken. 
If that is the case, please accept my apologies and feel free to close the issue! 

[console-export-2024-6-18_0-54-43.txt](https://github.com/user-attachments/files/15878380/console-export-2024-6-18_0-54-43.txt)

**Comment by Haxxer** [comment]
Thanks for the detailed breakdown, fixed in 3.2.2
