### ISSUE TITLE
[BUG] - alphaFilter on animateProperty method does not work as expected

### ISSUE THREAD

**Issue by boss-loot** [fantasycalendar/FoundryVTT-Sequencer#231]
**Describe the bug**
I have a macro that simulates a spectral form using the .animateProperty('alphaFilter' ... ). The result it's a white color instead of the spectral form.

**To Reproduce**
Execute the world script:
const sourceToken = token;

new Sequence()

    //TARGET_SHAKE
    .effect()
    .from(sourceToken)
    .fadeIn(200)
    .fadeOut(200)
    .loopProperty('sprite', 'position.x', {
      from: -0.05,
      to: 0.05,
      duration: 50,
      pingPong: true,
      gridUnits: true,
    })
    .scaleToObject(sourceToken.document.texture.scaleX)
    .duration(600)
    .opacity(0.5)

    //SPECTRAL_INTRO_RIGHT
    .effect()
    .from(sourceToken)
    .animateProperty('sprite', 'position.x', {
      from: 0,
      to: 0.3,
      duration: 600,
      ease: 'easeInOutBounce',
      gridUnits: true,
    })
    .animateProperty('sprite', 'position.x', {
      from: 0,
      to: -0.3,
      duration: 1500,
      delay: 600,
      ease: 'easeInOutQuad',
      gridUnits: true,
    })
    .duration(2100)
    .opacity(0.75)
    .filter('ColorMatrix', {
      hue: 60,
      brightness: 1.5,
      contrast: 0,
      saturate: -1,
    })
    .filter('Glow', {
      outerStrength: 2,
      innerStrength: 1,
      distance: 20,
      color: 0x89cff0,
    })
    .animateProperty('alphaFilter', 'alpha', { from: 0, to: 0.75, duration: 600 })
    .animateProperty('alphaFilter', 'alpha', {
      from: 0.75,
      to: 0,
      duration: 1500,
      delay: 600,
    })

    .play();

**Expected behavior**
In previous versions the effect simulates a spectral form that shake. Now instead of the spectral form I see a white form. If the  .animateProperty('alphaFilter') are commented then it begins to look like the spectral form.

**Screenshots**

**Setup:**
 - Foundry Version: [e.g. 12.327]
 - System Version: [e.g. DND5e 3.2.1]
 - Sequencer Version: [e.g. 3.2.0]
 - Tested in Foundry App

**Active modules:**
 - Sequencer
 - socketlib
 - Midi-QoL
 - DAE
 - Times-up

**Comment by Haxxer** [comment]
Fixed in 3.2.2
