### ISSUE TITLE
Foundry gives a warning message about sequencer

### ISSUE THREAD

**Issue by GregoryWarn** [fantasycalendar/FoundryVTT-Sequencer#232]
Foundry gives a warning message about sequencer.
It is about "manifestPlusVersion" as unknown key
![Sequence Warning](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/154914479/74ccbaad-6ae5-4cff-b22b-31a3e6e2c40c)

**Comment by Haxxer** [comment]
A warning is not an error, will fix in the next update.

**Comment by Haxxer** [comment]
Fixed in 3.2.5
