### ISSUE TITLE
[BUG] - Sequencer v3.2.2 doesn't play animation

### ISSUE THREAD

**Issue by boss-loot** [fantasycalendar/FoundryVTT-Sequencer#233]
**Describe the bug**
After updating to Sequencer v3.2.2 I noticed that a lot of animations won't play. No console error, just won't play. I downgraded to Sequencer V3.2.1 and the animation play as expected.

**To Reproduce**
Sample world macro to reproduce:
const myToken = canvas.tokens.controlled[0];
const targetToken = Array.from(game.user.targets)[0];
const elevation = targetToken.document.elevation;

let sequence = new Sequence();

//ATTACK
sequence
  .effect()
  .file('jb2a.melee_attack.01.butterflysword.01.1')
  .atLocation(myToken, { gridUnits: true })
  .rotateTowards(targetToken)
  .center()
  .spriteScale(0.35)
  .spriteOffset({ x: 0.4 }, { gridUnits: true })
  .elevation(elevation)
  .waitUntilFinished(-800);
  
await sequence.play();

**Expected behavior**
An attack animation.

Setup:
 - Foundry Version: [e.g. 12.327]
 - System Version: [e.g. DND5e 3.2.1]
 - Sequencer Version: [e.g. 3.2.2]
 - Tested in Foundry App

Active modules:
 - Sequencer
 - socketlib
 - Midi-QoL
 - DAE
 - Times-up

**Comment by Haxxer** [comment]
Fixed in 3.2.3 hotfix
