### ISSUE TITLE
[BUG] - Sounds do not play and give an error

### ISSUE THREAD

**Issue by FPTheFluffyPawed** [fantasycalendar/FoundryVTT-Sequencer#237]
**Describe the bug**
Trying to play a sound results in an error.
![imagem](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/18551568/0fe0dce7-3cb1-4726-9308-adffa94c68c7)

**To Reproduce**
1. Load any scene.
2. Run the following macro:
```js
new Sequence()
	.sound("<sound>")
		.volume(0.1)
.play();
```
3. Error should appear.

**Expected behavior**
Sound should play, but instead it errors out without playing any sound.

**Setup:**
 - Foundry Version: 11.315
- System Version: Lancer 2.1.1
- Sequencer Version: 3.2.3
- Browser & version: Chrome

**Active modules:**
Tested with no modules enabled.

**Comment by Haxxer** [comment]
Fixed in 3.2.4
