### ISSUE TITLE
[BUG] - Error on using the .sound() Feature

### ISSUE THREAD

**Issue by ChasarooniZ** [fantasycalendar/FoundryVTT-Sequencer#238]
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/79132112/34e46225-9d6b-4dc0-960a-b57e822bdce6)

this is the general jist of the code I have that is triggering this error
```js
seq.sound()
    .file(getSetting(`check-animations.sfx.file.${outcome}`))
    .volume(getSetting("check-animations.sfx.volume") / 100)
    .forUsers(usersToPlayFor);
```

**Comment by Pentazer** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/54109677/73ba413f-c972-455d-8e51-6ff7798c290f)
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/54109677/68598e14-42e8-4299-98cf-dcb605a65070)
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/54109677/3e0fa1e8-3ce0-43ae-b94d-53180197f454)

Same, I'm also getting this error
```
const actorToken = this._getActorToken();
new Sequence()
    .sound()
        .file("_TTRPG_Master_Library/SFX/Combat/PulseCG.wav")
        .fadeInAudio(0)
        .fadeOutAudio(0)
.play()
```

**Comment by gambit07** [comment]
Same error here!
