### ISSUE TITLE
[BUG] - inOptions.lineColor set incorrectly

### ISSUE THREAD

**Issue by lacktheknack** [fantasycalendar/FoundryVTT-Sequencer#239]
**Describe the bug**
A sequencer error triggered with other modules, labeled "shape - inOptions.lineColor must be of type string (hexadecimal) or number (decimal)

**To Reproduce**
1. Set up Automated Animations to use the Teleportation preset for some feature
2. Attempt to use that feature

**Expected behavior**
There should be a colored outline allowing selection of teleport target.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/137741576/8f1c7f0f-51fd-4612-ad60-d073b20383ce)

**Setup:**
 - Foundry Version: 327
 - System Version: DND5e 3.2.1
 - Sequencer Version: 3.2.4
 - Browser & version Foundry Client

**Comment by Haxxer** [comment]
This is an issue with automated animations, as `game.user.color` is no longer a string, but a custom colour class. Automated animations is not even V12 ready...

**Comment by lacktheknack** [comment]
Well dang.  Automated Animations is pretty much abandoned.  Guess I gotta find an alternative.

**Comment by lacktheknack** [comment]
Welp, Automated Animations fixed it, sorry to waste your brainspace!
