### ISSUE TITLE
[BUG] - Sprite with Loop Property and PingPong on it not working

### ISSUE THREAD

**Issue by DeviousHearts** [fantasycalendar/FoundryVTT-Sequencer#240]
**Describe the bug**
The macros I have that use .from() to create a sprite seems to make the sprite scaleOut() and shrink though no such call was implemented. It also occurs in another macro where the only item in common was a sprite with loopProperty and pingPong on it. These both worked flawlessly before the last update.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup:**
 - Foundry Version: 11
 - System Version: Mutants & Masterminds 
 - Sequencer Version: 3.2.4
 - Browser & version: Brave & Chrome latest

**Active modules:**
 - Sequencer
 - socketlib
 - [insert more modules here]

**Additional context**

**Comment by Haxxer** [comment]
Please fill out the entire bug report, and provide a macro to test.

**Comment by Haxxer** [comment]
Probably fixed in 3.2.5
