### ISSUE TITLE
[BUG] - Giant Scale Teleport Preset with A-A

### ISSUE THREAD

**Issue by Kharmans** [fantasycalendar/FoundryVTT-Sequencer#241]
**Describe the bug**
When using Teleport Preset on A-A, a giant scale area is showed, that don't respect the size configured.

**To Reproduce**
Just configure any teleport preset, use it and you will see the error.

**Screenshots**
![error](https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/112586547/4b3857da-0e4a-444a-b2b1-acd42bf73a1c)

**Setup:**
 - **Foundry**: v12.327
 - **D&D5e**: v3.2.1
 - **Sequencer**: v3.2.4
 - **Automated Animations**: v4.2.73

**Active modules:**
 - Automated Animations
 - Sequencer
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 3.2.5
