### ISSUE TITLE
[BUG] - Broken Sequencer Manager Scene

### ISSUE THREAD

**Issue by Crowguard** [fantasycalendar/FoundryVTT-Sequencer#244]
I was testing various Sequencer effects and managed to brick the Sequencer manager window on this scene. Unfortunately, I don't know which combination of effects caused it (been tweaking macros for a few hours, and just noticed). Attempts result in the following error. Deleting all the tokens does fix it, but I thought it best to report this.

https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/99844555/d5e93f10-ce67-4845-995b-8f60e0e9f88e

Included is a copy of the scene; it has tokens from PF2 in case that matters.

[fvtt-Scene-broken-sequencer-manager-Nu43wIR6gUIJO5Un.zip](https://github.com/user-attachments/files/15981284/fvtt-Scene-broken-sequencer-manager-Nu43wIR6gUIJO5Un.zip)

Foundry 12.327
Sequencer 3.2.4
PF2 6.04

**Comment by Haxxer** [comment]
Please always include the error message in the body of the ticket

**Comment by Haxxer** [comment]
How on earth are you running PF2e in V12 when it doesn't even support it?

**Comment by Haxxer** [comment]
Fixed in 3.2.12
