### ISSUE TITLE
[BUG] - Persistent effects no longer loop after updating to 3.2.6

### ISSUE THREAD

**Issue by oWave** [fantasycalendar/FoundryVTT-Sequencer#248]
**Describe the bug**

On 3.2.5, this macro plays an infinitely looping effect
```
new Sequence()
    .effect()
        .attachTo(token)
        .file("jb2a.markers.fear.dark_purple.03")
        .persist()
    .play()
```

On 3.2.6, the animation freezes on the last frame.

**Screenshots**

https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/9253349/d9239825-cdf5-4937-8cf5-1853a66bacfc

**Setup:**
 - Foundry Version: 12.327 and 11.315
 - System Version: pf2e 6.04/5.16.1
 - Sequencer Version: 3.2.6
 - Browser & version: Chrome 123.0.6312.86

**Active modules**
- jb2a_pateron
- sequencer
- socketlib

**Comment by Haxxer** [comment]
Fixed in 3.2.7
