### ISSUE TITLE
[BUG] - Canvas Freeze on Measurement Controls

### ISSUE THREAD

**Issue by gambit07** [fantasycalendar/FoundryVTT-Sequencer#250]
**Describe the bug**
Canvas freezes when switching to Measurement Controls for a template placed with a sequencer effect

https://github.com/fantasycalendar/FoundryVTT-Sequencer/assets/4236874/c0825661-4714-4b94-8455-18a14b71966e

Error:
`sequencer-animation-engine.js:175 Uncaught TypeError: undefined. Cannot create property 'value' on number '1.0175'
[Detected 1 package: sequencer]
    at Object._animateAttribute (sequencer-animation-engine.js:175:41)
    at sequencer-animation-engine.js:135:9
    at Array.forEach (<anonymous>)
    at Object._animate (sequencer-animation-engine.js:134:6)
    at sequencer-animation-engine.js:102:48
    at Array.forEach (<anonymous>)
    at Object.nextFrame (sequencer-animation-engine.js:102:20)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)`

Sequencer effect:
`	new Sequence()
		.effect()
		.file("jb2a.black_tentacles") //assets/animations/animated_spells/black_tentacles_border.webm
		.scaleToObject(1)
		.attachTo(template, { align: "right", edge: "on" })
		.delay(500)
		.scaleIn(0, 500, {ease: "easeOutCubic"})
		.fadeIn(500)
		.fadeOut(500)
		.mask()
		.belowTokens()
		.persist()
		.play()`

**To Reproduce**
1. Create a template with the sequencer effect above attached on template creation
2. Switch to Measurement Controls
3. Canvas freezes and the error is generated

**Setup:**
 - Foundry Version: 12.328
 - System Version: 5e 3.2.1
 - Sequencer Version: 3.2.8
 - Browser: Rippers FVTT Player Client 1.5.4

**Active modules:**
 - Sequencer
 - socketlib
 - [insert more modules here]

**Comment by Haxxer** [comment]
Fixed in 3.2.9

**Comment by Haxxer** [comment]
Sorry about that, please redownload sequencer, the fixed release should be okay

**Comment by gambit07** [comment]
> Sorry about that, please redownload sequencer, the fixed release should be okay

Not a problem, appreciate it!
