### ISSUE TITLE
[BUG] - endEffects and getEffects cannot handle names with spaces

### ISSUE THREAD

**Issue by Stexinator** [fantasycalendar/FoundryVTT-Sequencer#251]
**Describe the bug**
endEffects and getEffects cannot handle names with spaces

**To Reproduce**
1. Create an named effect with a space in the name e.g "Ghoul (1)"
2. Use above methods
3. See error -> Effects are not ended/found

**Expected behavior**
It finds the effects

**Screenshots**

**Setup:**
 - Foundry Version: 11.315
 - Sequencer Version: 3.2.9

**Active modules:**
 - Sequencer
 - socketlib

**Comment by Haxxer** [comment]
What is the error?

**Comment by Stexinator** [comment]
There is no error. Simply nothing happens

**Comment by Haxxer** [comment]
It may be because of `(` and `)`, as those are valid regex. What happens if you name the effect "test test", and try to find it?

**Comment by Stexinator** [comment]
With "test test" in the name it does not work same for "test(test)" So both are a problem. The " (1)" is automatically append by foundry when you enable automatic numbering.

**Comment by Haxxer** [comment]
Fixed in 3.2.10
