### ISSUE TITLE
[REQUEST] - Get the list of played files

### ISSUE THREAD

**Issue by absymylyar** [fantasycalendar/FoundryVTT-Sequencer#253]
When using data from sequencer database, is there a way to get, in advance, the list of files which sequence is about to play, before calling the ".play()".
For example to get the precise list of files to "preload", which is better than whole database entries.

**Comment by Haxxer** [comment]
Would a `preload` parameter on `Sequence#play` suit your purpose? If set to `true`, it will preload all files that will play in the sequence for all connected users.

**Comment by absymylyar** [comment]
That would be perfect indeed !
If you like, I can help, I contribute already on DnD5e system, and on those next couple of month, on summer, I will have some free time...
I have also conceptual idea to syndronize video and sound

**Comment by Haxxer** [comment]
Added with 3.2.11
