### ISSUE TITLE
[BUG] - Error on items whose names have a comma

### ISSUE THREAD

**Issue by carolinex** [fantasycalendar/FoundryVTT-Sequencer#262]
**Describe the bug**
Automated animations are not triggered when a weapon has a name with the special character "," - such as "crossbow, light". Browser console shows an error:
```Invalid regular expression: /^crossbow\,light$/gu: Invalid escape (at sequencer-effect-manager.js:198:23)```

**To Reproduce**
1. Target a token
2. Attack using "Crossbow, light" or any weapon with a comma in its name
3. Verify that attack animation is not triggered
4. Open Chrome console logs to verify error

**Expected behavior**
Animations should be triggered with no error

**Screenshots**
<img width="356" alt="image" src="https://github.com/user-attachments/assets/586fc1ff-5a2d-4256-8585-1d696090bae4">
<img width="347" alt="image" src="https://github.com/user-attachments/assets/bb9f68b4-bb5d-41e6-841b-ff28ef43ccac">

**Setup:**
 - Foundry Version: 12.328
 - System Version: DND5e 3.2.1
 - Sequencer Version: 3.2.10
 - Browser & version: Google Chrome 126.0.6478.127

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - D&D Beyond Gamelog
 - D&D Animations
 - Dynamic effects using Active Effects (DAE)
 - libWrapper
 - Midi QOL

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 3.2.11
