### ISSUE TITLE
CanvasPan().shake() causes game freeze when frequency = 0

### ISSUE THREAD

**Issue by napolitanod** [fantasycalendar/FoundryVTT-Sequencer#265]
**Describe the bug**
Running the sequencer .shake() causes Foundry to freeze. This appears to happen when the frequency is 0. It may also required the duration and strength be set > 0. I have not tested around the boundaries of the error, just can recreate it consistently with the macro provided.

**To Reproduce**
1. On a square gridded scene (not sure if grid matters), execute this macro as script: 
new Sequence().canvasPan().shake({
                            duration: 1000,
                            strength: 10,
                            frequency: 0
                        }).play()

**Expected behavior**
No shake occurs due to frequency being 0.

**Screenshots**
n/a

**Setup:**
 - Foundry Version: V12 328
 - System Version: DND5e 3.2.1
 - Sequencer Version: 3.2.10
 - Browser & version: using the Foundry App (is that proton??)

**Active modules:**
 - Sequencer
 - socketlib
 - all other deactivated

**Additional context**
I don't need to run with 0 frequency, simply reporting due to the impact to Foundry when run this way.

**Comment by Haxxer** [comment]
Fixed in 3.2.12
