### ISSUE TITLE
[BUG] - Cyrillic symbols parsing gives error 

### ISSUE THREAD

**Issue by ElijahaF** [fantasycalendar/FoundryVTT-Sequencer#267]
**Describe the bug**
Animation doesn't work for ranged attacks and effects if name of item (skill or effect) has cyrillic symbols.
It works fine for 'melee' and 'on token' animations.

**To Reproduce**
1. Add spell 
[fvtt-Item-ognennyj-snaryad-_-fire-bolt-LLxBUKo9XzafG8tu.json](https://github.com/user-attachments/files/16253326/fvtt-Item-ognennyj-snaryad-_-fire-bolt-LLxBUKo9XzafG8tu.json)
to any actor.
3. Check that animation enabled and successfully recognized in Automated Animations tab for the spell.
4. Cast the spell on another actor (target distance attack).
5. Get error in console. No animation.

**Expected behavior**
Animation should work as it works with standard 'fire bolt' spell.

**Screenshots**
![Sequencer error](https://github.com/user-attachments/assets/23bd7b00-fddf-4f77-b9ec-1606d708048f)

**Setup:**
 - Foundry Version: 12.328
 - System Version: DND5e 3.2.0
 - Sequencer Version: 3.2.10
 - Browser & version: Google Chrome 126.0.6478.127 

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - Midi QoL and related
 - Argon Combat HUD
 - Tidy 5e Sheets
 
 All modules on screenshot:
![image](https://github.com/user-attachments/assets/1f8284f7-c999-41a2-a2b2-f5f63eb24627)

**Additional context**
It has worked fine before I updated Foundry Version from 11 to 12 with all modules on july. 
I'm not sure which Sequencer version I had before this global update.

**Comment by Haxxer** [comment]
I would recommend updating as this was fixed in 3.2.11 - you can see this in the latest releases and changelog.

**Comment by ElijahaF** [comment]
Thanks, it was super fast. It works :D

**Comment by Haxxer** [comment]
I didn't do anything, the update was already out when you posted this issue lol
