### ISSUE TITLE
[BUG] - Adding a text to sprite with "rotateTowards" changes the anchor point

### ISSUE THREAD

**Issue by Codas** [fantasycalendar/FoundryVTT-Sequencer#268]
Adding a text to an effect that is positioned with "rotateTowards" sets the anchor at an unexpected location.

Every effect is positioned at `1500x1000`, with 200 units y-offset for each following effect.
In the following screenshot, the first entry is just positioned using `rotateTowards` to the right, second is the same but with a text added, third is as before but using `rotate(0)` instead of `rotateTowards`.
<img width="980" alt="rotateTowards with text behavior" src="https://github.com/user-attachments/assets/5af73121-c66f-4780-ba6c-9ca26788dc7a">

Effects 1 and 3 are positioned correctly, whereas effect 2 I think should look just like 1 but with a text added and centered at the effects location, like in the third screenshot.

Code used to create these effects:

```js
const textStyle = { fill: "#ffffff", strokeThickness: 5 }

new Sequence()
  .effect()
  .file("jb2a.energy_beam.normal.bluepink.03")
  .atLocation({ x: 1500, y: 1000 })
  .rotateTowards({ x: 2000, y: 1000 })
  .play()

new Sequence()
  .effect()
  .file("jb2a.energy_beam.normal.bluepink.03")
  .atLocation({ x: 1500, y: 1200 })
  .rotateTowards({ x: 2000, y: 1200 })
  .text("with text", textStyle)
  .play()

new Sequence()
  .effect()
  .file("jb2a.energy_beam.normal.bluepink.03")
  .atLocation({ x: 1500, y: 1400 })
  .rotate(0)
  .text("with text and rotate(0)", textStyle)
  .play()

```

**Comment by Haxxer** [comment]
Fixed in 3.4.0
