### ISSUE TITLE
[BUG] "stretchTo" breaks looping via "persist"

### ISSUE THREAD

**Issue by TheNittles** [fantasycalendar/FoundryVTT-Sequencer#269]
**Describe the bug**
When an effect uses the stretchTo method, the effect will cease looping properly when it's also using the persist method.

**To Reproduce**
1. Create a sequence with an animated effect
2. Have the effect stretchTo a point of your choice.
3. Have the effect persist
4. Let the effect play through its entire animation. The effect will remain on the canvas but stop animating.

**Expected behavior**
The effect animation should loop to the beginning of its animation again,

**Screenshots**

https://github.com/user-attachments/assets/9b956497-8d7d-41b1-b76a-fcf44832067c

Here's a recording of a macro I use that uses stretchTo to create a conduit between two points. As you can see, it stops animating after one loop.

**Setup:**
 - Foundry Version: v11.315
 - System Version: LANCER v2.1.7
 - Sequencer Version: v3.2.11
 - Browser & version: Google Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Active modules:**
 - Sequencer
 - WarpGate
 - JB2A
 - Advanced Macros

**Additional context**
This problem appears to be exclusive to the 3.2 versions. I tried a few different releases and found that. 3.1.4 is the latest one that does not have this issue.

**Comment by Haxxer** [comment]
I believe this has been fixed in previous versions

**Comment by chrisk123999** [comment]
This bug appears to still be happening on version 3.3.6.

**Comment by Haxxer** [comment]
Fixed in 3.4.0
