### ISSUE TITLE
[BUG] - loopOptions method doesn't work as expected

### ISSUE THREAD

**Issue by boss-loot** [fantasycalendar/FoundryVTT-Sequencer#270]
**Describe the bug**
I am using the loopOptions (former noLoop) method on an animation and the animation dissapear after it finished. The expectation was that the animation expands and remain visible untill the effect it's deleted.

**To Reproduce**
1. Run the world macro:
```js
const targetToken = token;
  new Sequence()
    //BLOOD GROUND
    .effect()
    .file('jb2a.liquid.splash.blue')
    .name('visualName')
    .opacity(0.9)
    .atLocation(targetToken)
    .tint(0xff0000)
    .randomizeMirrorY()
    .randomRotation()
    .timeRange(0, 1000)
    .loopOptions({ loops: 1 })
    .fadeOut(500)
    .elevation(0, { absolute: true })
    .persist()

    .play();
```

**Expected behavior**
The expectation was that the animation expands and remain visible untill the effect it's deleted.

**Setup:**
 - Foundry Version: [e.g. 12.329]
 - System Version: [e.g. DND5e 3.3.0]
 - Sequencer Version: [e.g. 3.2.11]
 - Executed from Foundry app.

**Active modules:**
 - Sequencer
 - socketlib
 - Midi
 - Dae
 - Times-uo

**Comment by Haxxer** [comment]
Fixed in 3.4.0
