### ISSUE TITLE
[BUG] - Playback rate of flipbooks depend on momentary framerate

### ISSUE THREAD

**Issue by Codas** [fantasycalendar/FoundryVTT-Sequencer#274]
Flipbooks currently exhibit inconsistent playback rates that vary with the current frame rate and are relative to the frame rate when the flipbook animation was first started.

Reproducing it can be finicky in certain cases, but the easiest way is: Set FPS in foundry to 60 or something like that. Create a flipbook animation and play it. In the best case scenario, the animation will play back as if set to 24 fps. lower the framerate in foundry to 30. The animation will now play with 12 fps.

The reason for this is that the AnimatedSprite implementation by default plays each frame for exactly one rendered frame. With a fixed 60 fps, the hardcoded playbackRate lets the animation correctly play at 24 fps. 

In reality however, many systems cannot handle a static 60 fps wheras others have the framerate unlocked to above 60.

The AnimatedSprite has the possibility to instead of a list of textures be supplied with a list of `FrameObject`s that encode timing information for each frame together with the texture to be played.

**Comment by Haxxer** [comment]
Fixed in 3.4.0
