### ISSUE TITLE
[BUG] when using scaleIn and scaleOut together, scaleOut is affected by the scaleIn value

### ISSUE THREAD

**Issue by Codas** [fantasycalendar/FoundryVTT-Sequencer#276]
**Describe the bug**
Essentially, when using this sequence:
```js
new Sequencer().effect().file('effect.webm').scaleIn(0.5).scaleOut(2).play()
```
the `scaleOut` animation part will seemingly not happen.

The reason for this is that the `_determineScale` function on `canvas-effect.js` takes into account the initial set scaleIn factor before calculating the scaleOut animation.

I would expect the abaove sequence insted to animate in from a scale of 0.5 to 1, then display the majority of the animation at scale 1 and finally scale out to a scale of 2 compared to the regular size after the scaleIn has completed.

**Comment by Haxxer** [comment]
Fixed in 3.4.0
