### ISSUE TITLE
[BUG] - stretchTo - inLocation is invalid, and must be of type of object, string, placeable object, or document

### ISSUE THREAD

**Issue by Pentazer** [fantasycalendar/FoundryVTT-Sequencer#278]
**Describe the bug**
[Magic Missile sample sequencer](https://fantasycomputer.works/FoundryVTT-Sequencer/#/sample-macros?id=magic-missile) does not work as copied exactly from the sequencer website. I was testing my macros and found that previously many of my older macros are no longer working. IE:

```
//Melee Attack
const source = this._getActorToken();
new Sequence()
//Melee
	.effect()
		.file("jb2a.shortsword.melee.01.white.5")	//The Attack
		.atLocation(this.object.target)
		.scale(1)
		.waitUntilFinished(-2600)
//Sound Effect
	.sound()
		.file("_TTRPG_Master_Library/SFX/FFVI/SwordSlash.2")	//Sound Effect
		.fadeInAudio(0)
		.fadeOutAudio(0)
		.waitUntilFinished(-700)
//Melee
	.effect()
		.file("jb2a.shortsword.melee.01.white")	//The Attack
		.atLocation(this.object.target)
		.scale(1)
		.waitUntilFinished(-2200)
//Sound Effect
	.sound()
		.file("_TTRPG_Master_Library/SFX/FFVI/SwordSlash.4")	//Sound Effect
		.fadeInAudio(0)
		.fadeOutAudio(0)
.play()
```

So I decided to copy the magic missile macro to see if something was up only to find that it produces that error. 

**To Reproduce**
1. Create macro, copied exactly from sequencer database
2. Select the Attacker
3. Target the target
4. Execute macro

**Expected behavior**
Should fire the magic missile as described on the sequencer database, but it instead produces that error. 

**Screenshots**

**Setup:**
 - Foundry Version: 12.328
 - System Version: DND5e 3.3.1
 - Sequencer Version: 3.2.11
 - Browser & version: None, foundry desktop client.

**Active modules:**
 - Sequencer
 - socketlib
 - JB2a Free
 - Module Management +

**Additional context**
Using the two stage sword attack written above absolutely nothing happens anymore. This previously was working on past editions of foundry but now suddenly its not with the latest updates?

**Comment by Haxxer** [comment]
Did you select two tokens when you ran the macro?

**Comment by Pentazer** [comment]
Ah okay that got the magic missile example to work.
But I'm still facing the issue that the melee attack's not doing anything.
If I select A and target B, nothing.
if I select A and B and target B, still nothing.

Weirdly enough, it's NOTHING. not even an error message.

**Comment by Haxxer** [comment]
Your macro is referencing `this.object.target`, I don't see how that is defined anywhere in the macro. You are most likely dependent on a macro module that adds that as a variable. Not a sequencer issue, since the sample works.

**Comment by Pentazer** [comment]
Perfect, thanks. That makes a lot of sense. The macro format above are part of a LONG list of animation and sound macros I created for Exalted 3e system I figured they could just migrate over to D&D but it seems like there are element changes between the two so I'll need to make a new set for D&D instead. That clears it up!
