### ISSUE TITLE
[BUG] - Unable to open Show Sequencer Manager 

### ISSUE THREAD

**Issue by gambit07** [fantasycalendar/FoundryVTT-Sequencer#280]
**Describe the bug**
Under certain conditions, the Show Sequencer Manager panel fails to open.

**To Reproduce**
The show sequencer manager panel fails to open with the error below, this seems to occur when switching between gridded and gridless on a scene

**Expected behavior**
show sequencer manager opens

**Screenshots**

https://github.com/user-attachments/assets/6fd0877b-fbeb-465b-8e1c-30bee0f91b4c

foundry.js:655 Error: An error occurred while rendering EffectsUIApp 38. Cannot read properties of undefined (reading 'type')
[Detected 1 package: sequencer(3.2.11)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5794:13

**Setup:**
 - Foundry Version: 12.330
 - System Version: 5e 3.3.1
 - Sequencer Version: 3.2.11
 - Browser & version Rippers Browser 1.5.4

**Active modules:**
 - Sequencer
 - socketlib
 - [insert more modules here]

**Additional context**

**Comment by MrVauxs** [comment]
Try disabling elevation ruler.

**Comment by gambit07** [comment]
> Try disabling elevation ruler.

Yeah I've tried that, doesn't make a difference in the behavior. Another odd thing is that switch between gridded and gridless will cause animations to appear. They are animations that were previously placed on the canvas, but do not show up as current effects when sequencer manager is opened. After switching grid type they become visible, but sequencer manager is unable to be opened so they cannot be deleted. I'm wondering if this is an issue with animations that were unable to be removed due to specific circumstances and that is the underlying issue

**Comment by Haxxer** [comment]
Fixed in 3.2.12
