### ISSUE TITLE
[REQUEST] - FoundrySummons whith Portal

### ISSUE THREAD

**Issue by GabrielAlvesSilva** [fantasycalendar/FoundryVTT-Sequencer#282]
Hello,

Since the WarpGate module was discontinued, I have been trying to find a way to replace it.

I found the Portal module by theripper93. Is there any possibility for FoundrySummons to be updated to work with the Portal module?

These are the errors that occur when I try to summon in Foundry V12, but I believe the main reason is that the WarpGate module is no longer being updated.

![image](https://github.com/user-attachments/assets/bbe04c7d-ff24-4d1d-ba97-97e88cc7db37)

![image](https://github.com/user-attachments/assets/1a4c4060-1371-4452-9570-fa3764a0a214)

![image](https://github.com/user-attachments/assets/caa12c33-b4ce-4b70-9c2d-93313f912c68)

![image](https://github.com/user-attachments/assets/690ade23-322f-4dd6-a194-0cc2dfd1f093)

Thank you for your time.

**Comment by Haxxer** [comment]
Portal is not Sequencer? I'm not sure what I can do about Portal within Sequencer...?
