### ISSUE TITLE
[BUG] - Sound macro executes with no sound (Still)

### ISSUE THREAD

**Issue by Pentazer** [fantasycalendar/FoundryVTT-Sequencer#283]
**Describe the bug**
see issue #279
https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues/279
Same issue, still doesn't seem to be working with latest version.

**To Reproduce**
Exact same process as in #279 

**Setup:**
 - Foundry Version: 12.330 and 12.328 (Tested in both)
 - System Version: DND5e 3.3.1
 - Sequencer Version: 3.2.12
 - Browser & version: None, foundry desktop client.

**Additional context**
This time I had the debugger up when I found out you could do that:
![image](https://github.com/user-attachments/assets/b81ecd4e-21f8-4915-a1ca-c65e422fc286)

Again, just to be sure, I tested it in automated-animations and the sound does play in Foundry.

**Comment by Haxxer** [comment]
Fixed in 3.2.13 (thanks Vauxs!)
