### ISSUE TITLE
[BUG] Template Effects are broken with 3.2.12

### ISSUE THREAD

**Issue by nschoenwald** [fantasycalendar/FoundryVTT-Sequencer#284]
**Describe the bug**
Using Foundry V12, dnd5e 3.3, latest version of Automated Animations and Sequencer, Fire Breath from Red Dragons and Magma Mephits breaks. Probably applies to more effects, but those are the ones I tested with and can reproduce with no modules enabled other than AA, Sequencer socketlib. They work correctly in 3.2.11.

**Comment by iansutherland75** [comment]
2nd this.  On V11 too.

**Comment by Haxxer** [comment]
Fixed in 3.2.13
