### ISSUE TITLE
[BUG] - Animations Visible in Fog of Exploration

### ISSUE THREAD

**Issue by NovabusterX** [fantasycalendar/FoundryVTT-Sequencer#285]
**Describe the bug**
Animations are visible in Fog of War, while players do not have line of sight, when they should not be visible.

**To Reproduce**
1. Have an animation playing on a map. Can be on another token, or a tile.
2. Have a player see the animation and map area.
3. Have the player move their token out of line of sight from the animation. Usually behind a wall.
4. Animation will still be visible in fog of war, even though the token doesn't have line of sight.

**Expected behavior**
When a token/player moves out of line of sight from an animation, they should not still see the animation playing in the fog of war.

**Screenshots**
![image](https://github.com/user-attachments/assets/ceb719f3-aa8b-4eae-9543-042e5f005c4d)
Player is behind 3 walls and can still see animation on the stage floating around another player.
Player can also see the portal tile to the right that is behind the exterior wall that.

**Setup:**
 - Foundry Version: [12.330]
 - System Version: [PF2e 6.2.0]
 - Sequencer Version: [3.2.12]
 - Browser & version [Google Chrome 127.0.6533.90]

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - JB2A Animated Assets

**Additional context**
If the animation is a tile, the players can see me hide and unhide it behind walls in Fog of Exploration.

**Comment by Haxxer** [comment]
Fixed in 3.2.15
