### ISSUE TITLE
PF2E Reach error

### ISSUE THREAD

**Issue by Eligor** [fantasycalendar/FoundryVTT-Sequencer#29]
Hello, i'm using this module on the Pathfinder 2e system, and when an actor is out of reach of another actor, a red error just popout to warn me that the module can't reproduce the animation. The thing is that sometimes when a player or an npc provoke AoO, they first move the token, and then i/they roll the attack, so obviously the token is out of reach of the animation.
Is there a way to remove the error from my game, or even removing the warning completely?

**Comment by Haxxer** [comment]
Hi, could you please press F12 and open the console to see what the error is exactly?

Are you using Sequencer to move tokens?

**Comment by Eligor** [comment]
![image](https://user-images.githubusercontent.com/13001096/133002274-ef31a9f8-8acb-44a0-81ee-0880fdd71fd7.png)
this is the console error

Sequencer to move token? i don't think so, it's just the "drag the token by clicking on it" kind of movement.
by the way, the animation works fine if the token are close, but as soon as the token is out of reach, the error popup
