### ISSUE TITLE
[BUG] - Sound volume scales on both music and interface volume sliders

### ISSUE THREAD

**Issue by tyrielv** [fantasycalendar/FoundryVTT-Sequencer#294]
**Describe the bug**
Sounds played with sequencer are quiet unless both the music and interface sliders are turned up.

**To Reproduce**
1. Turn all volume sliders up. Play a sound (e.g. with automated animations). The sound is loud.
2. Turn the interface volume down. Play a sound - it is quiet.
3. Turn the interface volume back up and the music volume down. Play a sound - it is quiet.

**Expected behavior**
Only one volume slider should control the sound.
Based on [this](https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/8c96d9bddac1e3fcf305bfd544fe41d10cb5ab6b/src/modules/sequencer-sound-manager.js#L71) it looks like Sequencer is explicitly scaling on the interface slider, then when it plays the sound it is not specifying the audio context and Foundry is defaulting it to the "music" context.

Based on the [change description](https://github.com/orgs/foundryvtt/projects/42/views/9?filterQuery=label%3Abreaking+status%3ADone+audio&pane=issue&itemId=41576199) in V12 I think sequencer should stop explicitly scaling the volume based on the interface slider and instead pass the interface audio context when calling the Foundry "play" API.

**Setup:**
 - Foundry Version: 12.331
 - System Version: Pathfinder 2E 6.2.2
 - Sequencer Version: 3.2.15
 - Browser & version: Google Chrome 

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - PF2E Animation Macros

**Comment by tyrielv** [comment]
#292 has a fix for this

**Comment by Haxxer** [comment]
Fixed in 3.2.16
