### ISSUE TITLE
[BUG] - SequencerAboveUILayer is erroring

### ISSUE THREAD

**Issue by Tookie03** [fantasycalendar/FoundryVTT-Sequencer#302]
Exactly what the title says, It's not playing the effect at all, downgrading back to 3.2.15 allows it to work again (not the preloading issue though.)

**To Reproduce**
Use .screenSpaceAboveUI()

**Expected behavior**
It's supposed to play the effect above the UI.

**Screenshots**
![image](https://github.com/user-attachments/assets/82cf728f-a690-41ff-ad9c-13297c110ec6)

**Setup:**
 - Foundry Version: [e.g. 12.331]
 - System Version: [DND5e 3.3.1]
 - Sequencer Version: [3.2.16]

**Active modules:**
 - Sequencer
 - socketlib

**Additional context**
Unrelated issue, when I preload things the progress bar doesn't go away
![image](https://github.com/user-attachments/assets/6f93fb01-36cd-49ca-b447-dfff3b615a03)

**Comment by Haxxer** [comment]
Fixed in 3.2.17
