### ISSUE TITLE
Compendium.getDocuments() is extremely slow, considering using Compendium.getIndex() instead

### ISSUE THREAD

**Issue by tradiuz** [fantasycalendar/FoundryVTT-Sequencer#305]
https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/7b9799aa4453c937048497d7a7a0d0643e57fe67/src/modules/sequencer.js#L165

`getDocuments()` pulls the contents of the documents which means loading a lot of unnecessary data vs leveraging the index when searching for the name.

**Comment by Haxxer** [comment]
This was fixed some time ago
