### ISSUE TITLE
[REQUEST] - _fps for _flipbook

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#307]
**Is your feature request related to a problem? Please describe.**
Currently the 24 FPS for flipbooks is hard-coded. The asset packs I am using are animated in 30/60 FPS. It would be great to have accurate depiction of those animations by being able to set the FPS yourself.

**Describe the solution you'd like**
A `_fps` or similar property to add alongside `_flipbook`.

**Comment by Codas** [comment]
This.. should some time maybe in the future be possible once #275 is merged. Just added support for this in 7f31adf

**Comment by Codas** [comment]
This should be resolved by #275

**Comment by Haxxer** [comment]
Added in 3.4.0
