### ISSUE TITLE
[BUG] - Flipbook doesn't seem to work Consistently

### ISSUE THREAD

**Issue by ChasarooniZ** [fantasycalendar/FoundryVTT-Sequencer#308]
**Describe the bug**
Flipbook animations don't seem to properly animate sometimes

**To Reproduce**
Seems to work:
- When you use the play effect and just click
![GIF 9-11-2024 12-08-16 PM](https://github.com/user-attachments/assets/94fbfed7-cc5c-4528-affe-2fec5373b262)
Doesn't Seem to work
- When you drag the effect to scale it 
- When you view it in the animation Database
![image](https://github.com/user-attachments/assets/cbb09624-62d7-4a67-ab21-ac294f50a520)

**Expected behavior**
This to show as an animated video

**Setup:**
 - Foundry Version: 12.331
 - System Version: PF2e 6.3.1
 - Sequencer Version: 3.2.17
 - Browser & version Chrome 128.0.6613.121

**Comment by ChasarooniZ** [comment]
Follow up, the issue appears to be with at least the `stretchTo()` option, which causes it to not animate

![stretch to](https://github.com/user-attachments/assets/243b6b7a-4f00-4081-8573-ae9daaddb92d)

**Comment by Codas** [comment]
#275 addresses this issue and some others with flipbooks like the inconsistent frame timing.

**Comment by Codas** [comment]
This should also be resolved now in 1.4.0
