### ISSUE TITLE
[BUG] - .name doesn't link random rotation and mirroring of two effects

### ISSUE THREAD

**Issue by ctbritt** [fantasycalendar/FoundryVTT-Sequencer#309]
**Describe the bug**
When trying to link a second effect to the first effect, which has been randomly rotated and mirrored using `.name()`, the second effect doesn't not rotate or mirror. 

**To Reproduce**
1. Create sequence like so: 
2. 
```
  .effect()
  .name("Cracks")
  .file("jb2a.ground_cracks.01.dark_red")
  .size(defileSize)
  .rotate(randomRotaion)
  .randomizeMirrorX(randomMirrorX)
  .randomizeMirrorY(randomMirrorY)
  .delay(3000)
  .fadeIn(1000)
  .fadeOut(5000)
  .belowTokens()
  .atLocation(token)
  .opacity(0.75)
  .duration(10000)

  .effect()
  .file("jb2a.impact.ground_crack.still_frame.01")
  .size(defileSize)
  .delay(7500)
  .fadeIn(1000)
  .belowTokens()
  .atLocation("Cracks")
  .persist()
```
4. Run the sequence. 
5. The second effect will not reflect "Cracks" rotation or mirroring.

**Expected behavior**
The second effect should match the rotation and mirroring of the first effect -- "Cracks", in this case.

**Setup:**
 - Foundry Version: 12.331
 - System Version: DnD5e 3.3.1
 - Sequencer Version: 3.2.17
 - Browser & version Chromium Engine Version 128.0.6613.138

**Active modules:**
 - Sequencer
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 3.3.4
