### ISSUE TITLE
[BUG] - Persist only remembers the last sequence

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-Sequencer#310]
I've got this macro for making ioun stones attach to a token. If I have multiple of the tokens for that actor on the map, then the sequence plays for both (because of persisting to the prototype (circled in image)). But if I pull another copy of that actor in from the world's actor tab, it's only getting the last-most persisted effect (selected token with arrow). Likewise if I refresh the page, only the last-most effect loads.

```js
const path = "jb2a.ioun_stones.01.blue.strength";
// first time path was 'jb2a.ioun_stones.01.pink.protection'
const name = foundry.utils.randomID()
new Sequence()
  .effect(path)
  .attachTo(token)
  .fadeIn(500)
  .fadeOut(500)
  .scale(0.10)
  .spriteOffset({ y: token.height / 2 })
  .zeroSpriteRotation(true)
  .loopProperty("spriteContainer", "rotation", { from: 0, to: 360, duration: 6000 })
  .persist(true, { persistTokenPrototype: true })
  .name(name)
  .play();
```

![image](https://github.com/user-attachments/assets/043c7c9a-02f3-4b2e-9619-4c49df0f8228)

System is pf1 10.7 (though shouldn't be important as nothing here is specific to pf1).
Sequencer version is 3.2.11

**Comment by Haxxer** [comment]
Fixed in 3.3.3
