### ISSUE TITLE
[REQUEST] - Add-a-named-location method

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#316]
**Is your feature request related to a problem? Please describe.**
When working with modules, sometimes you need to delegate stuff such as location of an effect outside of Sequencer. The problem is that in order to add that location to a sequence, you need to replace every instance of that location in each section from `.atLocation("test")` to `.atLocation(yourData)`.

**Describe the solution you'd like**
It would be great to have a CoreMethod that adds a generic `name`d location to the Sequence without it being attached to other existing sections.

Example
```js
const location = await crosshairs();

new Sequence()
  .addLocation("loc", location)
  .effect()
    .atLocation("loc")
    .file("jb2a.antilife_shell.blue_no_circle")
  .play()
```

**Comment by Haxxer** [comment]
Added in 3.3.1
