### ISSUE TITLE
[BUG] - scaleToObject does not play well with JSON crosshairs

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#320]
**Describe the bug**
When turning a crosshair to JSON (most commonly for sending thru a socket), some data seems to be lost that is integral to making `.effect()`s scale properly. When used in conjunction with `scaleToObject`, the JSON version of the Crosshair Template, the effect becomes flattened.

**To Reproduce**
```js
const crosshair = await Sequencer.Crosshair.show()

new Sequence()
  //.addNamedLocation("test", crosshair)
   .addNamedLocation("test", JSON.parse(JSON.stringify(crosshair))) // Same with .toJSON()
  .effect()
    .atLocation("test")
    .scaleToObject()
    .file("jb2a.portals.horizontal.ring.blue")
  .play()
  ```
  
**Expected behavior**
Same behavior as with a normal crosshair that has not been turned into JSON.

https://github.com/user-attachments/assets/5b97168a-2872-42ac-9f33-f3c4ad199bcd

**Comment by Haxxer** [comment]
Use `crosshair.document.getOrientation()` to get a json data compliant with Sequencer positional data
