### ISSUE TITLE
[REQUEST] - Provide option for non-central scaling.

### ISSUE THREAD

**Issue by welovekah** [fantasycalendar/FoundryVTT-Sequencer#323]
Currently effect elements always scale from the center, even if using screenSpaceAnchor. 

This makes it difficult to scale an element towards one direction. IE: A progress bar.

**Comment by Haxxer** [comment]
Have you changed the sprite anchor with `.anchor()`?

**Comment by welovekah** [comment]
Solved. Anchor works, when i would have assumed screenspaceanchor would have
