### ISSUE TITLE
[BUG] - Crosshair persist does not provide the spawned template to rest of Sequence

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#325]
**Describe the bug**
When using crosshairs, you'd want to create a template using that crosshairs location and then reference that template in further effects. Problem is, the `name` of the crosshair does not return the created template for effects to `attachTo`, but what I assume to be the plain X,Y coordinates.

**To Reproduce**
```js
new Sequence()
  .crosshair("test")
    .distance(2.5)
    .location(_token, { limitMaxRange: 15 })
    .persist()
  .effect()
    .attachTo("test")
    .scaleToObject()
    .persist()
    .file("jb2a.portals.horizontal.ring")
  .play()
```

Then move the template. You will also see a warning that `attachTo` couldnt attach and defaulted to `atLocation`.

[chrome_aXJH95PuR1.webm](https://github.com/user-attachments/assets/9cd079d8-95e3-4e6f-a2e4-7d020766bc0a)

**Comment by Haxxer** [comment]
Fixed in 3.3.4
