### ISSUE TITLE
I really need help...Chain Lightning

### ISSUE THREAD

**Issue by Kirin92** [fantasycalendar/FoundryVTT-Sequencer#33]
Alright.... I just can't figure out how Chain lightning works. There are three different macros of chain lightning.
What should I do? 
the animation only targets one target, not the others. Should my players do the saving throws first or what? I am really confused .
Pls help....

**Comment by Haxxer** [comment]
Why did you close this? Did you solve it? :)

**Comment by Kirin92** [comment]
Well... not really. I'm still confused.
I thought it's a dumb problem (because my problem is confusion xD).
The thing is... If the player casts the spell and then click on damage button, a new window pops up to tell me which player should get the lightning animation within 30 ft.
Why I am confused? Because there are two more macros in the compendium. 
"Sequencer-VFX-Chain-Lightning-Simple"
and
"Sequencer-VFX-Chain-Lightning-Complex"

I dunno what they are and they seem not to function? What are those?

**Comment by Haxxer** [comment]
If you read the first couple of lines on those macros, you'll see that they're simple examples of macros that can be made with the Sequencer. As for why your player doesn't get the popup - did you set him to be the owner of the macro? He can't run it if he doesn't own it, after all.

**Comment by Kirin92** [comment]
Well. I can't really understand the code but I'll try. thank you~

**Comment by Haxxer** [comment]
It has comments at the top:
```
// Requires the Jack Kerouac's Animated Spell Effects: Cartoon module
// Select a token, then target a set of tokens, and run this macro
```

**Comment by Kirin92** [comment]
... damn... thanks... I didn't saw that.

**Comment by V13Axel** [comment]
Probably don't 🪚 your code, it'll only cause more errors (or less, if it kills the hardware)

:wink:
