### ISSUE TITLE
[REQUEST] - Option to have Animate property scale off screen size

### ISSUE THREAD

**Issue by ChasarooniZ** [fantasycalendar/FoundryVTT-Sequencer#330]
Similar to the option to set as grid units options to have animate property (for like x and y position) scale off of scren size if the effect is set to `screenSpace()`.

This would allow for fancier/more accurate screenSpace animations

**Comment by Haxxer** [comment]
Can you elaborate on this, and give me an example theoretical code?

**Comment by ChasarooniZ** [comment]
Hi, the thought process is something like:

`animateProperty("sprite", "position.x", { from: 0, to: 0.5, duration: 500, screen space:true})`

The ideal being not necessarily that exactly, but coordinates that scale off screen space to allow accurate placement of elements if they're in the screen space area

**Comment by ChasarooniZ** [comment]
Fully understandable if this is out of scope though

**Comment by Haxxer** [comment]
Added in 3.3.7

**Comment by ChasarooniZ** [comment]
LETS GOOOOO!!
