### ISSUE TITLE
[BUG] Error: "Filepicker.parseS3URL is undefined" (in Foundry v12, use `foundry.utils.parseS3URL`)

### ISSUE THREAD

**Issue by morepurplemorebetter** [fantasycalendar/FoundryVTT-Sequencer#332]
## Describe the bug
The module uses `Filepicker.parseS3URL` which doesn't exist in FoundryVTT v12 anymore.
Instead, `foundry.utils.parseS3URL` should be used.

## To Reproduce
Try using Sequencer to play a sound with a wildcard from an s3 bucket.

## Setup:
 - Foundry: v12.331
 - System:  DnD5e v3.3.1
 - Sequencer: v3.3.4

## Additional context
I doubt I need to provide more details, but please ask if you need more info.

**Comment by Haxxer** [comment]
Fixed in 3.3.5
