### ISSUE TITLE
[BUG] Deprecation warning for PixiJS in FoundryVTT v12

### ISSUE THREAD

**Issue by morepurplemorebetter** [fantasycalendar/FoundryVTT-Sequencer#333]
## Describe the bug
I'm getting several warning messages in my console from this module on load:
```
PixiJS Deprecation Warning: filters.AlphaFilter has moved to AlphaFilter
Deprecated since v7.1.0
render@https://foundry.flapkan.com/modules/sequencer/module.js:21620:10
[...]
```

The same goes for these filters:
```
PixiJS Deprecation Warning: filters.ColorMatrixFilter has moved to ColorMatrixFilter
PixiJS Deprecation Warning: filters.BlurFilter has moved to BlurFilter
PixiJS Deprecation Warning: filters.NoiseFilter has moved to NoiseFilter
PixiJS Deprecation Warning: filters.DisplacementFilter has moved to DisplacementFilter
```

A simple search and replace for `PIXI\.filters\.(AlphaFilter|ColorMatrixFilter|BlurFilter|NoiseFilter|DisplacementFilter)`  to `PIXI.$1` fixed these warnings for me.

## Additional context
I doubt I need to provide more details, but please ask if you need more info.

EDIT: added more deprecation warnings for other PIXI.filters

**Comment by Haxxer** [comment]
Fixed in 3.3.5
