### ISSUE TITLE
[BUG] - version 3.3.5 creates massive failure of token magic, animations and more.

### ISSUE THREAD

**Issue by TheXeno30** [fantasycalendar/FoundryVTT-Sequencer#335]
**Describe the bug**
When installing version 3.3.5 AA, tokenmagic and CPR breaks

**To Reproduce**
install 3.3.5

**Expected behavior**
nothing

**Screenshots**
N/A

**Setup:**
 - Foundry Version: 12.331
 - System Version: D&D5E 3.3.1
 - Sequencer Version: 3.3.5
 - Browser & version Chrome

**Active modules:**
lots

**Additional context**
installing 3.3.4 makes everything ok.

**Comment by Haxxer** [comment]
It is token magic, try disabling it.

**Comment by sonofkyusss** [comment]
Hi,
It's only when disabling Sequencer that everything returns to "normal".
Disabling TMFX does not resolve the issue. Disabling Sequencer does (or revert back to 3.3.4).
TMFX has not been updqated since Sep 09 2024.

**Comment by Haxxer** [comment]
Hopefully fixed in 3.3.6

**Comment by sonofkyusss** [comment]
> Hopefully fixed in 3.3.6

Yes, TMFX an Sequencer are working together again.

**Comment by TheXeno30** [comment]
It work now... Thanks for the quick response. ☜(ﾟヮﾟ☜)
