### ISSUE TITLE
[BUG] - Above Screen Space UI layer not working

### ISSUE THREAD

**Issue by Drakerus1** [fantasycalendar/FoundryVTT-Sequencer#337]
**Describe the bug**
When using .screenSpaceAboveUI() the effect does not render at all, leading me to believe that the layer is broken.

**To Reproduce**
1. Run the macro I attached to see that the effect renders correctly when not using the aforementioned layer.. You'll need a generic black square image for Dark_Screen.
3. Remove the "//" from the .screenSpaceAboveUI() line and run the macro again to see that the effect no longer renders.

**Expected behavior**
The desired result is a full screen dimming.

**Screenshots**
N/A

**Setup:**
 - Foundry Version: 12.331
 - System Version: Pathfinder 2e 6.4.1
 - Sequencer Version: 3.3.6
 - Browser & version: Google Chrome 130.0.6723.59

**Active modules:**
 - Sequencer
 - socketlib

[fvtt-Macro-debug-convergence-6XwcKHkSg5JYXHri.json](https://github.com/user-attachments/files/17402654/fvtt-Macro-debug-convergence-6XwcKHkSg5JYXHri.json)

**Comment by Haxxer** [comment]
Fixed in #336 338
