### ISSUE TITLE
[BUG] - Animate Property bug "InOptions.screenSpace"

### ISSUE THREAD

**Issue by Yashael** [fantasycalendar/FoundryVTT-Sequencer#339]
**Describe the bug**
An error occurs when a macro, that works fine previously, is activated

**To Reproduce**
1. Launch the macro :
-------------------------------------------------------------------------------------------------------
//Last Updated: 8/27/2023
//Author: EskieMoh#2969

//Set potion color: blue, green, purple, yellow, red
let potioncolor = "green";

if (potioncolor == "blue"){
     color = "blue"
     tintColor = '0x2cf2ee'
     hue1 = '10'
     hue2 = '-200'
     hue3 = '0'
     saturate = '1'
}  
else if (potioncolor == "green"){
     color = "green"
     tintColor = '0xbbff00'
     hue1 = '-105'
     hue2 = '35'
     hue3 = '0'
     saturate = '1'
}
else if (potioncolor == "purple"){
     color = "purple"
     tintColor = '0xf50f95'
     hue1 = '135'
     hue2 = '-95'
     hue3 = '0'
     saturate = '1'
}
else if (potioncolor == "yellow"){
     color = "yellow"
     tintColor = '0xffbb00'
     hue1 = '230'
     hue2 = '10'
     hue3 = '0'
     saturate = '1'
}
else if (potioncolor == "red"){
     color = "green"
     tintColor = '0xec0927'
     hue1 = '180'
     hue2 = '-30'
     hue3 = '275'
     saturate = '1'
}

await new Sequence()

.effect()
.file("animated-spell-effects-cartoon.water.05")
.atLocation(token, {offset: {x:0.2, y:-0.5}, gridUnits:true})
.scaleToObject(0.75)
.opacity(0.9)
.rotate(90)
.filter("ColorMatrix", { saturate: saturate, hue: hue1})
.zIndex(1)

.wait(200)

.effect()
.file(`jb2a.sacred_flame.source.${color}`)
.attachTo(token, {offset: {y:0.15}, gridUnits:true, followRotation: false})
.startTime(3400)
.scaleToObject(1.8)
.fadeOut(500)
.animateProperty("sprite", "position.y", { from: 0, to: -0.4, duration: 1000, gridUnits:true})
.filter("ColorMatrix", { hue: hue3})
.zIndex(1)

.effect()
.from(token)
.scaleToObject(token.document.texture.scaleX)
.opacity(0.2)
.duration(750)
.fadeIn(100)
.fadeOut(600)
.filter("Glow", { color: tintColor , distance: 10, quality: 0.1})
.tint(tintColor)

.effect()
.file(`jb2a.particles.outward.orange.01.03`)
.attachTo(token, {offset: {y:0.1}, gridUnits:true, followRotation: false})
.scale(0.2)
.duration(1000)
.fadeOut(800)
.scaleIn(0, 1000, {ease: "easeOutCubic"})
.animateProperty("sprite", "width", { from: 0, to: 0.25, duration: 500, gridUnits:true, ease:"easeOutBack"})
.animateProperty("sprite", "height", { from: 0, to: 1.0, duration: 1000, gridUnits:true, ease:"easeOutBack"})
.animateProperty("sprite", "position.y", { from: 0, to: -0.6, duration: 1000, gridUnits:true})
.filter("ColorMatrix", { saturate: 1, hue: hue2})
.zIndex(0.3)

.wait(1000)

.play()
"
--------------------------------------------------------------------------------------------------------------------------
**Expected behavior**
Error thrown by console : "Uncaught (in promise) Error: undefined. Sequencer | Effect | animateProperty - inOptions.screenSpace must be of type boolean
[Detected 2 packages: sequencer(3.3.7), advanced-macros(2.2.1)]"

**Screenshots**
![Capture d'écran 2024-10-18 121044](https://github.com/user-attachments/assets/e07e4a1c-3e22-4b1a-8a95-fa8ebd6f863c)

**Setup:**
 - Foundry Version: 12.331
 - System Version: DnD 3.3.1
 - Sequencer Version: 3.3.7

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A

**Comment by Haxxer** [comment]
Fixed in 3.3.8

**Comment by Yashael** [comment]
It works! Thanks a lot!
