### ISSUE TITLE
[BUG] - Sequencer Canvas Issues

### ISSUE THREAD

**Issue by Dusk-Lynx** [fantasycalendar/FoundryVTT-Sequencer#347]
**Describe the bug**
After some time playing the map suddenly goes black seemingly randomly. our GM saw an error that seemed to say something couldn't get the resolution, however they reloaded before I could ask them to send over the error log.

**To Reproduce**
1. Enable Sequencer
2. Load a map
3. play for some amount of time
4. Map and tokens disappear

**Expected behavior**
Map does not disappear 

**Setup:**
 - Foundry Version: 12 Stable 331
 - System Version: Pf2e 6.5.0
 - Sequencer Version: [e.g. 1.0.0]
 - Browser & version: Chrome 124.0.6367.210

**Additional context**
it seemed to be an error with something timing out when loading/reloading the map, we are using Forge so that may explain why things would refresh/load randomly if thats not normal for foundry. however it ultimately seems like a canvas issue. it didn't effect other UI elements

**Comment by silversiren1101** [comment]
Having this issue too. Had to disable all animations, dice so nice, etc, to be able to run the game. Most common issue in the console is in image.
![image](https://github.com/user-attachments/assets/5615a2eb-9180-4144-b237-d518b9c7b288)

**Comment by tia-lynn** [comment]
I'm getting some similar errors and behavior.

**Setup:**
Foundry Version: 12 Stable 331
System Version: PF2e 6.5.0
Sequencer Version: 3.4.1
Browser & version: Microsoft Edge Version 130.0.2849.46 (Official build) (64-bit)

![image](https://github.com/user-attachments/assets/394ce431-10fd-4c83-94ac-9d940dabfaae)

**Comment by Haxxer** [comment]
Fixed in 3.4.2
