### ISSUE TITLE
[BUG] - screenSpace isn't playing effect [Sequencer 3.4.2]

### ISSUE THREAD

**Issue by Tookie03** [fantasycalendar/FoundryVTT-Sequencer#354]
**Describing the bug**
When using screenSpace it doesn't render/play the effect but will still play the macro with no issues. It works fine with version 3.3.8 but any version after it doesn't render/play. (I'm unsure if I need to change anything with my macros due to the 3.4.0 update with webm files being handled as a spritesheet) 

**To Reproduce**
```
await Sequencer.Preloader.preloadForClients("(webm file)", false)
new Sequence()

.effect()
.file(webm file)
.screenSpace()
.screenSpaceScale({
    x: 1.0,         // Scale on the effect's X scale
    y: 1.0,         // Scale on the effect's Y scale
    fitX: true,    // Causes the effect to set its width to fit the width of the screen
    fitY: true,    // Causes the effect to set its height to fit the height of the screen
    ratioX: false,  // If Y is scaled, setting this to true will preserve the width/height ratio
    ratioY: false   // If X is scaled, setting this to true will preserve the height/width ratio
})
.screenSpaceAboveUI()
.fadeOut(250)

.play()
```

**Expected behavior**
It should play and render the effect above the screenspace. 

**Screenshots**
![image](https://github.com/user-attachments/assets/5b2cb22e-91ac-409f-bd79-00581fcdb758)

**Setup:**
 - Foundry Version: [12.331]
 - System Version: [DND5e 4.0.4]
 - Sequencer Version: [e.g. 3.4.2]
 - Browser & version [Inside of foundry]

**Active modules:**
 - Sequencer
 - socketlib

**Comment by Haxxer** [comment]
Fixed in 3.4.3
