### ISSUE TITLE
Persistent animations that won't stay deleted.

### ISSUE THREAD

**Issue by Nedrapter** [fantasycalendar/FoundryVTT-Sequencer#356]
**Describe the bug**
Sequence together with Automated Animations module makes some persistent effects. The effect is deleted yet it appears again when the token is placed again on the map or when the map switches.

**To Reproduce**
Have these 2 modules cast Detect Thoughts from dnd5e, delete the animation the drag the token again in the map.

**Expected behavior**
Effect to not return after getting deleted.

**Screenshots**

**Setup:**
 - Foundry Version: 13.331
 - System Version: 4.0.4
 - Sequencer Version: 3.4.3
 - Browser & version Opera, Firefox, Chrome

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations
 - libwrapper

**Additional context**
I'm not sure if there's a proper way to delete an effect. It feels like the animation is stored on the actor and every time I drag the token into the scene, or switch scenes it pulls the data again. Just an assumption though I have no clue how it works.

**Comment by Haxxer** [comment]
Can you please export your actor and upload it to the ticket? It would help us debug.

**Comment by Haxxer** [comment]
Should be fixed in 3.4.4
