### ISSUE TITLE
[REQUEST] - ScreenSpaceScale affecting shapes

### ISSUE THREAD

**Issue by ChasarooniZ** [fantasycalendar/FoundryVTT-Sequencer#358]
As said screenSpaceScale affecting shapes, currently atm it just makes them unseeable when they're on the `aboveUI` layer

**Comment by ChasarooniZ** [comment]
If not feasable at least some method to set Shape's size based on the user its playing on screen size

**Comment by Haxxer** [comment]
Fixed in 3.4.5
