### ISSUE TITLE
Possible Bug with attachTo()

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#36]
Issue was first reported on the A-A list at https://github.com/otigon/automated-jb2a-animations/issues/276 .

When using .attachTo() and setting a token as the object, if the Token has any scaling effect applied ( Scale(ratio) }, the effect does not properly center.
To replicate, you can use:

let tactor = canvas.tokens.controlled[0];

new Sequence()
.effect()
.file("modules/jb2a_patreon/Library/2nd_Level/Darkness/Darkness_01_Black_600x600.webm")
.attachTo(tactor)
.scale(.5)
.play()

For the Token, if you edit it on the Image tab, and change the Scale(ratio) higher or lower than 1, the effect starts to be placed off center. I can't see in the token info where this would effect the placement, but I'm assuming it has something to do with Pixi, but that's like reading japanese for me lol.

**Comment by Haxxer** [comment]
Fixed in a recent update
