### ISSUE TITLE
Catching an error that I was told is a Sequencer issue

### ISSUE THREAD

**Issue by Dominemesis** [fantasycalendar/FoundryVTT-Sequencer#369]
Catching an error I reported to the creator of PF2 RPG Numbers mod, which they said was a Sequencer issue:

Console shows the following errors;

![PF2rpgnumbers console errors](https://github.com/user-attachments/assets/27391a11-1ad5-4ad2-b910-c0de616fc9d1)

**Comment by Haxxer** [comment]
Fixed in 3.4.6
