### ISSUE TITLE
Sequencer manager empty 

### ISSUE THREAD

**Issue by chrisella** [fantasycalendar/FoundryVTT-Sequencer#41]
Having cast Spirit guardians which through the Automated Animations addon applies a sequencer effect, the effect appears fine (as seen in the screenshot) however nothing ever appears in my sequencer manager tab. 

![image](https://user-images.githubusercontent.com/1069324/142015141-66f26ecf-36e7-4c0d-8222-1ba0d2d97ed6.png)

In-fact neither of the buttons (How-To or Manager) do anything when clicked.
I have to stop the sequence/animation via the console currently which is not ideal at-all.

![image](https://user-images.githubusercontent.com/1069324/142017220-ddeb7ee6-63cb-467f-a51d-ec118d7b127d.png)

**Comment by Haxxer** [comment]
Are you the GM in this instance?

**Comment by chrisella** [comment]
Hey, yes I am

**Comment by Haxxer** [comment]
Are on the A-A discord server? Easier to discuss there.

**Comment by chrisella** [comment]
I'm not but happy to join if you can send a link

**Comment by Haxxer** [comment]
Issues on Github is more for tracking and reporting bug purposes, not so much remote assistance

**Comment by Haxxer** [comment]
https://discord.gg/E4EvhQGr

**Comment by Haxxer** [comment]
Fixed in latest versions of ASE and Sequencer
