### ISSUE TITLE
Translate French

### ISSUE THREAD

**Issue by Elfenduil** [fantasycalendar/FoundryVTT-Sequencer#43]
Hi,

Can you add the translate French in you module, see the file in Att

Thank you
[Traduction Sequencer FR.txt](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/7561921/Traduction.Sequencer.FR.txt)

**Comment by Haxxer** [comment]
Added in 1.2.11, thanks for the contribution!

**Comment by Haxxer** [comment]
Hi there! I have recently updated some localization, would you be up for updating the French localization? :)
