### ISSUE TITLE
[Request] Let us provide multiple objects as sources or targets

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-Sequencer#45]
Ok new suggestion. If I've got an effect chain (that's what I've been calling `.effect().method1().method2().etc()` in my head), and a method in that chain takes an object/token as a parameter, what if we could give it an array and it would apply that effect chain to every object in that method?

So something like `new Sequence().effect().file(boom).atLocation([token1, token2, token3]).play()` and it would play the boom on each of those tokens.

Or something like `new Sequence().effect().file(arrowTrap).atLocation([trapTile1, trapTile2]).reachTowards([token1, token2]).play()` and it would cause both trap tiles to shoot at both tokens (for a total of 4 animations).

I realize it could quickly get out of hand if someone was irresponsible with how many tokens they passed into multiple places.

**Comment by Haxxer** [comment]
I have also evaluated this, and it is much better to use for loops for this, as the backend refactor would be immense! Thanks for the suggestion, though!
