### ISSUE TITLE
Error related to Dice so Nice animations

### ISSUE THREAD

**Issue by gravagehulk** [fantasycalendar/FoundryVTT-Sequencer#47]
I keep getting this error. I used to have animations set up for when I rolled a natural 1 or natural 20 in Dice so Nice. I reset to defaults and that doesn't seem to help. This error ONLY comes up when I roll a 1 or 20. There are currently no animations or sounds set in Dice so Nice.

![image](https://user-images.githubusercontent.com/69117052/144687585-018b403e-3ab3-4832-b6a9-4aeb17d911d2.png)

**Comment by Haxxer** [comment]
I am not sure what Sequencer can do if you're running macros that have malformed contents.

The error is simply pointing out that the Sequence you are creating has an effect with no file to play.

This is intended behaviour, and I recommend asking on the main Foundry discord how to reset your settings fully.

**Comment by gravagehulk** [comment]
I don't have any macros related to Dice so Nice. This ONLY comes up on a 1 or 20 on the dice. It doesn't come up any other time. No macros run when I roll a 1 or 20. It seems like it's related to whatever animation I had set for Dice so Nice, but those have been cleared.

**Comment by Haxxer** [comment]
Sequencer does not natively integrate into DSN, nor does it store anything on any data relating to any other modules.

**Comment by gravagehulk** [comment]
okay, thanks. I follow up with DsN

**Comment by Haxxer** [comment]
How does DSN set an animation to play?

**Comment by gravagehulk** [comment]
It's an option through the settings. You pick a dice, pick a side, then you set an animation or sound. You can set as many as you want to one side of a die or multiple sides. I used to have both a sound and an animation set to play on a 20 and a 1. Suddenly, this error started popping up, so I cleared the settings on DsN and it's still doing it.

**Comment by Haxxer** [comment]
Sounds like something that DSN has configured wrong, I'll talk to them tooand see what's up. Thanks!

**Comment by gravagehulk** [comment]
I appreciate your help. This is a new one for me. I have been using both modules for a while and just started seeing this.

**Comment by Haxxer** [comment]
As I thought, DSN doesn't use Sequencer, so it must be another module that relies on the natural 1 and 20s. I recommend you use Find The Culprit to find the module causing the error.

**Comment by gravagehulk** [comment]
Thanks. I'll check it out.
