### ISSUE TITLE
Add options param to `attachTo` for an align option

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-Sequencer#48]
It would be useful to be able to do something like this `.attachTo(token, { align: 'top-right' })` (with options for each of the 8 directions (top/left/bottom/right and the combination of each two adjacent)).

I see this with working in tandem with `offset` so `attachTo(token, { align: 'top-right' }).offset({x: 50})` would align it to the top right and then push it 50 to the right.

**Comment by ctbritt** [comment]
yup. Was using sequencer 2.0 beta 2, with AA and when attaching an effect to a template, it would put the center of the effect on the top left corner of the template, like so:
<img width="690" alt="Screen Shot 2021-12-31 at 2 52 56 PM" src="https://user-images.githubusercontent.com/4516034/147840358-9a94d9e9-c4ba-4849-8dd3-c57477c099ec.png">

**Comment by ctbritt** [comment]
also created strange template effects like this:

https://user-images.githubusercontent.com/4516034/147840374-7ee6121b-1fe4-4535-8fbf-1d4c401d1595.mov

**Comment by Haxxer** [comment]
@ctbritt Please log this with A-A rather than on an unrelated ticket on Sequencer.

**Comment by Haxxer** [comment]
The beta is not ready to be used, and should not log tickets for it

**Comment by Haxxer** [comment]
Added in 2.0.0
