### ISSUE TITLE
Add .hide() method to animations for toggling hidden state of tokens.

### ISSUE THREAD

**Issue by monodemono** [fantasycalendar/FoundryVTT-Sequencer#49]
**Is your feature request related to a problem? Please describe.**
I have a room with a bunch of skeleton tiles, and after the players examine the painting in the room I'm going to trigger a macro that I wrote that fades the tiles out, and fades the skeleton's tokens in, starting the fight.
The problem is that while the skeleton tokens have their opacity turned down, the players will still be able to see the red square around the tokens when putting their cursor in the room.
I can separately toggle their hidden state within the macro before fading them in, but I think a .hide() method would really simplify this.

**Describe the solution you'd like**
Add a .hide() method to animations to toggle the hidden status of tokens (and probably tiles too, though those don't exactly suffer from the same issue as above).

**Describe alternatives you've considered**
Writing a line into my macro to unhide the token before fading it in.

**Additional context**
Wasp told me they could add a .hide() method on the #macro-polo channel of the Foundry VTT discord server. I'm simply filing this issue request for tracking and posterity.
Thanks for this great module and support :)

**Comment by Haxxer** [comment]
Added in 2.0.0
