### ISSUE TITLE
Tool buttons visible to users below permission setting

### ISSUE THREAD

**Issue by ianm32** [fantasycalendar/FoundryVTT-Sequencer#51]
**Describe the bug**
When the settings in Sequencer are set to "Assistant GM," particularly the toolbar options for the database and manager, the buttons are visible to a user with Trusted Player permission on my server. Users with Player status cannot see these tools.

**Expected behavior**
Would expect the tools to not be present in the user's toolbar.

**Screenshots**
See attached screenshots of my Sequencer settings as GM, and the toolbar view of my Trusted Player.
![Capture2](https://user-images.githubusercontent.com/27756065/146443029-eabe07d5-0db5-4389-b303-81e466278749.JPG)
![Capture](https://user-images.githubusercontent.com/27756065/146443037-7dd16053-8023-4d5e-b65f-d4e68b30071a.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 96.0.1054.53

**Comment by Haxxer** [comment]
Fixed this bug, and added setting in 2.0.0 to disable these buttons locally
