### ISSUE TITLE
Sequencer Breaks /stream view, which prevents other modules from working

### ISSUE THREAD

**Issue by PimpWilly** [fantasycalendar/FoundryVTT-Sequencer#52]
**Describe the bug**
When a user is using foundry's /stream page, versus the game page, while using PF2e then Sequencer throws errors in the console log. This stops other modules (like dice so nice in combination from Stream Utils) from rendering the dice properly. 

Foundry throws this error:
Uncaught TypeError: Cannot read properties of undefined (reading 'activeTool')
[Detected 1 package: sequencer]
    at Game.get activeTool [as activeTool] (foundry.js:4892)
    at SequencerEffectPlayer.get playActive [as playActive] (sequencer-effect-player.js:26)
    at BelowTokensEffectsLayer.get playActive [as playActive] (effects-layer.js:73)
    at BelowTokensEffectsLayer.drawPoint (effects-layer.js:122)
    at BelowTokensEffectsLayer.render (effects-layer.js:83)
    at e.render (display.min.js:8)
    at r.render (core.min.js:8)
    at t.render (app.min.js:8)
    at t.emit (ticker.min.js:8)
    at e.update (ticker.min.js:8)
    at _tick (ticker.min.js:8)

**To Reproduce**
1. Launch your Foundry world, using PF2E, Dice so Nice, Stream Utils, Automated Animations and Sequencer all enabled.
2. Now, open a second window with the <host>/stream URL instead of the /game url, to access the stream screen
3. Once loaded, roll a d20 in the /game window. 
4. watch in the /stream window, as the error is throw in console when the dice starts rolling ,and freezes the roll from happening
5. Above error is printed in console log

**Expected behavior**
Sequencer should be able to recognize the "stream" view, and not throw errors when trying to access undefined variables in this view.

**Screenshots**
See https://i.imgur.com/0FevcWz.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110

**Additional context**
The "stream" view isn't heavily used, but some streamers rely on it to overlay information. It doens't render any of the game views, just specific things configured to be shown. Might need more null checks to make sure you're accessing variables set, or to ignore the "stream" view entirely by checking the "game.view" variable is the proper view.

**Comment by Haxxer** [comment]
I believe this was fixed in 2.0.0 or later
