### ISSUE TITLE
Possibility to hide the tools for the GM ?

### ISSUE THREAD

**Issue by Padhiver** [fantasycalendar/FoundryVTT-Sequencer#53]
**Is your feature request related to a problem? Please describe.**
Using a lot of modules, the selection of tools on the left start to get really long, I would like to know if it is possible to hide the Sequencer ones, even for the GM, when they are not needed ?

**Describe the solution you'd like**
Well, that in the settings we have the possibility to hide the tools for the GM, as we can do for the players.

**Describe alternatives you've considered**
I don't know. A checkbox to manage the appearance of tools globally ... ?

**Additional context**
I don't know what else to say, except to say thank you for the work done, and even if this request should not see the light of day ! :)

**Comment by Haxxer** [comment]
2.0.0 added such a setting
