### ISSUE TITLE
Sequencer Data Base Issue

### ISSUE THREAD

**Issue by Lawlesslisa** [fantasycalendar/FoundryVTT-Sequencer#54]
When I go to save my module setting, I get this message from FVTT.

<img width="547" alt="Sequencer" src="https://user-images.githubusercontent.com/94867746/149551730-4345ffa4-ee20-4f5d-b70e-957b8093f943.png">

I am using the latest Sequencer module, version 2.0.1 and this is in the PF2E system.  I believe it is preventing my Automated Animations Module from working.

**Comment by Haxxer** [comment]
This is a problem with Automated Animations, please post it on their repository.
