### ISSUE TITLE
'Preload' check box in Player

### ISSUE THREAD

**Issue by Melephisance** [fantasycalendar/FoundryVTT-Sequencer#55]
I am unsure what this option does.

Without the check box ticked one selects the desired animation, drags a line and it plays. With the check box ticked same behaviour doesn't play anything. Hence my question as it isn't immediately obvious what this check box does, and likewise why it seems to prevent animations playing when checked.

Thanks in advance :)

**Comment by Haxxer** [comment]
Can you confirm which version you are on?

**Comment by Melephisance** [comment]
Of course:

Foundry vtt v 9.242
Sequencer 2.0.5

**Comment by Haxxer** [comment]
@Melephisance I believe I have fixed this in the latest version - could you check again?

**Comment by Melephisance** [comment]
Yes this works fine now thank you :)
