### ISSUE TITLE
Macro sounds broken

### ISSUE THREAD

**Issue by Spiderfoxtail** [fantasycalendar/FoundryVTT-Sequencer#57]
It seems that after the latest update all of the macros I created with audio no longer work.
This is the coding I am using, can you tell if I am doing something wrong or if the update truly broke the module? I am only using Sequencer and Socketlib

let target = Array.from(game.user.targets)[0];

let sequence = new Sequence()

    .effect()
        .file("Music/videos/shotgun_blast_01.webm")

        .atLocation(token)
        .reachTowards(target)       
    .play();

new Sequence()
    .effect()
        .file("Music/videos/gunMuzzleFlash.webm")
        .atLocation(token)
.rotateTowards(target)
.scale(0.2)
.endTimePerc(0.1)  
    .play();

new Sequence()
    .sound()
        .file("Music/sounds/shotgun.ogg")
        .fadeInAudio(100)
        .fadeOutAudio(100)
    .play()

**Comment by Haxxer** [comment]
Do you have any errors in the console? Which browser are you on? Which version of Sequencer are you on?

All of these questions are in the bug issue template on Github, so please use that in the future.

**Comment by Spiderfoxtail** [comment]
Foundry VTT Version 9 - Build 242
Game system Mausritter Version 0.1.2c
Sequencer Version 2.0.9
Socketlib Version 1.0.10

No errors in the console. Everything works, animations, direction, and such but no sound. The effect sounds work as a playlist.

**Comment by Haxxer** [comment]
Could you check if your interface sound level is turned down? Could you also upload your sounds here so that I can test it myself?

**Comment by Spiderfoxtail** [comment]
Couldn't get the audio file to upload here so I put the sound in dropbox.
https://www.dropbox.com/s/8veetik04iy5b3k/shotgun.ogg?dl=0
![InterfaceVolume01](https://user-images.githubusercontent.com/46890287/150622397-fe686cc7-a067-4518-8635-e345d206e4b3.png)
That's the interface level at max. I could not find any other place to change the volume. If there is, let me know.

**Comment by Haxxer** [comment]
What does your Sequencer module settings look like? Is Sound Enabled?

![image](https://user-images.githubusercontent.com/12858387/150638832-83d53b6e-fd15-4a86-89bf-fa53ba49399d.png)

**Comment by Spiderfoxtail** [comment]
![SequencerConfigure](https://user-images.githubusercontent.com/46890287/150645314-8fc9b4a5-38f4-4fa8-8a56-c8a63a223178.png)
This is how I have it set up currently. Sounds are enabled.
Updated this morning to Sequencer V2.0.10

**Comment by Haxxer** [comment]
I have located the issue in the fading of the audio - if you remove `fadeInAudio` and `fadeOutAudio`, it will work. I'll release a fix for this in the next update.

**Comment by Spiderfoxtail** [comment]
Whoa, that worked!
Thank you very much. This module is awesome and essential in our game!
