### ISSUE TITLE
Core V9.9.238 Throwing Error: 'isPrivate is not defined' with AutoAnimations module lodaded.

### ISSUE THREAD

**Issue by the-real-orson** [fantasycalendar/FoundryVTT-Sequencer#58]
**Describe the bug**
On screen load I get an error, I think the problem is with Autoanimations module, but thought I'd post it here in case I'm incorrect (I only understand the console enough to be dangerous).  :

Console Error info:
foundry.js:316 ReferenceError: isPrivate is not defined
[Detected 2 packages: autoanimations, sequencer]
    at autoAnimations.js:88:75
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at module.js:35:15

AutoAnimations js that is producing the error:
// Registers Database with Sequencer
Hooks.on("sequencerReady", () => {
    let obj01 = moduleIncludes("jb2a_patreon") === true ? JB2APATREONDB : JB2AFREEDB;

    Sequencer.Database.registerEntries("autoanimations", obj01, isPrivate = true);
    if (game.settings.get("autoanimations", "killAllAnim") === "off") {
        console.log("ANIMATIONS ARE OFF")
        socket.off('module.sequencer')//
        killAllAnimations = true;
    }
});

**To Reproduce**
1. log into game
2. check console for errors

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**

**Comment by Haxxer** [comment]
Are you on the latest Sequencer version?

**Comment by Haxxer** [comment]
Also, that seems like an error in Automated Animations, please post it on their repository. This is not the right place.
