### ISSUE TITLE
0.5.0 update and issues with the .name() call

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#6]
Using .name("namehere") in the first sequence, followed by atLocation("namehere") in the following sequence no longer works correctly after the 0.5.0 update. It seems to log the stored position a x: 0, y: 0. Using this sequence as a go-by (worked prior to update)

new Sequence()
    .effect()
        .atLocation(canvas.tokens.controlled[0])
        .reachTowards(canvas.tokens.controlled[1])
        .JB2A()
        .repeats(5, 500)
        .missed(true)
        .name("animation")
        .addOverride(
            async (effect, data) => {
                switch (true) {
                    case data._distance <= 1400:
                        data.file = "modules/jb2a_patreon/Library/Cantrip/Fire_Bolt/FireBolt_01_Dark_Red_30ft_1600x400.webm"
                        break;
                    case data._distance > 2600:
                        data.file = "modules/jb2a_patreon/Library/Cantrip/Fire_Bolt/FireBolt_01_Dark_Red_90ft_4000x400.webm"
                        break;
                    default:
                        data.file = "modules/jb2a_patreon/Library/Cantrip/Fire_Bolt/FireBolt_01_Dark_Red_60ft_2800x400.webm"
                }
                console.log(data)
                return data
            }
        )
        .effect()
            .atLocation("animation")          
.file("modules/jb2a_patreon/Library/Generic/Template/Circle/OutPulse/OutPulse_01_Regular_PurplePink_Burst_600x600.webm")
            .scale({x: .33, y: .33})
            .delay(1700)
            .repeats(5, 500)
            .belowTokens(true)
            .play()

**Comment by Haxxer** [comment]
Fixed in 0.5.1
