### ISSUE TITLE
startTime no longer allowed to exceed 1000ms

### ISSUE THREAD

**Issue by Z3nner** [fantasycalendar/FoundryVTT-Sequencer#62]
Create any macro that uses the ".startTime()" function.  Set the start time to any delay less than 1000ms and the macro will execute normally, playing at the indicated start time.
Now reset the start time to anything equal to or greater than 1000ms and the macro will no longer play that portion.  Console will return the following error.

'TimeRanges': The index provided (1) is greater than or equal to the maximum bound (1).
    at CanvasEffect.set video [as video]

**Comment by Haxxer** [comment]
Is the effect's duration longer than 1 second?

**Comment by Z3nner** [comment]
Yes.  The two I noticed this on included the JB2A eldritch blast and fireball.beam.orange.  Both are 4 seconds

**Comment by Haxxer** [comment]
Fixed in 2.0.15
