### ISSUE TITLE
Missing some JB2A animations (of white melee attacks) @ Sequencer Database Viewer

### ISSUE THREAD

**Issue by GenX187** [fantasycalendar/FoundryVTT-Sequencer#63]
Some animations (of white melee attacks) are no longer displayed in the JB2A database at  Sequencer Database Viewer!?
I don't know if the Sequencer module creates this DB or the JB2A module (I am a Patreon user and use the JB2A Complete Collection in Version 0.3.6).
Currently I miss the entries e.g. for GreatSword01_01_Regular_White_800x600 & HandAxe02_01_Regular_White_800x600

Errormessage old Macro usage
![Example_Missing_JB2A-Entrys](https://user-images.githubusercontent.com/35866459/152703579-6a2bb348-dd21-4adc-bc07-af2ae7aa9771.JPG)

Missing the entry at Sequencer Database Viewer
![Missing_JB2A-Entrys](https://user-images.githubusercontent.com/35866459/152703578-4d35aa1a-7575-4c87-b2c3-c7ec568bef78.JPG)

But the files exists in the folder
![Example_Missing_JB2A-Entrys_2](https://user-images.githubusercontent.com/35866459/152703575-ace720cb-eaa7-4ad9-9422-06165f97c21c.JPG)

Or is this a bug in the JB2A module?

**Comment by Haxxer** [comment]
You've gotten this mixed up - JB2A registers into Sequencer's database, but Sequencer is not responsible for that.

Think of it like this - Sequencer offers a blank book for others to write into - JB2A then writes into the book what they want Sequencer to know about, but Sequencer itself doesn't do the writing.

I suggest you contact JB2A instead.

**Comment by GenX187** [comment]
Ok, sorry for mixing up some things.
I wrote this ticket:
https://github.com/Jules-Bens-Aa/JB2A_DnD5e/issues/9
