### ISSUE TITLE
Suspected Memory Leak

### ISSUE THREAD

**Issue by GambetTV** [fantasycalendar/FoundryVTT-Sequencer#64]
**Describe the bug**
I am not 100% certain it's a memory leak and I'm not 100% certain your module is the culprit, as socketlib is a prerequisite of using this module. All I can say with certainty is that when I use this module in conjunction with JB2A animations and then either Warpgate or Automated Animations (or both), there is a persistent FPS drop that builds up over time, and seems to persist even after the animations end. 

For instance, using the Fireball macro packaged in the JB2A compendium, which requires this module and Warpgate to use, during the first use, my FPS will dip from 60 to 57 while the animation plays, but then it recovers to 60. I will then manually end the effect, as it lets a still frame linger persistently, so I end all effects after each use for the sake of the test.

After the second use, the initial FPS drop will be larger, and the lingering FPS drop will be around 5 FPS per use of the macro. Within ten uses of it my FPS is permanently below 30 FPS.

If I disable Warpgate and use the effects from the Automated Animations module, I see similar effects, although the specific FPS drop changes depending on what effect I'm using.

Now, I will say, when I only use the Sequencer Effects player, to manually drop in one effect at a time, I never see any persistent slowdown. Any FPS drop recovers when the animation finishes playing. Because of this, I cannot say with certainty that Sequencer is the culprit. But it feels like the likelihood is higher than it is with the other two modules, since I can reproduce the effect even if I disable Automated Animations and only use Warpgate with Sequencer, or vice versa turn off Warpgate and only use Automated Animations with Sequencer.

Hopefully this is helpful and can lead to rooting out this problem. Thanks.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Foundry App
 - Version: v9 build 249; sequencer 2.0.14

**Comment by Haxxer** [comment]
Thank you for the great breakdown - can you confirm that you have hardware acceleration enabled?

**Comment by GambetTV** [comment]
This is through the Foundry App itself.

**Comment by Haxxer** [comment]
Could you also post your system specs? I have quite a powerful rig so it's hard for me to replicate your issue, I'm afraid.

**Comment by GambetTV** [comment]
i7 7700K
32 GB RAM
AMD Radeon RX 6900 XT

I should point out that this occurs even when I'm just in the app by myself, but it also seems to be affecting all of my players, playing across a variety of systems, in various browsers, etc.

**Comment by Haxxer** [comment]
I changed some things around, and may have fixed it, but it's hard for me to tell;

![image](https://user-images.githubusercontent.com/12858387/152885919-90e3dc4f-c472-40ce-9a40-2c08e02dbd5b.png)

Even with this many, the FPS barely budges.

**Comment by Haxxer** [comment]
I hopefully fixed this in 2.0.15, please let me know if that's not the case!
