### ISSUE TITLE
[Suggestion] Add an option to remove Sequencer from Token Controls

### ISSUE THREAD

**Issue by Brimcon** [fantasycalendar/FoundryVTT-Sequencer#65]
The Controls being in Token Controls as well as having the sidebar for Sequencer tools feels redundant to me and the option to remove them from the sidebar removes all of them.

The use case here is when you have a lot of modules that utilize the side bar it tends to expand it quite far. 

![image](https://user-images.githubusercontent.com/7198283/156454025-b7f5079c-694f-4966-a369-4a3df63ba064.png)

I could just remove sequencer tools entirely but the convenience of having the Sequencer Layer in the sidebar is nice to have.

**Comment by Haxxer** [comment]
This setting already exists.

![image](https://user-images.githubusercontent.com/12858387/156454349-9da2bf02-62ee-4601-969f-53063a73829a.png)

**Comment by Brimcon** [comment]
Doing that removes the Sequencer Layer Button though, not just from Token Controls.
![image](https://user-images.githubusercontent.com/7198283/156454495-e76c6d63-a989-4d07-937a-1d995597e626.png)

**Comment by Haxxer** [comment]
Ah, so you want to control every tool individually.

**Comment by Brimcon** [comment]
Yeah. This tool here is what I want to remain. It has the same tools in the Token Controls, but with the added "Play" Button.
![image](https://user-images.githubusercontent.com/7198283/156454900-8fdb6cc7-54cb-471b-951e-97e6ffb49d3c.png)
