### ISSUE TITLE
Compatibility with DF Template Enhancements: Fix Square Template Rotation

### ISSUE THREAD

**Issue by Dialectikal** [fantasycalendar/FoundryVTT-Sequencer#68]
Hello,
I've noticed that the "Fix Square Template Rotation" option from DF Template Enhancements doesn't work with some Sequencer operations. Specifically, Automated Animations that utilize templates will fail with this option enabled. I don't really want to tell my players that they can't orient their spells this way, since I sometimes switch between theater of the mind and using the grid. The DF Template Enhancements provides an elegant solution for this.

The current workaround is for me to enable the option only when needed. It won't work with any animations, and it will cause clicking on certain spells to fail, but it will let me or my player drop a template with the desired orientation.

I've mentioned this to Otigon (Automated Animations) and flamewave000 (DF Template Enhancements), and they both said the limitation is on the side of Sequencer. Specifically, that Sequencer is expecting a Rect(x, y, width, height), while in the case of these adjusted squares, DF Templates is using a Polygon with 4 points.

The workaround is clunky and a bit slow, but I can get by with it. I'm just wondering if this could potentially be handled by Sequencer, or if maybe there is a better workaround I haven't considered.

Thanks

**Comment by Haxxer** [comment]
Fixed with https://github.com/flamewave000/dragonflagon-fvtt/issues/333
