### ISSUE TITLE
use JB2A from AWS S3 bucket

### ISSUE THREAD

**Issue by emwhalen** [fantasycalendar/FoundryVTT-Sequencer#69]
The storage limitations on my hosting solution make the in-Foundry JB2A Patreon module infeasible (it consumes a large amount of space). I typically upload large assets and libraries to my S3 bucket and pull from there. Sequencer doesn't appear to currently support JB2A being hosted anywhere but within Foundry's path, and I wish I could point it to the database in my S3 instead.

**Comment by Haxxer** [comment]
So you're also changing the database paths to point to your S3 bucket at the same time?

**Comment by Haxxer** [comment]
This would be more specifically up to JB2A to add an option to prepend an S3 bucket to their paths. As any module could register any files to the Database, it would be dangerous for Sequencer to assume anything about the paths - if anything, it should assume that people who are registering to its database knows what they are doing. What do you think @emwhalen ?

**Comment by emwhalen** [comment]
Ah, perhaps. I'll float the consideration with JB2A and get their thoughts. I'm not well enough versed in the backend of either system to know the best path.

**Comment by emwhalen** [comment]
Via the latest JB2A update, this issue is now resolved.
