### ISSUE TITLE
[Feature Request] Sequencer Effect Manager Expansion

### ISSUE THREAD

**Issue by otigon** [fantasycalendar/FoundryVTT-Sequencer#74]
**Is your feature request related to a problem? Please describe.**
Not related to any particular problem, just some feature requests I've run across for control of animations for Linked Tokens. 

**Describe the solution you'd like**
The ability for using ``Sequencer.EffectManager.getEffects(inFilters})`` and ``Sequencer.EffectManager.endEffects(inFilters})``  to accept a ``sceneId`` from an Inactive Scene. This would allow control of Linked Tokens to have animations read and removed across multiple scenes, both active and inactive.

**Describe alternatives you've considered**
No clear path for doing this, other than manually reading Seqeuencer flags on tokens from Inactive scenes and remove the flag data from the Token using ``token.unsetFlag()``.
I was attempting to do this as such:
```js
async function deleteEffectsAllScenes5e (effect) {
    let allScenes = game.scenes.contents;

    for (var i = 0; i < allScenes.length; i++) {
        let currentScene = allScenes[i];
        let currentSceneId = currentScene.id;

        let checkAnim = Sequencer.EffectManager.getEffects({ sceneID: currentSceneId, origin: effect.uuid})

        await Sequencer.EffectManager.endEffects({ sceneID: currentSceneId, origin: effect.uuid})
    }
}
```

**Additional context**
The use case for this in 5e is with Active Effect animations. Currently my RC build applies animations tied to Active Effects when a scene is loaded (Linked Tokens share the same Conditions AE's across scenes). However, when ending the Active Effect on an active scene, and thus removing the Animation via Sequencer, the effect will still persist on the Token on a different scene.

**Comment by Haxxer** [comment]
Added with 2.1.0
