### ISSUE TITLE
Performance drop when adding a new token to canvas

### ISSUE THREAD

**Issue by pbl3tech** [fantasycalendar/FoundryVTT-Sequencer#77]
I'm experiencing severe FPS drops when I add new tokens to canvas with Sequencer active. When I press "reload application", the fps drop disappears. Deleting tokens from canvas does not improve FPS.

**Comment by Haxxer** [comment]
Does this happen with only Sequencer installed?

**Comment by pbl3tech** [comment]
Do you mean installed or active?

**Comment by Haxxer** [comment]
Active.

**Comment by pbl3tech** [comment]
Yes - the only two active modules I have are Sequencer and its requirement, socketlib.

**Comment by Haxxer** [comment]
1. Are your modules up to date?
2. How powerful is your computer?
3. Could you please check your console for errors (F12 -> Console -> Copy red text)
4. Could you please check if this happens with every token, or specific ones?
5. Does this happen in a fresh world?

**Comment by pbl3tech** [comment]
1. Yes.
2. Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, NVIDIA GeForce RTX 2070, 16 GB RAM, Windows 10 64 bit.
3. No red text as far as I can see.
4. Seems to be happening with every token.
5. Yes.

**Comment by Haxxer** [comment]
I'm not sure then, no one else has reported this issue...

**Comment by BenChand** [comment]
Hi, I'm also getting this issue, and it's very easily reproducible for me.

1. My modules are up to date.
2. 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz  3.00 GHz
3. No console errors
4. It happens for every token
5. It happens in a fresh world

I've tried it with the windows foundry app, the chrome browser and firefox and they all have the same issue. Here's how to reproduce:

1. Create a new game world (I used dnd 5e as the system)
2. Install and enable Sequencer as the only module
3. Create a blank NPC
4. Create an empty scene
5. Repeatedly drag and drop the blank NPC onto the scene

My FPS starts at 50-60fps and drops to about 15-20fps after adding about 20 NPCs to the scene. If I refresh the page, or change scene, the FPS drop goes away.

**Comment by BenChand** [comment]
I think I'm starting to understand what's going on here and why performance is degrading over time. When an actor is dropped onto the canvas, `on_DropActorData` in `foundry.js` triggers a canvas layer to be activated. When this canvas layer is activated, it deactivates all the other canvas layers:

```
  /* -------------------------------------------- */
  /*  Methods
  /* -------------------------------------------- */

  /**
   * Activate the CanvasLayer, deactivating other layers and marking this layer's children as interactive.
   * @return {CanvasLayer}    The layer instance, now activated
   */
  activate() {

    // Set this layer as active
    const wasActive = this._active;
    this._active = true;

    // Deactivate other layers
    for (let name of Object.keys(Canvas.layers) ) {
      const layer = canvas[name];
      if ( layer !== this ) layer.deactivate();
    }
    if ( wasActive ) return this;

    // Assign interactivity for the active layer
    this.zIndex = this.getZIndex();
    this.interactive = false;
    this.interactiveChildren = true;

    // Re-render Scene controls
    if ( ui.controls ) ui.controls.initialize({layer: this.constructor.layerOptions.name});
    return this;
  }
```

Which brings us to `BaseEffectsLayer`'s `deactivate` function, that sets `isSetup` to false.

```
    deactivate() {
        super.deactivate();
        this._clearChildren();
        this.active = false;
        this.isSetup = false;
        InteractionManager.tearDown();
    }
```

After all this finishes, on the next tick, the `BaseEffectsLayer`'s `render` function is invoked, which runs `this._setup()` in its entirety since `isSetup` is now false, which proceeds to construct another copy of the `UIContainer` and add it as a child. I'm guessing that something is then trying to clear or render all these extra `UIContainer` instances and that's what's clogging the CPU.

**Comment by Haxxer** [comment]
Oh wow, thank you for that writeup!

**Comment by Haxxer** [comment]
Hm, could you add `if(!this.active) return;` below line 26 in that file, perhaps that could fix your issue?

**Comment by BenChand** [comment]
I tried commenting out `this.setup = false;` in the `deactivate` function and that fixes the performance issue. I'm not too familiar with how all this stuff works to know what the actual correct solution is here though 😄

**Comment by Haxxer** [comment]
@BenChand So my suggestion with the `if(!this.active) return;` didn't work?

**Comment by BenChand** [comment]
> @BenChand So my suggestion with the `if(!this.active) return;` didn't work?

If it carries on when it's active, then it will proceed to set `isSetup` as false right? I might be missing something, but the simple `this.setup = false` being commented out works 😄

**Comment by Haxxer** [comment]
Hopefully, 2.1.1 will have resolved this issue
