### ISSUE TITLE
Add layer above light layer for animation to be visible over fog & darkness

### ISSUE THREAD

**Issue by Killasaurus-Warbear** [fantasycalendar/FoundryVTT-Sequencer#81]
**Is your feature request related to a problem? Please describe.**
- If a scene has high darkness or unrevealed fog it can cause effects to be completely hidden behind vision walls. For most effects this is fine, but for things like lightning bolts, smoke clouds, etc it makes sense for these things to be seen in the distance above buildings/trees. 

**Describe the solution you'd like**
- Adding a layer above the light layer would allow animations to always be visible. Possibly alwaysVisible(). 

**Describe alternatives you've considered**
- The only solution I've found to completely solve this is disabling token vision. Revealing fog of war somewhat works if the darkness is low enough, but the fog still slightly conceals animations.

**Additional context**

**Comment by Haxxer** [comment]
Added in 2.1.1
