### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by pbl3tech** [fantasycalendar/FoundryVTT-Sequencer#83]
Sequencer seems to be affecting my performance. If previously I've experienced framerate issues only when adding new tokens to a scene, now my FPS drops by 10-15 while I have the module enabled, even on an empty scene. Disabling Sequencer returns FPS back to normal levels.

I'm running a PF1E game on Forge VTT. There are no error messages in the console. The problem persists on a newly created world as well. I am using the last version of the module and Foundry version 9 build 269.

**Comment by Haxxer** [comment]
Which version of Sequencer are you on?

**Comment by pbl3tech** [comment]
2.1.7

**Comment by pbl3tech** [comment]
Any updates?

**Comment by Haxxer** [comment]
No, I am on holiday for the next 10 days. I recommend contacting the foundry community regarding this issue, perhaps they can help you narrow it down within the module. Sequencer is open source, so anyone can make contributions.

**Comment by Haxxer** [comment]
Does this still occur @pbl3tech ?

**Comment by Kicktar** [comment]
This issue persists for one of my players (they're computer is the worst of the group) on 2.1.8. Didn't get a chance to test it with no other modules enabled, but I did test it without any dependents enabled.

From what we could tell, the lag was worse with larger tiles or larger background visible, and at no point was a sequence actually running or called.

**Comment by Kicktar** [comment]
I can also confirm that the issue persists on Sequencer 2.1.13, as I did quickly test that with my player before our game tonight.

**Comment by Haxxer** [comment]
Could both of you try to enable this setting in Sequencer's settings?

![image](https://user-images.githubusercontent.com/12858387/183760968-18159ef0-7838-4bc2-87af-a2ff03c1ade0.png)

**Comment by Kicktar** [comment]
Well, that appears to help partially here. My player's FPS went back up to without-sequencer numbers, but his controls were still responding extremely slowly or not responding at all as if the FPS were still in the 5-15 range. We also took this chance to try with just Sequencer (and socketlib) enabled, which made no change. Also tried just disabling Sequencer but leaving socketlib just to make sure it wasn't somehow that, and that was back to playable.

**Comment by KonteiKeisei** [comment]
I am having a similar issue. I noticed this in the log while sequencer is enabled:
![image](https://user-images.githubusercontent.com/49371326/186280274-47509746-43a8-47d0-a917-ee4abfd81b4f.png)

do you see that as well when verbose logging is enabled?

**Comment by Haxxer** [comment]
@KonteiKeisei 

I think I have nailed down this issue in the the beta branch, could you uninstall sequencer and then install it through this link?

https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-Sequencer/next/module.json

**Comment by KonteiKeisei** [comment]
Same issue with that version, though the messages have slowed down, still more than 5 a second and performance is terrible on large scenes:

![image](https://user-images.githubusercontent.com/49371326/186281043-545bf59f-60a9-44d8-96e4-420e0df9ff83.png)

**Comment by Haxxer** [comment]
I honestly don't know what could be causing the issue. There's nothing that should be running on Sequencer's side when you're just viewing a scene. Could you enable debugging in Sequencer's settings, refresh, and view the messages (and not warnings) and see if you spot any "Animation Engine Started"? This is the only thing that actively runs, but only when Sequencer is playing animations.

**Comment by KonteiKeisei** [comment]
No such messages. Nothing sequencer related running. Happens when sequencer is the only module enabled. and only on specific scenes. Better yet, if i recreate the scene, problem goes away. So its something in the scene itself that's causing it.

**Comment by Haxxer** [comment]
Can you please export the scene that's causing it, and upload it here?

![image](https://user-images.githubusercontent.com/12858387/186281869-8fed8233-a246-4246-ac0d-f7efed64d574.png)

**Comment by KonteiKeisei** [comment]
[ImpactedScenes.zip](https://github.com/fantasycalendar/FoundryVTT-Sequencer/files/9411087/ImpactedScenes.zip)

**Comment by Haxxer** [comment]
@KonteiKeisei Could you message me on Discord (Wasp#2005)? I would love to take a look on your server personally, because your scenes work fine on my end 😓

**Comment by KonteiKeisei** [comment]
absolutely!
