### ISSUE TITLE
Rendering issues due to Sequencer's hot-patching of PIXI texture loading

### ISSUE THREAD

**Issue by ofeldt** [fantasycalendar/FoundryVTT-Sequencer#86]
**Describe the bug**

On Chrome (103.0.5060.66 and at least one version) before I experience visual artifacts in rendering of animated webm files. This is true for ```Tile```s and Sequencer created elements. The artifacts are prominent in alpha transparent videos as alpha value might be doubly applied to the video texture object in PIXI. Changing the alpha mode in the marked line to: ```PIXI.ALPHA_MODES.NO_PREMULTIPLIED_ALPHA``` fixes the issue for me.

https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/c06de836ebe061243775a520076cd17fe5185368/scripts/libwrapper.js#L15

**To Reproduce**

1. Import provided ```Sequencer-Spell-5e-Generic-Healing``` macro.
2. Select a token.
3. Click on the ```Sequencer-Spell-5e-Generic-Healing``` macro.
4. See visual artifacts, as it's not a green circle with spark, but just a pixel blog over the selected token.

**Expected behavior**
Webm video files with a lot of alpha transparency to be rendered clearly.

**Screenshots**
Sorry, no screenshot, due to cross device.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 103.0.5060.66

**Comment by MrVauxs** [comment]
Done the Reproduce steps (with the exception of Importing the macro, I used it directly). No artifacts found.
- OS: Windows 10
- Browser: Chrome
- Version: 103.0.5060.66 (latest)
- Foundry: 9.269 (latest stable)
- Sequencer: 2.1.7 (latest)
Tested on Pathfinder 2e system, 3.12.0.8 (latest)

https://user-images.githubusercontent.com/32039708/176319593-60bc3d76-256d-42c2-af10-2478612c29b3.mp4

**Comment by Gazkhan** [comment]
Can't reproduce the error either : 

- OS: Windows 10
- Browser: Chrome(Version: latest v 103.0.5060.66)
- Foundry: 9.269
- System: DnD5e v 1.6.2 and 1.6.3 (latest)
- Sequencer: 2.1.6 and 2.1.7 (latest)

**Comment by MrVauxs** [comment]
Having applied the modification, there animations appear darker, as if they had shadows.

https://user-images.githubusercontent.com/32039708/176320456-30e0fe94-06bb-4b97-bdcf-a787537e0c95.mp4

**Comment by Haxxer** [comment]
@Firehouse-Games @ofeldt Could you update sequencer and enable this module setting and see if that fixes it for you?

![image](https://user-images.githubusercontent.com/12858387/177209595-8ef0a765-6de4-4a41-98cb-08931a9a1d6f.png)

**Comment by Firehouse-Games** [comment]
It worked, problem solved! Thank you
