### ISSUE TITLE
Allow a 'min' and 'max' for `waitUntilFinished`

### ISSUE THREAD

**Issue by dmrickey** [fantasycalendar/FoundryVTT-Sequencer#87]
Right now `waitUntilFinished` takes no value (i.e. exactly when it ends) or a single value )an offset from the end of the effect). It would be nice if we could pass in two values and get a random offset between those two values from the end (basically just like `delay`)

**Comment by Haxxer** [comment]
@dmrickey Could you perhaps post a macro that would demonstrate an use case with this?

**Comment by Haxxer** [comment]
Added in 2.1.9
