### ISSUE TITLE
Allow default Sequencer keybinds to be deleted

### ISSUE THREAD

**Issue by weepingminotaur** [fantasycalendar/FoundryVTT-Sequencer#89]
Currently, Sequencer has multiple keybinds that cannot be deleted, which results in conflicts being displayed with keybinds from other modules. It would be great if one could delete the default keybinds (in addition to adding one's own, which is currently permitted).

**Comment by Haxxer** [comment]
These keybinds only work on the Sequencer effect layer, what are the conflicts that are cropping up?

**Comment by Haxxer** [comment]
Added in 2.1.9
