### ISSUE TITLE
playbackRate() changes effect duration rather than speed

### ISSUE THREAD

**Issue by Vauryx** [fantasycalendar/FoundryVTT-Sequencer#90]
Using .playbackRate() In an effect causes the effect's duration to change but not its speed.
For example,  .playbackRate(2) is cutting the length in half but not changing the speed

![Foundry_Virtual_Tabletop_Dk7Vrx3XZy](https://user-images.githubusercontent.com/32877348/177879136-bb4dc5b4-811f-4b1f-b7d7-da5d41a2bc7e.gif)

Script for reproduction:
``` const caster = canvas.tokens.controlled[0];
const target = Array.from(game.user.targets)[0];

if(!caster){
    ui.notifications.error("No caster");
    return;
}

console.log("Caster: ", caster);
console.log("Target: ", target);

let introSeq = new Sequence();
introSeq
    .effect()
    .file('jb2a.energy_strands.in.blue.01.1')
    .atLocation(caster)
    .scale(0.5)
    .playbackRate(1)
.play() 
```

Tested on Sequencer 2.1.8

**Comment by Haxxer** [comment]
Fixed in 2.1.9
