### ISSUE TITLE
Random Effects

### ISSUE THREAD

**Issue by Boifuba** [fantasycalendar/FoundryVTT-Sequencer#91]
Hi, i'm not a programmer so i'll try to explain using examples. i'll use this macro as example:

let tokenD = canvas.tokens.controlled[0];
```
.effect()
        .file("/effects/fire01.webm")
        .scale(1.0)
        .atLocation(tokenD)
        .spriteOffset({ x: -10, y: -70 })
        .fadeIn(300)
        .fadeOut(1000)
        .persist()
 .play()
```

My idea is randomize this macro between these below effects each time i click the macro. 

/effects/fire01.webm
/effects/fire02.webm
/effects/fire03.webm
/effects/fire04.webm

Can be possible! 

Thanks for all the hard work!

**Comment by Haxxer** [comment]
Already supported.

```
effect()
        .file(["/effects/fire01.webm, "/effects/fire02.webm", "/effects/fire03.webm", "/effects/fire04.webm"])
        .scale(1.0)
        .atLocation(tokenD)
        .spriteOffset({ x: -10, y: -70 })
        .fadeIn(300)
        .fadeOut(1000)
        .persist()
 .play()
```

https://github.com/fantasycalendar/FoundryVTT-Sequencer/wiki/Effects#file

"This may also be an array of paths, which will be randomly picked from each time the effect is played."
