### ISSUE TITLE
Sequencer.EffectManager.endEffects not retrieving list

### ISSUE THREAD

**Issue by Boifuba** [fantasycalendar/FoundryVTT-Sequencer#93]
![image](https://user-images.githubusercontent.com/21176804/179437682-64ed7f30-2cfb-4e95-b78e-09b00916705d.png)

I can.t retrieve a list of active effects with these commands
![image](https://user-images.githubusercontent.com/21176804/179437746-252c0930-c22d-45bf-beb8-ae3be80f2a97.png)

My macro have .name and is active

**Comment by Haxxer** [comment]
Could you please provide more information? There is a bug ticket template to follow that asks for module versions, foundry version, browser version,.etc.

Please also post your macro, as I cannot read minds

**Comment by Haxxer** [comment]
@Boifuba Please read above.

**Comment by Haxxer** [comment]
Closing.
