### ISSUE TITLE
Update Existing Effects on Token Updates

### ISSUE THREAD

**Issue by MrVauxs** [fantasycalendar/FoundryVTT-Sequencer#94]
**Is your feature request related to a problem? Please describe.**
When using various effects, one might stumble into a situation where say, a Spell enlarges your token, making it 2 x 2 rather than 1 x 1. With that change, all pre-existing effects are now too small, and need to be reapplied (assuming they are using `scaleToObject`).

It would be great that Sequencer would automatically update effects using `scaleToObject` whenver a Token changes size or scale.

**Describe the solution you'd like**
Have Sequencer update effects with `scaleToObject` upon the object changing size or scale.

**Describe alternatives you've considered**
No real alternatives considered.

**Additional context**
Would be great for players who often have permanent effects on them, such as equipped floating items around them, or auras, or some persistent condition.

**Comment by EternalRider** [comment]
Same Needs, It's very important.

**Comment by Haxxer** [comment]
Fixed with 3.2.0
