### ISSUE TITLE
Ouija board not working

### ISSUE THREAD

**Issue by davelamorte** [fantasycalendar/FoundryVTT-Sequencer#95]
**Describe the bug**
I wanted to use the great Ouija board sample but when I click "move" on the macro generated panel, nothing happens.

**To Reproduce**
I tried creating a new world, 5e system, no modules except Sequencer and the animated-spell-cartoon.
Nothing changed between my clean new world and my main campaign one, so it's not a module incompatibility I guess.
Sequencer works, I even tried with Automated Animations module and they all work as expected.

**Expected behavior**
I have followed the instructions: created a new actor, assigned the pointer token to it, deleted the old token and moved the actor inside the map; used the macro; I click MOVE and nothing happens.

Foundry v9.269
5e system 1.6.3

**Comment by Haxxer** [comment]
Fixed in 2.1.13
