### ISSUE TITLE
Canvas drawing failed: The BelowTokensEffectsLayer subclass of CanvasLayer must define the _draw method

### ISSUE THREAD

**Issue by yakuzadave** [fantasycalendar/FoundryVTT-Sequencer#97]
**Describe the bug**
Sequencer Module no longer loads in Foundry V10 Testing 5 - Build 279 and hangs on loading Canvas with the following errors (one in Dev Tools Console and one as a UI Toast Notification).

**UI Error**
```
Canvas drawing failed: The BelowTokensEffectsLayer subclass of CanvasLayer must define the _draw method
```

**DevTools Console**
```
lib.js:335 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
[Detected 1 package: sequencer]
    at Module.get_all_documents_from_scene (lib.js:335:37)
    at SequencerEffectManager.setUpPersists (sequencer-effect-manager.js:334:32)
get_all_documents_from_scene	@	lib.js:335
setUpPersists	@	sequencer-effect-manager.js:334
await in setUpPersists (async)		
(anonymous)	@	module.js:35
setTimeout (async)		
(anonymous)	@	module.js:30
#call	@	foundry.js:688
callAll	@	foundry.js:645
setupGame	@	foundry.js:7772
```

**To Reproduce**
1. Update to latest version of Foundry and Sequencer
2. Load Game World
3. Enable Sequencer Module in game settings
4. To roll back and get canvas to load, just disable the Sequencer module and reload application.

**Expected behavior**
- Sequencer loading and being able to add effects via macros or manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/34697131/187767738-89b65eab-db51-4cfe-9ee7-8f4f12a5f13a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by Haxxer** [comment]
Module is not yet V10 compatible.

**Comment by yakuzadave** [comment]
@Haxxer 

I saw the new Alpha release that for v10 and I got a chance to install it via the JSON file.  Looks like this resolves the issue I was seeing and everything loads.  Great work!
