### ISSUE TITLE
Error in Foundry v10

### ISSUE THREAD

**Issue by Kharmans** [fantasycalendar/FoundryVTT-Sequencer#98]
**Describe the bug**
When use the module with Foundry v10, the maps doesn't load.

**To Reproduce**
Just active the module and try to load any map.

**Screenshots**
![image](https://user-images.githubusercontent.com/112586547/187783095-d463b3cd-47d0-4efd-b42f-c45f7e43daee.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit Version 21H2
 - Browser OperaGX
 - Version LVL4 (core: 89.0.4447.104)

**Comment by Haxxer** [comment]
Sequencer is not V10 ready.
